### ISSUE TITLE
Ubuntu 17.10 Alt not passed 

### ISSUE THREAD

**Issue by coolemza** [FreeRDP/Remmina#1342] opened 2017-10-26 11:01 UTC
* Client (OS name and version): Ubuntu 17.10
* Remmina version (remmina --version): 1.2.0-rcgit-24 (git rcgit-24)
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Xubuntu 17.04
* Connecting via (RDP, VNC, ...): RDP

"Alt" stopped passing after upgrading from 17.04 to 17.10, 1.1.2 version have same issue

**Comment by giox069** [comment] 2017-10-26 11:56
Are you using Unity under Wayland/XWayland? This can be similar to issue #1086 if you are running under wayland.

**Comment by coolemza** [comment] 2017-10-26 13:12
yes, you right, its the same

**Comment by julian-alarcon** [comment] 2017-12-23 23:20
This should be closed and marked as duplicated of #1086

**Comment by antenore** [comment] 2017-12-23 23:33
Good point @julian-alarcon 

Duplicate of #1086

**Closed by antenore** 2017-12-23 23:33 UTC
Labels: duplicate
