### ISSUE TITLE
clipboard not synchonizing between RDP sessions and host

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [FreeRDP/Remmina#556] opened 2015-04-15 10:29 UTC
host: Ubuntu 14.04.2 LTS
Remmina 1.1.1-1+739+next+201504141816~ubuntu14.04.1
RDP Windows 7 x64

Neither copy from host to RDP nor copy from RDP to host is working in the last few builds

**Comment by giox069** [comment] 2015-04-15 11:08
Which kind of data are you copying ? Text or images or other data ?
Please check on the connection profile settings, advanced tab, you have not checked "Disable clipboard sync".

**Comment by realdreams** [comment] 2015-04-15 11:13
I was copying text. "Disable clipboard sync" is not checked. Clipboard worked before but sometimes it caused the RDP session to be unresponsive for several seconds (a few builds back). Now it stopped working completely.

**Comment by giox069** [comment] 2015-04-15 12:56
Did you copy a big amount of data (ie: an image) over a slow network connection before copying the text ? Please try to close and reopen the RDP connection to the server and see if clipboard transfer starts working again.

**Comment by realdreams** [comment] 2015-04-15 13:06
It's copied over LAN, just text. I restarted remmina and the clipboard started working, but still there were times when I tried to copy some text into the RDP session, the paste inside RDP wasn't greyed out but nothing showed up after pasting.

Copying image from browser (copy image) into RDP session does not work. I will report back with more testings.

**Comment by giox069** [comment] 2015-04-15 13:18
Thank you for testing and reporting.
Your testing results will be appreciated.

**Comment by realdreams** [comment] 2015-05-26 16:12
With 1.1.1-1+749+next+201505190046~ubuntu14.04.1, using clipboard or contect menu (right click) in remmina RDP often causes remmina to become unresponsive for a few seconds. And I am unable to copy/paste even inside the same RDP session. Only text was copied into clipboard.

**Comment by codeocelot** [comment] 2015-06-23 18:51
I can confirm the bug is happening to me on my ubuntu 15.04 host w/ Win Server 2012 R2 Datacenter (Azure VM).  Toggling 'Disable sync' under 'Advanced Settings'  didn't help. 

I don't recall this always being an issue.  I'll keep an eye out for what variable might be causing this.

**Comment by micsutka** [comment] 2015-07-08 11:23
host    Ubuntu 14.04.2 LTS
Remmina 1.1.1-1+761+next+201506260301~ubuntu14.04.1 
RDP to  Windows XP SP3 32bit
"Disable clipboard sync" is not checked.

Coping any text from host to RDP works, but coping any text from RDP to host does not work.
I've restarted everything (host, client, rdpclip.exe, reconnect, logoff), but no luck.

Previously I used remmina without ppa: clipboard sync in version 1.0.0-4ubuntu3 (0.9.99.1) worked.

**Comment by zajc** [comment] 2015-07-11 15:04
I have the same issue no matter which version I'm using (Xubuntu 15.04 or remmina-next ppa). Clipboard is not working no maatter what I do and this is very annoying.
I must use xfreerdp 1.1.0 from commandline instead remmina.

**Comment by micsutka** [comment] 2015-07-11 17:51
Why is this issue still in unconfirmed state?
Because we are waiting to a new stable freerdp (https://github.com/FreeRDP/FreeRDP/issues/2678#issuecomment-118784535)?

**Comment by giox069** [comment] 2015-07-11 18:07
@micsutka: its' unconfirmed because it's a bit hard to reproduce and we had no time to test it a lot. It seems that for some people (me included) the clipboard stops working after some time we use remmina, and it's impossible to understand when it happens. For other people, the clipboard never works.
I think I will take a look at the code during the next week.

**Comment by grexe** [comment] 2015-11-11 12:12
any progress on this? I also cannot use the clipboard between host and RDP session at all, inside the remote session it works.

**Comment by antenore** [comment] 2015-11-18 17:06
Can you please confirm if the problem happens when you have only one remmina (RDP) session opened?

**Comment by asdfljdasflkjwfd** [comment] 2015-11-19 01:48
From my experience this issue has been fixed for a while. Are you running the version from Ubuntu ppa?

**Comment by ronpike** [comment] 2015-12-02 18:53
I am on Ubuntu 15.10 and I periodically lose the ability to clip from host to remote/remote to host.  If I logout of my workstation and back in, the ability to clip returns.  thanks.

**Comment by antenore** [comment] 2015-12-02 19:39
@ronpike which version of Remmina do you have?

**Comment by ronpike** [comment] 2015-12-02 19:53
@antenore 1.1.2  (version that came with Ubuntu 15.10 I believe)

**Comment by antenore** [comment] 2015-12-02 21:24
We don't support anymore that version, you should follow the wiki to install remmina from our main branch (next).

We have an official ppa.

```sh
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard
```

Please, read before to post questions to old threads.

**Comment by ronpike** [comment] 2015-12-03 05:29
Ok, thanks - Google search led me to the thread!  :)

**Comment by zajc** [comment] 2015-12-06 10:36
I found out Remmina 1.2.0-rcgit.5 (Ubuntu 15.10) clipboard sometimes doesn't work in fullscreen. I have also checked with xfreerdp 1.2.1-dev and copy between hosts and guest doesn't work while in fullscreen. I guess it is freerdp issue.

**Comment by micsutka** [comment] 2015-12-06 10:39
I've changed from Ubuntu to Debian and from Remmina to xfreerdp.
This was the only way I could get a stabe RDP client solution on linux.

**Comment by ronpike** [comment] 2015-12-06 18:12
@zajc - @micsutka - Thanks  I am on the new Remmina version and am still
having clipboard issues.  For example copying a Chrome web page image on
the host to an Outlook email in a remote session.

Also on the new version I would like to be able to move the toolbar to the
top of the Remmina window (where it was located on the older version).

**Comment by giox069** [comment] 2015-12-06 21:00
@ronpike: the clipboard problems are currently under investigation. But you should in some way check your libfreerdp version to be updated. The ubuntu PPA "remmina-next" currently has an old version of libfreerdp (1.2) and we are working on these days to have it updated to the current git version (2.0).

The toolbar on the left is drag&drop-able with your mouse. Just move it to the top.

**Comment by wayne13** [comment] 2015-12-23 18:24
Hey guys,  whats the status of the clipboard issue? Ubuntu trusty into xrpd.  Using 1.2.0-rcgit.7.  Any work arounds?  Thank you for this nice software!

**Comment by ronpike** [comment] 2015-12-23 20:15
@wayne13 Remmina 1.2.0-rcgit.7 with freerdp-x11 1.2.0~git20150207+dfsg-0wily1 is working nicely for me currently on Ubuntu 15.10.   

Yes, it is an excellent program- thank you Remmina team!

**Comment by giox069** [comment] 2015-12-23 20:22
About the PPA update: currently the freerdp version included in the remmina-next PPA is blocked to git20150207. We are waiting an update from the PPA maintainer.
About the clipboard issue: @wayne13 can you reproduce your problem and describe it opening a new issue? This issue is closed and was dated April...
@ronpike thank you :)

**Comment by zajc** [comment] 2016-01-12 14:33
I found out the connection why the clipboard between RDP sessions and host sometimes doesn't work on my computer (Ubuntu 15.10, Remmina 1.1.2 or 1.2). If I use VirtualBox, clipboard stops working. If I turn off the Virtualbox and Remmina and then start Remmina again the clipboard works again. I hope this helps somebody.

**Comment by nakedhitman** [comment] 2016-01-17 02:14
@zajc I think you nailed it. This was also affecting me when using the KVM Virtual Machine Manager (virt-manager). Closing virt-manager and reconnecting to the RDP desktop restored clipboard functionality for me. Thankfully, KVM allows the VM to run in the background without a client connection, since it was hosting the VM I wanted to connect to :P

Is there anything that Remmina/FreeRDP can do to ensure dominance over the keyboard/clipboard when it is the active window? I'm sure the same tricks that the virtual machine consoles use to steal input can be made to serve Remmina instead...

**Comment by jkldgoefgkljefogeg** [comment] 2016-01-17 22:32
I can confrim the clipboard does not work when virtualbox 5.0.10-dfsg-2ubuntu1 and remmina 1.1.2-ppa1+819+next+2016011218 are both viewing Windows 7 (2 independent instances).

**Comment by zajc** [comment] 2016-01-20 11:36
The workaround in Ubuntu is to run headless Virtualbox VM (shift+START button) and access it via Remmina (RDP). The clipboard works fine after.

**Comment by nakedhitman** [comment] 2016-02-01 17:42
The issue has reoccurred for me even without a VM client session running. RDP connections to desktops do not sync the clipboard. I uninstalled VirtualBox, KVM/libvirt does not have any VMs or clients running, and VMware Workstation is not running (kernel module not loaded). Any other thoughts on what might cause this? I am running OpenSUSE Tumbleweed x64.

**Comment by TNSC-DanB** [comment] 2016-02-01 21:19
Same issue here, Ubuntu 15.10, newly built machine, issue existed with the Ubuntu version and exists now with the PPA version

**Comment by TNSC-DanB** [comment] 2016-02-01 21:21
Fixed by doing apt-get purge remmina and apt-get install remmina, now it works.  Previously when I switched from Ubuntu version to PPA version I just did apt-get remove and apt-get install.  Let's see if it sticks!

**Comment by nakedhitman** [comment] 2016-02-02 17:28
Turns out I was on an ancient version of remmina. Upgrading via a more up-to-date repository did the trick for me.

**Comment by TNSC-DanB** [comment] 2016-02-02 18:31
Randomly started happening to me again today.  Not sure what the trigger was, not running any other remote control or VM software on this machine.

**Comment by MalcomPT** [comment] 2016-02-23 15:34
remmina:
  Installed: 1.1.1-2

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie

I also have clipboard issues, it usually doesn't work.

**Comment by realtelematics** [comment] 2016-02-24 07:16
I have found that if you open a second rdp session the clip board stops working.
I reboot my box to get it working again. Restarting Remmina does not help.
I have resorted to doing second RDP inside my existing RDP session....its painful!

**Comment by giox069** [comment] 2016-02-24 09:39
@MalcomPT: We cannot patch stock versions of remmina you find in current distributions. You should try to obtain a newer version of remmina (1.2.0-rcgit8), retest and post results here. See the wiki.

**Comment by Demontager** [comment] 2016-02-26 15:57
So only way to get remmina 1.2.0-rcgit8 is to build from source, right ?
As i see repository ppa:remmina-ppa-team/remmina-next contains 1.1.2 version.

**Comment by giox069** [comment] 2016-02-26 18:02
it's a file naming problem on the PPA package. But the contained remmina is 1.2 and in sync with our "next" branch. In the last 2 days we had a problem for the 16.04 version of the PPA which did not compile correctly. We will fix it.

**Comment by Demontager** [comment] 2016-02-26 18:55
I really confused. I added ppa:remmina-ppa-team/remmina-next and installed remmina from there.
Version shown in About page states that it is 1.1.2 . Do I have actual 1.2.0 or 1.1.2 installed ?
![1bbscreenshot_2016-02-26_20-51-22](https://cloud.githubusercontent.com/assets/7040503/13362093/21b99424-dccb-11e5-969d-28fc06a7e781.png)

**Comment by giox069** [comment] 2016-02-26 20:20
The version in that dialog box is the real version, so... you are running remmina 1.1.2. Maybe the old remmina process has been running. Try to reboot the computer, or just  `killall remmina`, restart remmina, reopen the About dialog and see if it's remmina 1.2.0-rcgit8.

**Comment by Demontager** [comment] 2016-02-26 21:04
Yeap, this was a problem recent remmina was still running. Now About shows 1.2.0-rcgit.8 (git n/a)
And clipboard copying host<--->rdpserver working for me now nicely, thank you for fixing!

**Comment by giox069** [comment] 2016-02-26 21:09
:+1: there are still some issues with the clipboard in remmina 1.2.0-rcgit.8. Unfortunately I'm unable to reproduce and debug them, due to poor info and lack of time. So feel free to post here if you find something useful.

**Comment by sentient** [comment] 2016-03-03 00:50
![image](https://cloud.githubusercontent.com/assets/183579/13481001/ce71e864-e096-11e5-87dd-0aee6b441d43.png)
1.2.0 fixed it for me as well (after the > killall remmina )

**Comment by mallxs** [comment] 2016-03-13 01:37
I'm still on 1.1.0 But if the copy/past stops working, just restart remmina
Not just close the window; the remmina process keeps running in the background.
killall remmina will do the job.

**Comment by giox069** [comment] 2016-03-13 09:17
@mallxs: this issue has been closed a long time ago. Please don't add comments to closed issues, and report only when using the latest version of remmina (1.2.0-rcgit.10).

**Comment by Fexxer** [comment] 2016-03-22 20:22
I am using 1.2.0-rcgit.10 and RDP clipboard is working fine with Windows7 RDP servers in both directions, however with Windows XP servers the clip board only functions when transfer is Linux to Windows.  In the other direction "Paste" is available but the paste operation does nothing.  This is doing text only transfers.

Remmina = Awesome utility otherwise :)

**Comment by zajc** [comment] 2016-04-12 09:27
Just an INFO for those involved in this closed thread. At the moment I'm using the latest 1.2.0-rcgit.11 and I found out why clipboard was not working. The reason was teamviewerd service. I uninstall Teamviewer and now the clipboard works.

**Comment by pc-wurm** [comment] 2016-06-14 14:00
+1 @mallxs Thanks!

>$ killall remmina

**Comment by cmcanulty** [comment] 2016-06-19 13:13
It won't work for me since upgrade to xubuntu 16.04, very annoying. I have all pkgs updated on all machines

**Comment by sxc731** [comment] 2016-07-07 08:42
**First off, thank you so much for an amazing piece of software!** (and apologies for posting on a closed bug but maybe this helps someone else or even narrowing down the bug).

In my case, the "Always show tabs" option is what broke clipboard sync.  I ticked it back on and everything is honky-dory again!

Version info: "about" says 1.1.2; apt says 1.1.1-ppa1+484+201508180831~ubuntu14.04.1.  This is on stock Ubuntu 14.04.3 LTS.  I tried 1.2.0-rcgit-xx but it was too unstable for me (problems with custom resolution settings), so went back to 1.1.x

**Comment by cmcanulty** [comment] 2016-07-07 12:29
nice, unfortunately didn't do a thing to fix it for me

**Comment by dimonf** [comment] 2016-07-12 10:16
ubuntu 16.04 / remmina 1.2.0-rcgit.14 (git n/a):

no clipboard sync. neither of the above methods works.

**Comment by yanickrochon** [comment] 2016-07-12 16:51
Ubuntu 16.04 / Remmina 1.1.2 (APT install) does not work either. No solutions were able to solve it. This issue is closed, but the problem is still occurring. If the fix is confirmed, why isn't it pushed to the repositories? This is not a trivial issue....

**Comment by sxc731** [comment] 2016-07-12 17:37
Perhaps a couple more things in addition to my above post might help it work?

1. Ensure the 'Grab all keyboard events' option is enabled in the toolbar (if the toolbar is hidden, make it appear with right-CTRL+T).  I think this is a per-session setting so if you have several open, you may need to enable this for each.
2. After you have "Always show tabs" (per previous comment) and "grab all keyboard events" enabled, do a Remmina cold-start: exit all windows and check with `ps -ef | grep -i remmina` that all processes are gone before restarting it.

I had a re-occurrence of the problem recently and it only started working again after I went through the above steps.  Since then, all good but obviously YMMV...

**Comment by yanickrochon** [comment] 2016-07-12 17:48
@sxc731 doesn't work for me.

**Comment by giox069** [comment] 2016-07-12 17:54
@yanickrochon why remmina 1.1.2 ? Have you tried the current version 1.2.X of remmina ?
Follow the instruction on the [remmina wiki main page](https://github.com/FreeRDP/Remmina/wiki) to install it from the ubuntu's PPA.

**Comment by cmcanulty** [comment] 2016-07-12 18:00
that worked for me from my ubuntu client  to a windows server but not ubuntu to ubuntu. However thank you so much for the toolbar hint, I thought it was gone forever. I still have no main toolbar in the remmina interface but now do in the remote  connections. I absolutely hate the disappearance of toolbars etc in the "modern" interfaces. I am running 1.2.0-rcgit.14 (git n/a). Is there a way to get the toolbar back on the remmina main page?

**Comment by sxc731** [comment] 2016-07-12 18:13
@cmcanulty: Main menu -> View -> Toolbar ?  Also the toolbar on the connections window can be controlled from Edit -> Preferences -> Options ("Hide toolbar in the tabbed interface").  I'm still on 1.1.2 so YMMV ;-)

**Comment by yanickrochon** [comment] 2016-07-12 18:17
@giox069 this is from Ubuntu MATE's official repository (v.1.1.2), from a fresh install of 16.04. If the repository is outdated, my point still stands; why wasn't the official repository updated?

**Comment by cmcanulty** [comment] 2016-07-12 18:21
the new version I have only has a top panel with a + sign for adding a new connection , the quick connect box, and a three line thing on the right you can click to reach options. No main menu, that is what I want back. I can get the other toolbar from a remote connection with the rt ctrl+T but no toolbar before I open a connection

**Comment by giox069** [comment] 2016-07-12 18:24
@yanickrochon: remmina 1.2 depends on FreeRDP's libfreerdp 2.0, which cannot be included in current standard distributions because it's considered to be unstable by the developer.  We can't do anything for this. And this is because we created the PPA for remmina 1.2 and freerdp 2.0.

**Comment by giox069** [comment] 2016-07-12 18:30
@cmcanulty: the menu is the menu on the right: https://github.com/FreeRDP/Remmina/pull/875

https://plus.google.com/communities/106276095923371962010

![selezione_012](https://cloud.githubusercontent.com/assets/5477803/16778699/7157439a-486f-11e6-967b-23841d1139a3.png)

**Comment by dimonf** [comment] 2016-07-12 19:17
Didn't help. I connect from Ubuntu 16.04 to Windows7 VM, both versions,
1.1.2 and 1.2 (version from PPA), lack clipboard sync. This problem was
unknown to me when before I upgraded from 14.04 to 16.04

Anyway, thank you for reply.

**Comment by antenore** [comment] 2016-07-12 19:22
@dimonf if you have both versions installed, it won't ever never work. Remove, plus purge the old remmina and freerdp packages, than be sure you don't have a team viewer instance running.

**Comment by giox069** [comment] 2016-07-12 19:23
and don't forget to reboot the PC.

**Comment by dimonf** [comment] 2016-07-14 07:30
Doesn't seem working. I purged all dependencies before fresh installation
from ppa with no improvement.

**Comment by cmcanulty** [comment] 2016-07-14 23:40
it seems so weird that linux-windows clipboard works but linux-linux it doesn't

**Comment by dimonf** [comment] 2016-07-15 04:58
I connect from Ubuntu 16.04 to Windows7 via RDP. For Linux-Linux I don't
need RDP at all )

**Comment by sw-pawelg** [comment] 2016-12-08 10:17
This seems to fix both:
- clipboard issue
- unable to connect issues

in Remmina for me

`rm ~/.freerdp/known_hosts`

**Comment by alexeyzimarev** [comment] 2017-08-02 07:35
Using latest Reminna from the PPA solved the clipboard issue for me.

**Comment by cmcanulty** [comment] 2017-08-02 14:45
Still doesn't work for me either in LAN or WAN. Using xubuntu 16.04 all updated and remmina next ppa. It is really a inconvenient feature to not have working.

**Comment by princeofmars** [comment] 2017-08-14 14:13
Confirming it also does not work from ubuntu-gnome 17.04===>rdp===>windows 7

**Comment by cmcanulty** [comment] 2017-08-14 15:48
This may clarify the cause . I can copy and paste in remmina between windows machines but not linux.

**Comment by ndemou** [comment] 2018-01-29 22:18
Sorry if posting on a closed issue is not a good idea but I don't have a better one. I wanted to clarify something for those that have issues with teamviewer blocking remmina's copy-paste like myself: You do not need to uninstall teamviewer. A sudo killall teamviewerd is enough.

**Comment by cmcanulty** [comment] 2018-01-30 11:04
I also found a workaround for clipboard not working over WAN going from  linux to linux. Go to remmina on local machine and under prefernces-rdp-uncheck-use cliant keyboard mapping. Fixed an issue that has been causing me major issue for months.

**Comment by tpraxl** [comment] 2018-03-11 14:57
@cmcanulty "Use client keyboard mapping" was not checked. Still it doesn't work for me.

**Comment by cmcanulty** [comment] 2018-03-11 21:06
It's weird, I looked all over for a keyboard setting and there was none. Now in Remmina 1.2.0-rcgit-27 which is what I have installed, it is in preferences-rdp and I uncheck use client keybord mapping in client and server. Still I can't copy and paste  from a  client to server. Hope they fix that soon.

**Comment by antenore** [comment] 2018-03-12 07:27
Do you guys are using wayland?
It seems that clipboard support in FreeRDP, the library we use underlay, it's not yet implemented yet, so, even if in Remmina is implemented, there are probably some borderlines cases were it fails.

https://github.com/FreeRDP/FreeRDP/issues/3414#issuecomment-309036755 

I'd try to install XWayland and restart Remmina (probably a reboot won't hurt).

Please let me know, I'm reopening this.

**Comment by giox069** [comment] 2018-03-12 07:49
@antenore: remmina uses the standard GTK clipboard. Remmina uses libfreerdp only to route clipboard events from the remote server and then sends them to the local GTK clipboard. No local clipboard processing is done in libfreerdp. Local keyboard processing is done inside xfreerdp, but we do not use xfreerdp.
Al problems I had recently with the clipboard were due to the remote windows server having problems (maybe with th cliprdr process). Just closing the remote sessions with a real logoff from the windows server, not a simple disconnect, and repoening a new sessions, makes the clipboard work again.
It's important to do a real logoff from the remote windows server, not a simple disconnect.

Also please note: this thread is too old and give us a lot of confusionary information. There is no interesting technical data here to really try to identify a problem: it refers to old code (2015). And which server are you connecting to? Which remmina version are you using? Have you tried to logoff/logon or reboot the remote server?
I really advise all people here to open a new issue, reporting all the needed data.

Thank you.

**Comment by antenore** [comment] 2018-03-12 08:14
closing as per @giox069 comments.

**Closed by antenore** 2018-03-12 08:14 UTC
Labels: unconfirmed
