### ISSUE TITLE
Share folder date & time

### ISSUE THREAD

**Issue by markohrastovec** [FreeRDP/Remmina#934] opened 2016-07-26 12:56 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
- Client (OS name and version): Ubuntu 16.0.4.1
- Remmina version (remmina --version): 1.2.0-rcgit.14
- Desktop environment (GNOME, Unity, KDE, ..): Gnome
- Connecting to (OS and version): Windows 8
- Connecting via (RDP, VNC, ...): RDP
- RDP issues only, freerdp version (xfreerdp --version): 2.0.0-dev

Hi,

I have problems when saving files via share folder. When I save files from Windows to Linux host, the date and time of the file are completely wrong. They are approximately 5 years off. Files I saved today (2016-07-26) have date 2016-07-23 on linux. That is causing me problems because I cannot sort files according to their dates any more. This used to work properly in older versions on Remmina.

Regards
Marko
##

**Comment by antenore** [comment] 2016-08-03 19:54
@giox069 can you confirm? I cannot reproduce it.

I think we already had a report like this.

**Comment by giox069** [comment] 2016-08-04 07:15
I tested the latest remmina/freerdp with windows 10, but I cannot reproduce.
To save the file at the linux side I did "touch filename.txt", and under windows I can see the correct date/time.
Could you please check the timezone settings of both client and server ? Maybe they are in different timezones. I did not test with PCs in different timezones.

**Comment by markohrastovec** [comment] 2016-08-04 08:16
I have tried it with another Windows computer and the result is the same. However, the error is not what you tested. I have a Linux computer with installed Remmina. Then I connect to Windows host. I have share folder enabled in Remmina and I save a file from Windows to Linux disk via shared folder. In Linux I see the wrong date.

I have tried with Windows, which have different timezone and with one, which has the same timezone. In both cases the date & time in Linux were wrong. I also noticed that the difference between dates is not constant. For instance: I got 24. July dates yesterday and today (and probably some other days too). I noticed that, since this error started to occur, the dates are spanning from July 21st 2011 to July 24th 2011. I don't know when in the future it will jump to July 25th 2011. It looks to me as if the fields in date&time are shifted.

**Comment by giox069** [comment] 2016-08-04 08:48
Unfortunately I can't reproduce it. Remoting of folders is mostly managed by libfreerdp, can you help us doing some test with
```
   xfreerdp /v:_windows_pc_address_ /u:_username_ /d:_domain_ /drive:mydir,/home/giovanni/mydir
```
How did you obtain remmina and freerdp ? Via our PPA or using the compilation instructions ?

**Comment by markohrastovec** [comment] 2016-08-04 13:00
If I use xfreerdp I get the same error. I got Remmina from Remmina PPA.

**Comment by markohrastovec** [comment] 2016-08-06 11:53
I have tried it on another computer with Ubuntu 16.04. At first there was default Remmina installed which comes with Ubuntu. I think it was 1.1.2. With that version it works just fine. Then I added PPA according to instructions from https://github.com/FreeRDP/Remmina/wiki:

sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard

After this update I have the problems with the date & time of the files.

I have upgraded to the latest version because I was hoping the problems I have with clipboard will be resolved. They are not, so it is probably best for me to downgrade.

**Comment by giox069** [comment] 2016-08-06 12:02
@markohrastovec: we are trying to update the freerdp packages included in the remmina-next PPA. They are currently a bit outdated (end of March). But it will take us some day. After the update, you could re-test it.
For the clipboard problems: have you opened another issue ?

**Comment by markohrastovec** [comment] 2016-08-06 12:17
OK. I will test, when nre freerdp will be available. Shall I download newer freerdp myself from some other source?

Regarding clipboard. I have reported it: https://github.com/FreeRDP/Remmina/issues/693

**Comment by giox069** [comment] 2016-08-06 12:23
Mixing our remmina packages with FreeRDP packages from other sources is not a good idea.
As an alternative, if you can, you can remove the packages installed from the PPA and compile both Remmina and FreeRDP from their sources. Instructions are on our wiki: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-16.04

**Comment by giox069** [comment] 2016-08-10 07:42
The PPA has been updated. Could you do ``apt-get update && apt-get upgrade``, reboot and retest ?

**Comment by markohrastovec** [comment] 2016-08-11 06:09
I just got a new computer. I installed ubuntu 16.04 and remmina from scratch and tried it. The problem still resists.

**Comment by hanakemt** [comment] 2017-02-28 15:59
Experienced the same problem today. Installed remmina and xfreerdp today from the ppa. When I use rdesktop instead of xfreerdp date and time are set correctly:

rdesktop _windows_pc_address_:_port_ -u _username_ -p _password_ -g _geometry_ -r disk:_sharename_=_fullsharepath_

Can xfreerdp replaced by rdesktop in remmina? :-)

**Comment by antenore** [comment] 2017-03-01 08:31
@hanakemt we don't use directly the xfreerdp binary, but the FreeRDP library. We are quite against of using mechanisms like gtk_sockets (used to reparent an external window into a gtk window) and redesktop does not provide a library, but a Remmina contributor, @muflone , as developed an rdesktop plugin and you can use it. 

https://github.com/muflone/remmina-plugin-rdesktop

@All Regarding the date and time issue I still didn't be able to reproduce it.

Can you please confirm that using the xfreerdp binary you have the issue? If yes, can you kindly crosspost this to the FreeRDP/FreeRDP team ?

**Comment by antenore** [comment] 2017-03-01 08:37
Update:

With the following setup it works:

remmina - Version 1.2.0-rcgit-18 (git e827e2e)
Windows 2008 R2

**Comment by hanakemt** [comment] 2017-03-01 09:31
@antenore: I can confirm that remmina - Version 1.2.0-rcgit-18 (git rcgit-18) and FreeRDP version 2.0.0~dev (git n/a) work well with Windows 2008, bit they corrupt the date and time with Windows 7 and Windows 10. I'll (re)check also the xfreerdp binary.

**Comment by hanakemt** [comment] 2017-03-01 10:25
@antenore: xfreerdp (version 2.0.0~dev) is responsible for the incorrect date and time handling with Windows 2007 and 2010, I have checked it.
A previous version of xfreerdp (FreeRDP version 1.1.0~beta1 (git n/a); dowloaded from the Ubuntu 16.04 repo) handles correctly the date and time with all the above mentioned Windows variants.

**Comment by hanakemt** [comment] 2017-03-01 11:02
akallabeth wrote on <https://github.com/FreeRDP/FreeRDP/issues/3828> that this error "has been fixed on current master". Hope the remmina ppa will also be refreshed soon. Thank you!

**Comment by markohrastovec** [comment] 2017-04-11 07:28
Hi,

I noticed that the date is OK now. I have Remmina 1.2.0-rcgit-18 (git rcgit-18). About freerdp I believe the 
newer libfreerdp-plugins-standard and/or libfreerdp1 helped.

Here is the list of freerdp libraries installed on my computer.
$ dpkg -l | grep freerdp
ii  libfreerdp-cache1.1:amd64                                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                                1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                                    1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                                     1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-plugins-standard:amd64                           2.0.0~dev201703030839+dfsg-1ubuntu0~git14c236d~xenial amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp-primitives1.1:amd64                              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-utils1.1:amd64                                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1            amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp1:amd64                                           2.0.0~dev201703030839+dfsg-1ubuntu0~git14c236d~xenial amd64        RDP client for Windows Terminal Services (library)

**Comment by markohrastovec** [comment] 2017-04-11 08:13
Well,

after it all worked just perfect, I upgraded the freerdp and remmina and now remmina crashes when I want to open a file from a share folder. I can see the files, but when I try to open it Remmina closes. :(
Where can I get the previous versions?

Here is the list of installed SW:
```
$ dpkg -l | grep freerdp
ii  libfreerdp-cache1.1:amd64                                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                                1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                                    1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                                     1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-plugins-standard:amd64                           2.0.0~dev201703030839+dfsg201704061532-0ubuntu0~git9fd3974+e33fbeb~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp-primitives1.1:amd64                              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-utils1.1:amd64                                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                                       amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp1:amd64                                           2.0.0~dev201703030839+dfsg201704061532-0ubuntu0~git9fd3974+e33fbeb~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services (library)

$ dpkg -l | grep remmina
ii  remmina                                                     1.2.0-rcgit-18-1.0ubuntu3~xenial+rebuild1                                        amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                              1.2.0-rcgit-18-1.0ubuntu3~xenial+rebuild1                                        all          common files for remmina remote desktop client
ii  remmina-plugin-rdp                                          1.2.0-rcgit-18-1.0ubuntu3~xenial+rebuild1                                        amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc                                          1.2.0-rcgit-18-1.0ubuntu3~xenial+rebuild1                                        amd64        VNC plugin for remmina remote desktop client

```

**Comment by markohrastovec** [comment] 2017-04-11 08:21
Hi again

I downgraded libfreerdp-plugins-standard and libfreerdp1. Now it works again. the packages I found on https://bugs.launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next-daily/+sourcepub/7527368/+listing-archive-extra

**Comment by giox069** [comment] 2017-04-11 10:46
@markohrastovec we have another bug currently open for remmina crashing when using remote folders. Please continue reading in issue #1157
I hope it will be fixed ASAP.
Please note that 5 days ago, access to shared folders has been totally rewritten by the FreeRDP team. So, after fixing issue #1157, you should update remmina and recheck if this issue on date/time is solved.

**Comment by giox069** [comment] 2017-04-11 19:03
I have just updated the remmina-next PPA, with the latest libfreerdp that should fix the crash when using remote folders. You can now try to update your distribution.

**Comment by markohrastovec** [comment] 2017-04-12 05:37
It works now. Grazie mille.

**Closed** 2017-09-01 20:09 UTC
