### ISSUE TITLE
sigsegv when running RDP connection on dwm window manager

### ISSUE THREAD

**Issue by Shugyousha** [FreeRDP/Remmina#1504] opened 2018-03-07 15:06 UTC
* Client (OS name and version): 

Archlinux

Linux workarch 4.15.6-1-ARCH #1 SMP PREEMPT Sun Feb 25 12:53:23 UTC 2018 x86_64 GNU/Linux

* Remmina version (remmina --version): 

Remmina - 1.2.0-rcgit-27 (git rcgit-27)

* Desktop environment (GNOME, Unity, KDE, ..): 

dwm

* Connecting to (OS and version): 

Windows Server 2012

* Connecting via (RDP, VNC, ...): 

RDP

When RDPing into our server instances I get a sigsegv. I cannot pinpoint after how long this is happening but it does usually not take more than a few minutes.

The following is a stack trace:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9b0aa28933 in free () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f9ae186f700 (LWP 11915))]
(gdb) bt
#0  0x00007f9b0aa28933 in free () at /usr/lib/libc.so.6
#1  0x000055a238774be0 in remmina_stats_get_wm_name ()
#2  0x000055a238775059 in remmina_stats_get_all ()
#3  0x000055a23877511a in  ()
#4  0x00007f9b0d71826a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f9b0c71808c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f9b0aa9be7f in clone () at /usr/lib/libc.so.6

My current suspicion is that

"gfree_(wmname);" in

https://daguniverse.github.io/RemminaDoc/remmina__stats_8c_source.html#l00423

tries to free 'ret = "\0";' that is returned in

https://daguniverse.github.io/RemminaDoc/remmina__sysinfo_8c_source.html#l00128

because the function cannot get the wmname which results in the sigsegv (but I could be wrong).

Please let me know if you need more info.

**Comment by antenore** [comment] 2018-03-07 17:47
Yes, you are right, I've solved it yesterday evening. See #1499

**Comment by antenore** [comment] 2018-03-07 17:48
Duplicate of #1499

**Comment by Shugyousha** [comment] 2018-03-08 08:08
On Wed, Mar 7, 2018 at 6:48 PM, Antenore Gatta <notifications@github.com> wrote:
> Duplicate of #1499

Ah, sorry for that. I was searching for "sigsegv" so I didn't find the
other issue. Feel free to close.

**Comment by antenore** [comment] 2018-03-08 08:23
No problem at all. I'll close this and reopen the original one

**Closed by antenore** 2018-03-08 08:23 UTC
Labels: duplicate
