### ISSUE TITLE
Crush RDP connect when copy file into clipboard on RDP server and clipboard sync ON

### ISSUE THREAD

**Issue by PostoronnimV** [FreeRDP/Remmina#401] opened 2014-12-09 13:39 UTC
Mint 17 to Windows Server 2008 R2
remmina 1.1.1-1+542+next~ubuntu14.04.1

remmina
Remmina plugin GKEYRING (type=Ключ безопасности) registered.
Remmina plugin RDP (type=Протокол) registered.
Remmina plugin RDPF (type=Файл) registered.
Remmina plugin RDPS (type=Настройка) registered.
Remmina plugin SFTP (type=Протокол) registered.
Remmina plugin SSH (type=Протокол) registered.
[15:29:05:796] [4371:1037096704] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[15:29:05:796] [4371:1037096704] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[15:29:05:796] [4371:1037096704] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[15:29:06:930] [4371:1020405504] [INFO][com.freerdp.channels.rdprd.client] - Loading device service drive (static)
[15:29:06:637] [4371:1020405504] [INFO][com.freerdp.channels.rdprd.client] - registered device #1: Bufer (type=8 id=1)

remmina: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.

**Comment by Hubbitus** [comment] 2015-03-16 22:24
Does it duplicate of https://github.com/FreeRDP/Remmina/issues/280 and https://github.com/FreeRDP/Remmina/issues/411?

**Comment by giox069** [comment] 2015-03-17 08:11
Not really a duplicate, but "pheraps fixed" with missing user answer. Closing it.

**Closed by giox069** 2015-03-17 08:11 UTC

**Comment by PostoronnimV** [comment] 2015-03-17 10:22
Problem solved.
