### ISSUE TITLE
 Ubuntu 18.04 - broken dependencies?

### ISSUE THREAD

**Issue by mahescho** [FreeRDP/Remmina#1659] opened 2018-05-31 07:23 UTC
**We support Remmina 1.2+ versions only.** 
*Do not report bugs related to older Remmina versions!* 
 
## Local System Description

* Client (OS name and version): Ubunut 18.04
* Remmina version ( ```remmina --version``` ): NA
* Installation mean:
  - [ ] Distribution package.
  - [ X] PPA.
  - [ ] Snap.
  - [ ] Flatpak.
  - [ ] Compiled from sources.
  - [ ] Other - detail:
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Plugin:
  - [X] RDP - freerdp version ( ```xfreerdp --version``` ):
  - [ ] VNC
  - [ ] SSH
  - [ ] SFTP
  - [ ] SPICE
  - [ ] EXEC
  - [ ] Other (Please specify):
* Gtk Backend (Wayland, Xorg, ??): Xorg

When I try to install I get:

~# apt install remmina remmina-plugin-rdp remmina-plugin-vnc remmina-plugin-nx 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina-plugin-rdp : Depends: libfreerdp-plugins-standard (>= 2.0.0~git201710051313) but it is not going to be installed or
                               libfreerdp-client2 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by giox069** [comment] 2018-05-31 08:16
This is a duplicate of #1657. Follow it on #1657. Can you please `apt update && apt install remmina remmina-plugin-rdp remmina-plugin-vnc remmina-plugin-nx` now? Please add a comment on issue #1657 after testing, thank you. I think it should be fixed.

**Closed by giox069** 2018-05-31 08:17 UTC
