### ISSUE TITLE
this error message occur. i can not install remmina at tails.

### ISSUE THREAD

**Issue by 678623946782421** [FreeRDP/Remmina#1473] opened 2018-02-13 08:47 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Tails
* Remmina version (remmina --version): 1.2
* Desktop environment (GNOME, Unity, KDE, ..): ?
* Connecting to (OS and version): 
* Connecting via (RDP, VNC, ...): 
* RDP issues only, freerdp version (xfreerdp --version): 
-------------------------------------------------------------------------------------------------------
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 remmina-plugin-gnome : Depends: remmina (= 1.2.0-rcgit.24-2~bpo9+1) but 1.2.0-rcgit.26+dfsg-1~bpo9+1 is to be installed
E: Unable to correct problems, you have held broken packages.

this error message occur. i can not install remmina at tails.

i use this command. 

sudo apt install -t stretch-backports remmina remmina-plugin-rdp remmina-plugin-gnome libfreerdp-plugins-standard proxychains

**Comment by giox069** [comment] 2018-02-13 09:22
Can you try changing remmina-plugin-gnome with remmina-plugin-secret ?
```sudo apt install -t stretch-backports remmina remmina-plugin-rdp remmina-plugin-secret libfreerdp-plugins-standard proxychains```

**Comment by giox069** [comment] 2018-02-19 08:05
Closing because confirmed working on issue #1481. Note: maybe "proxychains" is not needed.

**Closed by giox069** 2018-02-19 08:05 UTC
