### ISSUE TITLE
RD Gateway authentication doesn't work

### ISSUE THREAD

**Issue by jescobar** [FreeRDP/Remmina#511] opened 2015-03-03 15:26 UTC
Hi All,

Thanks for this app, remmina is great!! And I apreciate your effort and work to add support for rd gateway servers.

I think I found an issue, it is seen trying to use the rd gateway server, it works but I can't authenticate against the server, I mean, I set the user name and its password however, remmina indicates that there are authentication problems (Authentication to RDP server server.com failed.
Check username, password and domain.), I verified the user and password and they are good. So I decided to use the freerdp terminal app and I had the same error until I specified user and password for the rd gateway server too (they are the same that for the rdp machine, the command to connect successfully with freerdp terminal app is: 
xfreerdp "/path/to/RDP/$file" /f /gu:$username@DOMAIN /gp:$pass /p:$pass /rfx)

Please let me know if the previous info is understandable, the english language is not my mother language.

Kind regards,
Josue Escobar
##

**Comment by muflone** [comment] 2015-03-04 21:05
Hi

remmina actually supports only the usage of the same username, password and domain for user authentication and gateway.
Different credentials are not yet supported.

What happens if you specify in your xfreerdp connection also the /u:$username@domain argument?
Are you able to connect without using the $file but only specifying the connection server?

**Comment by jescobar** [comment] 2015-03-05 13:49
Hi Muflone

Thanks for your help,

Regarding to this:
remmina actually supports only the usage of the same username, password and domain for user authentication and gateway.
Different credentials are not yet supported.

It is fine for me, I mean that in my case, the RD server and the Remote PC use the same user and password.

Regarding to:
What happens if you specify in your xfreerdp connection also the /u:$username@domain argument?
Are you able to connect without using the $file but only specifying the connection server?

It works fine, using exactly the same user and password for the  "/u", "/gu", "/p" and "/gp" parameters  and also without to specify the $file. My working command looks like: xfreerdp /f /u:user1@DOMAIN  /g:rd.server.com /gu:user1@DOMAIN /gp:password1- /v:pc.into.rdserver /p:password1 /rfx /cert-ignore

When I try to connect using remmina I get this error:

Authentication to RDP server pc.into.rdserver failed.
Check username, password and domain.

So I think that the connection to the RD server is working but the auth against the remote pc isn't.

Again thanks for your help, nice work.

Kind regards
Josue Escobar

**Comment by drew333** [comment] 2015-12-15 23:02
I have also noticed that there isn't support for different credentials for the RD Gateway in Remmina (1.2.0-rcgit.6). I tried using xfreerdp and it works using different credentials for the RD Gateway.

**Comment by antenore** [comment] 2017-06-07 22:21
I mark this as duplicate of #933 because there were a longer discussion over there.
Please join us as we have implemented the feature in a new branch.

**Closed** 2017-06-09 21:05 UTC
Labels: enhancement
