### ISSUE TITLE
Uzbek language support

### ISSUE THREAD

**Issue by ozbek** [FreeRDP/Remmina#560] opened 2015-04-24 06:28 UTC
Hello

I am using 64-bit Ubuntu 14.04 and Remmina is installed from official PPA (currently installed **1.1.1-1+742+next+2015041518**). 
However, I don't see `remmina.mo` at `/usr/share/locale-langpack/uz@cyrillic/LC_MESSAGES/`.

Is this intentional? If yes, is there anything that I may help to include Uzbek locale in official build?

Thanks.
##

**Comment by giox069** [comment] 2015-04-24 14:56
I have not deep knowledge of ubuntu packaging system. I can see that remmina files in ``/usr/share/locale-langpack/`` comes from a package called ``language-pack-gnome-XX-base``, and not from the remmina-next PPA.
**uz@cyrillic** language is a new (renamed) language that you put in remmina 1.2 recently, so it can't be found on ``language-pack-gnome-XX-base``.
I'm asking more info on this to @dktrkranz: any help, explanation and solution is welcome.
Thank you.

**Comment by ozbek** [comment] 2015-04-27 13:11
For reference I renamed the language file to **uz@cyrillic** because my local build is correctly working with that naming convention. 

Although, there are large Uzbek speaking communities in neighboring countries (Afghanistan, Kazakhstan, Kyrgyzstan, etc), Uzbekistan is the only country where Uzbek is officially . So, having the country code is somewhat redundant anyway. 

That said, imho having less specific name for the language pack should not be a problem. 

I might be wrong, but it seems to me that you (@dktrkranz?) have to create translations at https://translations.launchpad.net/~remmina-ppa-team.

**Comment by ozbek** [comment] 2015-05-06 01:16
Also, this [URL](http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu/dists/trusty/main/i18n/) is returning 404. Could that be related?

**Comment by antenore** [comment] 2015-06-25 20:52
@ozbek could you kindly see if someone else can help with the Remmina PPA (maybe you? can you obtain the rights?)

**Comment by uzbadmin** [comment] 2015-06-26 17:11
I hope, I can help to translate into Uzbek language.

**Comment by antenore** [comment] 2015-06-26 21:43
Welcome @uzbadmin , can you see with @ozbek ? 
Rahmat :-)

**Comment by ic3d** [comment] 2017-02-04 11:48
I close this issue because it's not a bug (hope now Remmina is translated in Uzbek language!)

**Closed by ic3d** 2017-02-04 11:48 UTC
Labels: notabug

**Comment by ozbek** [comment] 2017-02-07 01:05
Sorry, I should have reported back sooner. This seems to have been fixed in Ubuntu 16.04 and Remmina Version 1.2.0-rcgit-17 now. Thanks.
