### ISSUE TITLE
Full Screen with multiple monitors always in the same monitor

### ISSUE THREAD

**Issue by xkill** [FreeRDP/Remmina#140] opened 2012-12-27 14:39 UTC
I have two monitors, if I do a full screen connection, it always appear on the main monitor ... but I want to create the fullscreen on the monitor when I have the remmina window.

**Comment by Hubbitus** [comment] 2015-03-16 23:24
Possible duplicate of fixed https://github.com/FreeRDP/Remmina/issues/154

**Comment by ic3d** [comment] 2016-10-03 14:56
@xkill it seems the we've already fix it (see bug #154 ), can you confirm that this bug is now solved? 
Thanks!

**Comment by ic3d** [comment] 2016-10-14 12:03
I close this issue because of (possible) duplicate and it affects an old version of Remmina.

**Closed by ic3d** 2016-10-14 12:03 UTC
Labels: duplicate
