### ISSUE TITLE
Ctrl + c will not stop processes anymore (SSH)

### ISSUE THREAD

**Issue by munsta0** [FreeRDP/Remmina#858] opened 2016-05-09 14:57 UTC
Since my last update, remmina has been eating my ctrl+c, it is now impossible to stop any running process while inside a ssh terminal.

If I start a ping on a server, it'll run forever until I disconnect and reconnect... :(

* Client (OS name and version): Ubuntu 14.04
* Remmina version (remmina --version): remmina - Version 1.2.0-rcgit.11 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..):  Unity
* Connecting to (OS and version): Centos 5
* Connecting via (RDP, VNC, ...):  ssh

**Comment by weberhofer** [comment] 2016-05-09 15:00
Thanks for reporting. This issue is a duplicate of #847.

**Closed by weberhofer** 2016-05-09 15:00 UTC
