### ISSUE TITLE
Can't connect with Windows 2012

### ISSUE THREAD

**Issue by zodrac** [FreeRDP/Remmina#762] opened 2016-02-09 15:41 UTC
Hello. I can't connect with Windows Server 2012 Standard. Remmina says "Unable to connect to RDP Server X.X.X.X". No problem with W8R2, W2003, W7 or W10.

Any idea?

Remmina 1.2.0-rcgit.8 (git n/a)
FreeRDP 1.2.0~git20151218+dfsg-0trusty1 
Distro: Linux Mint 17.3 (rosa)
##

**Comment by antenore** [comment] 2016-02-10 20:05
Any Windows Server 2012 Standard or one specific host?

If it's just one, try to delete the entry of that server inside the file/s 

```
$HOME/.config/freerdp/known_hosts
$HOME/.config/freerdp/known_hosts2
```

**Comment by zodrac** [comment] 2016-02-15 07:58
I only have one windows 2012 standard. I installed remmina and remmina.plugin-rdp, try to connect (with $HOME/.config/freerdp/known_hosts and $HOME/.config/freerdp/known_hosts2 empty) and nothing happens, same message "Unable to connect to RDP Server...".

**Comment by giox069** [comment] 2016-02-15 08:04
@zodrac: exit from remmina, open a terminal window and launch remmina from the command line. Connect to the server and see the output on the terminal. Then copy & paste here the output (you can hide your sensitive data before posting).
You could also try a direct connection with xfreerdp and let us know:
```
xfreerdp /v:_host_name_ /u:user /d:domain
```

**Comment by fabiorauber** [comment] 2017-01-03 15:44
@zodrac, the same thing happened to me, and your solution worked fine. The error message is leaves you clueless though...

**Comment by ic3d** [comment] 2017-01-25 19:22
Hi @fabiorauber what solution are you talking about? Did you try the suggestion from @giox069 ? If so, can you copy&paste the output here? 
Thanks!

**Comment by rcassani** [comment] 2017-05-26 22:02
I had a similar problem, however the cause was not the Host OS, but that the "host key" had changed. I realized that by running:  
`xfreerdp /v:_host_name_ /u:user /d:domain`  
then I updated the `known_hosts` file as the outpu of the previous command suggested. Now it works

The output of the command was:

```
connected to 192.168.200.5:3389
The host key for 192.168.200.5 has changed
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the host key sent by the remote host is
xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx
Please contact your system administrator.
Add correct host key in /home/user/.config/freerdp/known_hosts to get rid of this message.
Host key for 192.168.200.5 has changed and you have requested strict checking.
Host key verification failed.
tls_connect: certificate not trusted, aborting.
Error: protocol security negotiation or connection failure
```

**Comment by balonik** [comment] 2017-06-28 09:18
I have same problem, only with Windows 2012 server. I get "license connection sequence aborted" error.
I have raised https://github.com/FreeRDP/FreeRDP/issues/4023

**Comment by ic3d** [comment] 2017-09-10 19:56
I'm closing this issue because it was not a Remmina one (but FreeRDP).

**Closed** 2017-09-10 19:57 UTC
Labels: invalid
