### ISSUE TITLE
SSH password can't save , terminal auto disconnection

### ISSUE THREAD

**Issue by liumengyu96** [FreeRDP/Remmina#1078] opened 2016-12-29 15:09 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): elementary os loki
* Remmina version (remmina --version): 1.2.0-rcgit-17
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): ubuntu 16.0
* Connecting via (RDP, VNC, ...): SSH
* RDP issues only, freerdp version (xfreerdp --version): 

Can't save SSH password .
When I stop acting in terminal a few seconds ,it will disconnect automatically.

**Comment by antenore** [comment] 2017-04-11 09:58
Are you using the Snap package? If so this is duplicated of #1129

**Comment by antenore** [comment] 2017-06-15 21:51
I've just fixed this and will be soon merged in next. Hopefully in a couple of weeks we will publish a new remmina release.

**Comment by antenore** [comment] 2017-06-15 21:55
Duplicate of #708

**Closed** 2017-06-19 06:59 UTC
