### ISSUE TITLE
Issue with PPA mentioned in Wiki

### ISSUE THREAD

**Issue by Lantizia** [FreeRDP/Remmina#439] opened 2015-01-12 11:45 UTC
Hi, On this page...

https://github.com/FreeRDP/Remmina/wiki

It mentions the remmina-next PPA but also aludes to the existance of a remmina-master PPA too.

If you install Remmina from the remmina-master PPA on trusty (which that PPA has been built for), you'll find when installing remmina-plugin-rdp there are incomplete FreeRDP dependancies which are neither in the PPA, nor Ubuntu, nor in any official FreeRDP PPA I could find built for trusty.

lantizia@ubuntu-test:~$ sudo apt-get install remmina-plugin-rdp
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 remmina-plugin-rdp : Depends: libfreerdp-client1.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                      Depends: libfreerdp-codec1.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                      Depends: libfreerdp-core1.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                      Depends: libfreerdp-gdi1.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                      Depends: libfreerdp-locale1.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                      Recommends: libfreerdp-plugins-standard but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

lantizia@ubuntu-test:~$ sudo apt-get install libfreerdp-plugins-standard
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libfreerdp-plugins-standard : Depends: libfreerdp-common1.1.0 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libfreerdp-utils1.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-crt0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-file0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-handle0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-interlocked0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-synch0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-sysinfo0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-thread0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
                               Depends: libwinpr-utils0.1 (>= 1.1.0~beta1+git20130629) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
##

**Comment by giox069** [comment] 2015-01-12 12:53
We never tested the "master" branch PPA, so I never put it into the wiki. Can you switch to the "next" branch PPA ? It's the most used here, also by other people.

**Comment by Lantizia** [comment] 2015-01-12 14:08
I'd prefer to run only what is considered stable (by either Ubuntu or the author of the software in question) which is why I went for remmina-master as that's 1.1.2 and not 1.2.

How much work would be involved in fixing the PPA for 1.1.2 (master) or is 1.2 not far from being master (I'm guessing your word for stable) anyway? (which yes I've tested, worked very well on 14.04).

**Comment by giox069** [comment] 2015-01-13 08:20
Today I booted an Ubuntu 14.04, updated it, and then
```
sudo apt-add-repository ppa:remmina-ppa-team/remmina-master
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp
```
(I only changed remmina-next to remmina-master from the original wiki instructions)
Remmina 1.1.2 (master) has been installed successfully and I can remote desktop to my servers.
I think you have some problems with the PPA setup, but I'm not a apt/dpkg expert, so I'm unable to help you :cry:

**Comment by Lantizia** [comment] 2015-01-13 08:33
Well this is a VM where I've installed Ubuntu MATE 14.04, installed VMware Tools, done whatever OS updates were available and then taken a snapshot.  I then use that snapshot to test each bit of software in a clean room process.  Are you sure your install of 14.04 hasn't previously had remmina-next installed also? (or perhaps the remmina-next PPA left behind) ?

**Comment by giox069** [comment] 2015-01-13 08:44
I can't say if there was a previous PPA configured. So... I'm downloading Ubuntu MATE 14.04.1 now. 32 or 64 bits ?

**Comment by Lantizia** [comment] 2015-01-13 10:53
64bit

**Comment by giox069** [comment] 2015-01-17 21:31
@Lantizia: I can confirm the problem on Ubuntu Mate 14.04.1 64bits, and I can also confirm that the problem does not occur with Ubuntu Desktop 14.04.1 64bit.
So it seems a Ubuntu-Mate related problem.

I just installed a fresh copy of both Ubuntus and typed the following commands to install remmina-master (stable) PPA:
```
sudo apt-add-repository ppa:remmina-ppa-team/remmina-master
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp
```
I get the same errors of unmet dependencies as @Lantizia pointed out opening this issue.

As a workaround for Ubuntu Mate: change the last line with:
```
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-client1.1 libfreerdp-codec1.1 libfreerdp-core1.1 libfreerdp-gdi1.1 libfreerdp-locale1.1 libfreerdp-plugins-standard libfreerdp-common1.1.0 libfreerdp-utils1.1 libwinpr-crt0.1 libwinpr-file0.1 libwinpr-handle0.1  libwinpr-path0.1 libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1 libwinpr-utils0.1 libfreerdp-primitives1.1  libwinpr-pool0.1 libwinpr-registry0.1 libwinpr-library0.1 libfreerdp-crypto1.1 libwinpr-dsparse0.1 libwinpr-library0.1 libwinpr-registry0.1 libwinpr-rpc0.1 libwinpr-sspi0.1 libfreerdp-cache1.1 libwinpr-input0.1 libwinpr-environment0.1 libwinpr-heap0.1 libwinpr-interlocked0.1
```
and all the needed dependencies will be installed.

@dktrkranz: I'm including you just to make you aware of this problem, but it seems an Ubuntu Mate related problem which affects only the remmina-master PPA and not the remmina-next one.

**Comment by myself42** [comment] 2016-05-24 07:07
@giox069: Thank you!
The same problem is with Linux Mint 17.x MATE.
But the workaround work like a charm here too.

**Comment by ic3d** [comment] 2016-11-17 17:21
Hi @Lantizia @myself42  , do you still get this issue with the latest version of Remmina? Thanks!

**Comment by myself42** [comment] 2016-11-19 08:55
Hi @ic3d , the latest stable Remmina (remmina-master) still have this issue.
The development Remmina (remmina-next) installs just fine.
(Remmina-next have some bugs but I am using it on production machine because there is no PPA build remmina-master for Mint 18 (Xenial))
Anyway thanks a lot for contribution to Remmina!

**Comment by giox069** [comment] 2016-11-19 10:18
The PPA remmina-master is no longer maintained, and no longer mentioned in the wiki. We leave it active because there could be some users using it.
A similar approach for the "master" branch on github: we will only push urgent security patches to it, but we never had one for months.
There are still some bugs both on master and next branch of remmina, but the next branch is the one we use and love more: bugs get fixed in the next branch :)

**Closed by giox069** 2016-11-19 10:18 UTC
Labels: unconfirmed
