### ISSUE TITLE
Remmina recconneting in progress error

### ISSUE THREAD

**Issue by Sunilkoppa27** [FreeRDP/Remmina#1427] opened 2018-01-03 10:23 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Ubuntu 14.04
* Remmina version (remmina --version): 1.2.0
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): windows server 2003
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version):2.0.0 
Hello 
I'm gettinng reconnection in progress attempting 1 to 20 error when i'm connecting windows server 2003 through remmina. please do needfull

**Comment by nanxiongchao** [comment] 2018-01-04 01:00
I also encountered this problem, may be related to your network stability
Method to reproduce the problem:
Unplug and plug in the network port will appear, automatically return to normal
You can now check your network stability

**Comment by Sunilkoppa27** [comment] 2018-01-04 01:05
Hello,
Any solution for this problem because  again and again I'm getting this
problem, unable to work also

On 04-Jan-2018 6:30 am, "nanxiongchao-loongson" <notifications@github.com>
wrote:

I also encountered this problem, may be related to your network stability
Method to reproduce the problem:
Unplug and plug in the network port will appear, automatically return to
normal
You can now check your network stability

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeRDP/Remmina/issues/1427#issuecomment-355171333>,
or mute
the thread

**Comment by ic3d** [comment] 2018-05-11 14:25
Hi @Sunilkoppa27 we're reviewing old open issues. Do you still get this one? Thanks!

**Comment by ic3d** [comment] 2018-05-28 13:03
I'm closing thi issue because it problably effects only an old version of Remmina. Feel free to open it again if needed.

**Closed** 2018-06-08 09:07 UTC
Labels: unconfirmed, wontfix
