### ISSUE TITLE
New grouping mode: All-In-One

### ISSUE THREAD

**Issue by mfuhrmann** [FreeRDP/Remmina#569] opened 2015-05-08 13:55 UTC
I use Ubuntu Gnome (Shell) and work with some virtual workspaces. Remmina can't handle it, to open new connections in already opened windows (which maybe contains some other open sessions; in register view), if the main window and the session window is seperated on different screens. I hope that was unterstandable...

Here an example:
* Remmina main window is opened on screen 1
* connect to RDP session1
* session1 starts on screen1
* move session1 window to screen2
* connect via main window to RDP session2
* session2 doesn't integrate into session1 window but opens a new remmina session window

If you are working with 2-3 physical monitors and additional with some virtual ones, you can get really angry.

**Comment by giox069** [comment] 2015-05-08 14:05
I should investigate a bit deeper on this. In the meanwhile please note the following
1. Please upgrade remmina to the latest devel version 1.2.X. See the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for Ubuntu 15.04.
2. Remmina should group new windows with the same group name by default. There is also a setting into Remmina Preferences -> Appearante->Tab interface which changes the grouping mode. By default is "tab by group". So, in your first post, my question is: are "session1" and "session2" on the same group ?

**Comment by mfuhrmann** [comment] 2015-05-08 15:25
Hey Giovanni,

I did the upgrade. It doesn't matter which grouping mode I use. 

Please take a look. I did a screencast: https://drive.google.com/file/d/0ByBnlB0HZwD0MFMtUmxMUksxQ3M/view?usp=sharing

**Comment by giox069** [comment] 2015-05-08 16:03
It's by design, into remmina_widget_pool_find() function of remmina_widget_pool.c: windows are grouped only if they belong to the same screen (monitor), the same workspace and the same group.
Changing the code seems to be quite simple, but it can result in a confusing user experience: when a user opens a new window, he/she expect to see it in the current screen and workspace.

The first solution I can think of, is to put a global preference like "group new windows in other screens and workspaces". But one day some users will activate it, they will forget it active and he will come here to post another issue because they can't find new windows.

Other solutions ? Asking to @antenore also.

**Comment by mfuhrmann** [comment] 2015-05-08 16:58
Some kind of "lost in translation" I guess.
Alle Verbindungen in Reitern = All connections in registers
It sounded like the option I needed.

A new grouping mode/feature should do the job. The definition should be:
* open all sessions in one window
* regardless on which screen this window is open
* for each session one register

I would like to explain my workflow. Just to bring light into the darkness:

* Remmina main window is placed on my monitor on the left side. Always in the forground
* the Remmina session window is placed on my monitor on the right side but on virtual workplace 3
* I primary work on virtual workplace 1
* so everytime I need a new RDP/VNC session I simply move the mouse to the left monitor and choose a session
* it would be perfect, when this new session opens on workplace 3 as register

Thank you for your friendly ear and have a nice weekend!

**Comment by antenore** [comment] 2015-06-21 22:09
Hi @mfuhrmann 

First of all a bit of background without entering into details.

As a dumb rule, it's not the job of GUI to decide where to place its own windows. A GUI should only respect the standards, so that the window manager can interact with it seamlessly.

One quick tip.

I'm a tiling window manager user and I often deal with these kind of issues because I don't use the mouse, so I need quick quirks to place windows where I want and when I want.

I don't know if you have an easy way to do this with Gnome Shell, but you can start to play with xprop, look an example on my workstation (The main remmina window and then a Remmina connection to localhost using SSH) 

```
xprop | grep -E "^(WM_CLASS|_NET_WM_NAME|WM_NAME)"  
WM_CLASS(STRING) = "remmina", "Remmina"  
WM_NAME(STRING) = "Remmina Remote Desktop Client"   
_NET_WM_NAME(UTF8_STRING) = "Remmina Remote Desktop Client"  

```

```
xprop | grep -E "^(WM_CLASS|_NET_WM_NAME|WM_NAME)"  
WM_CLASS(STRING) = "remmina", "Remmina"  
WM_NAME(STRING) = "ssh LH"  
_NET_WM_NAME(UTF8_STRING) = "ssh LH"  
```

As you can see, you can identify easily each window, then I could move the "SSH LH" to the desktop 4

```
 wmctrl -r "ssh LH" -t4 
```

Surely Gnome shell should have a plugin to do that out of the box, otherwise you can install an utility like [DavilsPie](http://burtonini.com/blog/computers/devilspie/)

> A window-matching utility, inspired by Sawfish's "Matched Windows" option and the lack of the functionality in Metacity. Metacity lacking window matching is not a bad thing. Metacity is a lean window manager, and window matching does not have to be a window manager task. 
> 
> Devil's Pie can be configured to detect windows as they are created, and match the window to a set of rules. If the window matches the rules, it can perform a series of actions on that window. For example, I can make all windows created by X-Chat appear on all workspaces, and the main Gkrellm1 window does not appear in the pager or task list.  

I close the issue, if I misunderstood your issue we will reopen it.

**Closed by antenore** 2015-06-21 22:09 UTC
