### ISSUE TITLE
crash of remmina when terminal bell rings

### ISSUE THREAD

**Issue by michaeltraxler** [FreeRDP/Remmina#163] opened 2013-03-15 10:40 UTC
Finally I can reproduce the crashes I experience since one year I use remmina.

remmina connects to a tighvncserver, all not dependent on the version numbers, also happens with the git version. 

$ xset b
$ perl -e 'foreach (1..10000) {print "\x07"}'

started on the client reliably crashes remmina.

With 
$ xset -b
 everything is fine, even though it still sometimes crashes from time to time, but this is maybe another issue.

I hope this helps to fix this really annoying bug many people experience.

Thanks, 
Michael

**Comment by muflone** [comment] 2015-01-11 16:59
I cannot reproduce this defect using the latest version of Remmina in the branch next.
Please test this defect against the latest available version of Remmina and if the problem persists please reopen this issue. Closing now.

**Comment by michaeltraxler** [comment] 2015-01-11 17:51
Hi,

I don't use remmina anymore. But I tried right now with 
Version     : 1.0.0
Release     : 11.2.1
Architecture: x86_64
Install Date: So 02 Nov 2014 20:09:51 CET
on OpenSuse 13.2
and I still crash remmina with the command given. Here the last two lines printed when started with strace.
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"U\2\300\317u.=\4\3@@\0\0\0\0\0\0\0\0@@@@@\0\0\3\37\205\2\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
write(2, "\n(remmina:13192): Gdk-WARNING **"..., 113
(remmina:13192): Gdk-WARNING **: remmina: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

) = 113
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by muflone** [comment] 2015-01-11 18:07
The version 1.0.0 is really old, you should use a more recent version of Remmina.
If you want please test it please see the wiki page https://github.com/FreeRDP/Remmina/wiki to get instructions how to use a more recent version of Remmina.

**Comment by michaeltraxler** [comment] 2015-01-11 22:24
Hi,

with 
i | remmina                            | package    | 1.1.1-41.2   | x86_64 | (System Packages) 
i | remmina-plugin-vnc                 | package    | 1.1.1-41.2   | x86_64 | (System Packages)

connecting to a tigervnc server (standard SuSE13.2, also 13.1 and older
versions) crashes the client whenever the bell is ringing quite often...

Michael

**Comment by ic3d** [comment] 2016-10-08 15:13
@michaeltraxler Sorry for this _very_ late answer, do you still experience this problem with the latest release of Remmina?

**Comment by michaeltraxler** [comment] 2016-10-08 19:11
yes, remmina still crashes with the bell :-(

**Comment by giox069** [comment] 2016-10-08 19:25
@michaeltraxler Did you test with version 1.2 of remmina ?

**Comment by michaeltraxler** [comment] 2016-10-08 23:06
remmina - Version 1.2.0-rcgit.13 (git n/a)
on 
openSUSE Tumbleweed
Release:        20161003

**Comment by weberhofer** [comment] 2016-10-13 15:51
I can not reproduce it connecting from/to openSUSE Leap 42.1

**Closed by weberhofer** 2016-10-13 15:51 UTC
Labels: bug
