### ISSUE TITLE
Remmina The Digger Edition On Slackware-current

### ISSUE THREAD

**Issue by FBobbioC** [FreeRDP/Remmina#1420] opened 2017-12-28 13:17 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): Slackware-current
* Remmina version (remmina --version): The Digger Edition (v1.2.0-rcgit.25 (2017-12-27))
* Desktop environment (GNOME, Unity, KDE, ..): KDE
* Connecting to (OS and version): CentOS 7
* Connecting via (RDP, VNC, ...): ssh
* RDP issues only, freerdp version (xfreerdp --version): N/A

First and foremost, I want to thank the whole Remmina team for such a great application.  I use it at home for personal use and at work to remote into Windows servers (2003, 2008 R2 and 2012 R2 via RDP in multiple countries in North, Central and South America), CentOS 7 (VNC and ssh), Red Hat (ssh), Slackware (ssh) and even a NetBotz device (ssh).  I am always eager to install a new version.  The "Multi password changer" feature was a great hit.  It saves me a lot of time when it is time to change my Windows password.  I am still working some quirks regarding XDMCP to connect to a Slackware machine, but that is another story.

I noticed yesterday (12-27-2017) that a new version came out, and as such, I downloaded, repackaged and installed it.  RDP works great, like always.  When I try to connect via ssh, the window just closes completely.  I tried running it from a terminal, and all I see is the following:

bash-4.4$ remmina
StatusNotifier/Appindicator support: your desktop does support it, but you did not compile remmina with cmake's -DWITH_APPINDICATOR=on

(remmina:4277): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault

Even the system tray icon closes, which may point to a complete package failure

My system is runs Slackware-current, with kernel 4.9.67 (http://slackware.mirrors.tds.net/pub/slackware/slackware64-current/slackware64/) with Multilib (http://taper.alienbase.nl/mirrors/people/alien/multilib/current/).  What could be causing the issue?  The version before that works great still (v1.2.0-rcgit.24 (2017-10-25)).  I receive the following when opening that same ssh connection in v1.2.0-rcgit.24 (the connection works and this is from when I start the connection to when I finish the connection):

bash-4.4$ remmina
StatusNotifier/Appindicator support: your desktop does support it, but you did not compile remmina with cmake's -DWITH_APPINDICATOR=on

(remmina:4866): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(remmina:4866): Gtk-WARNING **: Allocating size to remmina-cw-viewport 0xdb76d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(remmina:4866): Gtk-WARNING **: Allocating size to GtkScrollbar 0xe38a00 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(remmina:4866): Gtk-WARNING **: Allocating size to remmina-cw-viewport 0xdb76d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(remmina:4866): Gtk-WARNING **: Allocating size to GtkScrollbar 0xe38a00 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(remmina:4866): Gtk-WARNING **: Allocating size to remmina-cw-viewport 0xdb76d0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

I hope I can assist with any testing, in case it is needed.

Regards,

Fernando

**Comment by antenore** [comment] 2017-12-28 13:18
Can you check if you have any old versions of remmina still installed?

**Comment by antenore** [comment] 2017-12-28 13:21
can you also run remmina with gdb
```sh
gdb remmina
run
# as soon as you have the crash
bt
```

**Comment by FBobbioC** [comment] 2017-12-28 13:32
Antenore,

There is only rcgit.25 installed at the time of running Remmina (I always removepkg to uninstall the old version before installing the new version)

Below is the output of gdb remmina:

bash-4.4$ gdb remmina
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-slackware-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from remmina...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/remmina 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffead3f700 (LWP 7982)]
[New Thread 0x7fffea53e700 (LWP 7983)]
StatusNotifier/Appindicator support: your desktop does support it, but you did not compile remmina with cmake's -DWITH_APPINDICATOR=on

(remmina:7978): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
[New Thread 0x7fffd8c58700 (LWP 7984)]
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[New Thread 0x7fffd3a62700 (LWP 7987)]

Thread 5 "remmina" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd3a62700 (LWP 7987)]
0x0000000000439634 in remmina_ssh_init_session ()
(gdb) bt
#0  0x0000000000439634 in remmina_ssh_init_session ()
#1  0x000000000043b140 in  ()
#2  0x00007ffff4703565 in start_thread () at /lib64/libpthread.so.0
#3  0x00007ffff3a4a31f in clone () at /lib64/libc.so.6
(gdb) quit
A debugging session is active.

        Inferior 1 [process 7978] will be killed.

Quit anyway? (y or n) y

In this case, a small black window comes up, but the ssh connection does not complete, nor can I enter a username and password, just a small box.  Would this be an issue with the version of libpthread or libc running on my system?  I can troubleshoot further, with your instructions, once I arrive at work, and send you the output of any command you send me over.

I am also attaching a screenshot of what I see on the screen.  Please let me know if you need me to send it via E-Mail or some other way.

Regards,

Fernando

![remminathedigger12282017](https://user-images.githubusercontent.com/34915215/34412165-23ecc9be-eba1-11e7-9564-7d66e6f5ad1f.png)

**Comment by antenore** [comment] 2017-12-28 13:50
do you have a remmina debug or dbg package? If yes can you install it and run it again under gdb?

I'm building a new version of remmina for the PPA. I don't know if it'll solve the problem, nor if it'll be available immediately.

**Comment by antenore** [comment] 2017-12-28 13:56
The build is done

**Comment by FBobbioC** [comment] 2017-12-28 15:44
Antenore,

I am sorry I am so illiterate in this regards.  Would you have any hint or could you point me to a page to install the remmina debug?  I would gladly do that, but could only find the one for Ubuntu (https://packages.ubuntu.com/xenial/debug/remmina-dbg) and upon decompressing the package, and the files within, I only see some empty folders for usr

Where could I download the new build, if you would like to make it available?

**Comment by antenore** [comment] 2017-12-28 15:54
Looks like this is a bug I've to fix 
#1418 

You can workaround it with

```sh
ssh-keygen -b 4096
```

I'll submit a new version as soon as I'll fix it, sorry

Can you confirm please?

**Comment by FBobbioC** [comment] 2017-12-28 16:10
Antenore,

You, sir, are a genius!  That worked perfectly for all ssh connections (screenshot attached).  Thank you again for your prompt response.

By the way, what package does XDMCP use in Remmina?  I can use Xnest -query thincentre -geometry 1280x1024 :1  and am able to connect.  This I can get around, but would like to use Remmina, since it would centralize all connections in one place.

![remminathedigger12282018-1](https://user-images.githubusercontent.com/34915215/34415893-99d48300-ebb6-11e7-9d74-55bd59c838fa.png)

Regards,

Fernando

**Comment by antenore** [comment] 2017-12-28 16:22
closed via 30df7840a167620319ac43ca1eba62aaecfd0c46

**Comment by antenore** [comment] 2017-12-28 16:22
Thanks :-)
Open a new issue for xdmcp please

**Closed by antenore** 2017-12-28 16:22 UTC

**Comment by antenore** [comment] 2017-12-28 21:41
duplicate of #1418
