### ISSUE TITLE
Unable to connect to Win7 PCs via RDESKTOP with Remmina 1.2.0-rcgit.11

### ISSUE THREAD

**Issue by cjbaghl** [FreeRDP/Remmina#823] opened 2016-04-06 13:15 UTC
I recently upgraded from Remmina 1.2.0-rcgit.8 to 1.2.0-rcgit.11 via pacman (currently running Antergos [Arch Linux]).  After the upgrade, I am no longer able to connect to any of the Win7 PCs via RDESKTOP.  When I downgrade back to 1.2.0-rcgit.8, I can connect.

Can you suggest how to debug this issue?

**Comment by antenore** [comment] 2016-04-06 21:43
In general, we don't support external remmina plugins, but only the ones under remmina-plugins of the source tree, as we are already too busy with what we have.

First of all try to connect directly with rdesktop (it should work), than you can start remmina from the command line and then open the "Debug window" from the help menu. 
Take a look in the console and in the Debug Window for any errors.

I suspect that the remmina external plugin you are using is not been updated with the last modifications we introduced, for example the screenshot functionality. 

You probably just need to apply the same modification as https://github.com/FreeRDP/Remmina/commit/5caf0121e69acd22effbb1a159b3ebeef8e0f0dd#diff-a68146aab23ba03d34b881ace677ff51R2092 here https://github.com/muflone/remmina-plugin-rdesktop/blob/master/remmina-plugin-rdesktop/src/remmina_plugin.c#L402 

May I ask you why don't you use FreeRDP (the RDP implementation we use in Remmina)? It's more than stable now.

**Comment by muflone** [comment] 2016-04-06 22:13
@cjbaghl 
I can confirm the issue is related to the recent changes in the remmina plugin API.
In the next days I'll update the rdesktop plugin for Remmina to fix those changes.

In the future, please open the issue in the [remmina-plugin-rdesktop project](https://github.com/muflone/remmina-plugin-rdesktop/issues).

@antenore thank you for pointing the API change.

**Comment by antenore** [comment] 2016-04-06 22:15
yw.

**Comment by cjbaghl** [comment] 2016-04-07 00:43
All,

Thank you.  I elected to go with FreeRDP and it works well.
The only reason I switched to RDESKTOP was because FreeRDP would 
occasionally freeze and require me to close the window and restart. My 
hope is that FreeRDP is more stable now.

**Comment by giox069** [comment] 2016-04-07 06:50
@muflone: I think the commit is my commit here:
https://github.com/FreeRDP/Remmina/commit/5caf0121e69acd22effbb1a159b3ebeef8e0f0dd
In the next week, I will do some other additions to the plugins API to implement file copy&paste via RDP. We do not have an official metthod to notify of API changes, so I will send you an e-mail when done.

In the meanwhile, I'm closing this issue. As far as I understand, it's solved.

**Comment by antenore** [comment] 2016-04-07 07:13
We can probably just use a standard commit message when we will have an API change in the pull request, or in the main commit.

`Plugin API change: ...`

Sending mails around is nice and polite but it's quite inefficient, because we don't know if someone else is developing his/her own plugin out there.

My 2 cents.

**Closed** 2016-04-07 07:40 UTC
Labels: outofscope

**Comment by muflone** [comment] 2016-04-23 21:21
It took me a bit to find out the real culprit for the issue and I've found it in here: commit antenore@24cdef41d72342b2effc7ebe18395cafbe07087c
More exactly the [line 200](https://github.com/FreeRDP/Remmina/blob/24cdef41d72342b2effc7ebe18395cafbe07087c/remmina/include/remmina/plugin.h#L200) added a new method to the API, resulting in wrong function pointers for outdated plugins.

In the future please consider to add new methods to the end of the RemminaPluginService struct, in order to avoid plugin API breakage.

**Comment by antenore** [comment] 2016-04-23 21:32
Do you want I move it at the end already? We are merging a new PR right now

**Comment by muflone** [comment] 2016-04-23 21:58
Not needed, I'm releasing updates for all my plugins. Thank you.

**Comment by giox069** [comment] 2016-04-23 22:03
@muflone: adding new functions at the end of the structure will not save us when remmina will call... the last added function (which is not present in the plugin). The program control will be passed to a random location.
One immediate but temporary solution should be that current remmina developers will notify you for every ner PR or commit which changes the plugin api. And we can do this, but it can't be done forever (for example when commits are not coming from me or @antenore, or we will leave the project).

We are now trying to understand if there an alternative to this API call mechanism. If you have some ideas, just discuss with us (I think the G+ community will be a better place for this kind of discussion).

**Comment by muflone** [comment] 2016-04-23 22:21
The RemminaPluginService struct allows the plugins to call remmina's functions, not the opposite.
Adding new methods to the end of the struct would save us when the plugins call methods on the remmina side.

I think you meant the RemminaProtocolPlugin which is called from remmina to the plugin side.

I don't mind if sometimes the API change, I would be happy to update the plugins to reflect the changes, so I don't think particular worries are needed.

**Comment by giox069** [comment] 2016-04-23 22:35
Yes, true. I was thinking to the opposite way (RemminaProtocolPlugin).

But we really should think a way to automatically coordinate it.
It's not urgent, but let's think about it (a different data structure ?).

Please consider alsto that adding methods to the end of RemminaPluginService/RemminaProtocolPlugin, will mix up function groups, making the code a bit less readable.
