### ISSUE TITLE
help-all & help-gtk options not recognized

### ISSUE THREAD

**Issue by rsyring** [FreeRDP/Remmina#572] opened 2015-05-12 13:51 UTC
```
(puma)rsyring@loftex:~$ remmina --help | grep help
  -h, --help                  Show help options
  --help-all                  Show all help options
  --help-gtk                  Show GTK+ Options
(puma)rsyring@loftex:~$ remmina --help-all
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.
option parsing failed: Unknown option --help-all
(puma)rsyring@loftex:~$ remmina --help-gtk
Remmina plugin VNC (type=Protocol) registered.
Remmina plugin VNCI (type=Protocol) registered.
Remmina plugin RDP (type=Protocol) registered.
Remmina plugin RDPF (type=File) registered.
Remmina plugin RDPS (type=Preference) registered.
Remmina plugin SFTP (type=Protocol) registered.
Remmina plugin SSH (type=Protocol) registered.
option parsing failed: Unknown option --help-gtk
```
##

**Comment by giox069** [comment] 2015-05-12 14:23
Which version of remmina and under which OS are you running ? The "--help" switch has been fixed a long time ago...

**Comment by rsyring** [comment] 2015-05-12 14:57
Is it possible to get the version of Remmina from the command line?  That's actually what started this whole search for me.

I'm running the latest release (1.2.0-rcgit.3) on Ubuntu 14.04.

**Comment by giox069** [comment] 2015-05-12 16:35
Thank you for reporting. I'm investigating on "--help-gtk".
No, there is currently no way to have the version printed on the command line. I could fix it in the next commit, together with the --help-gtk fix.
``-V  --version`` is ok ?

**Comment by rsyring** [comment] 2015-05-12 16:43
Just my opinion, but `-v --version` seems better if `-v` isn't already used for something.  Thanks.  :)

**Comment by giox069** [comment] 2015-05-12 18:36
I have just pushed a couple of patches to print version and make `--help-gtk` and `--help-all` work.
The PPA should update in 24 hours.

**Comment by rsyring** [comment] 2015-05-18 14:05
I see the version switches now, but nothing is output.  `--help-gtk` works but:

```
$ remmina --help-all
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
```

**Comment by giox069** [comment] 2015-05-18 18:22
It seems that remmina cannot communicate with DBus.
I will try to avoid DBus requests during remmina startup, but I'm unable to reproduce your error.  Which desktop environment/window manager are you using ?

**Comment by rsyring** [comment] 2015-05-18 18:35
I'm using xubuntu 14.04, so xfce 4.10.

**Comment by ic3d** [comment] 2016-12-28 16:28
Hi @rsyring :-) We are reviewing old bugs. Do you still get this issue? Thanks!

**Comment by ic3d** [comment] 2017-01-19 15:23
I'm closing this issue because it seems to affect an old version of Remmina.

**Closed** 2017-01-25 19:36 UTC
Labels: unconfirmed, wontfix
