### ISSUE TITLE
Better user credentials management

### ISSUE THREAD

**Issue by aruljothi** [FreeRDP/Remmina#229] opened 2013-09-27 05:15 UTC
Dear Remmina Team,

 I have been using Remmina for the past few years and it is my default tool for RDP and i like it a lot for it's features and simplicity.

However i feel it lags one feature (explained below) which could make it a better tool.

Currently user credentials are stored for each server we add and In my case we have to change our password every 3 months which means i have to go and update each server (it is around 100+) every time. So it would be great if we implement a separate section to create user credentials and then associate one of the created user credential to each server. This will ensure that we update the credential at only one place when there is a change.

Please let me know if you need any clarifications from my side.

Regards,
Aruljothi.S

**Comment by Hubbitus** [comment] 2015-03-16 22:07
I suggesting close it one as duplicate of #82.

**Comment by giox069** [comment] 2015-03-17 08:09
Yes, closing as duplicate of #82, already marked as "newfeature". Thank you @Hubbitus.

**Closed by giox069** 2015-03-17 08:09 UTC
