### ISSUE TITLE
Remmina resets screen resolution settings in RDP shortcut

### ISSUE THREAD

**Issue by gmalets** [FreeRDP/Remmina#1323] opened 2017-10-19 08:58 UTC
Remmina resets screen resolution settings in RDP shortcut to custom (first in the list of custom available resolutions) created with new version of remmina 1.2.0-rcgit-21 (git rcgit-21)
Shortcuts created by old version are okay until (edit -> save)

* Client (OS name and version):    -   Linux Mint 18.2 / Ubuntu 16.04
* Remmina version (remmina --version):   -   1.2.0-rcgit-21 (git rcgit-21)
* Desktop environment (GNOME, Unity, KDE, ..):    -   Cinnamon, Xfce4
* Connecting to (OS and version):   -   WindowsServer 2012 R2
* Connecting via (RDP, VNC, ...):   -   RDP
* RDP issues only, freerdp version (xfreerdp --version):   -   2.0.0~dev (git n/a)

**Comment by giox069** [comment] 2017-10-19 09:16
Does it happens when you push the "Save" button in the profile editor? If yes, try to push "Save and Connect", it should save the selected resolution. If "Save and Connect" works, please close this issue as duplicate of issue #1307 (fixed and will be released with next release).

**Comment by gmalets** [comment] 2017-10-19 10:04
If push "Save and Connect" I've got full screen and client resolution only for current connect session.
Shortcut resolution still resets to custom (first in the list of available resolutions) even is push "Save and Connect"

**Comment by giox069** [comment] 2017-10-19 10:22
I think you should wait for the next release (1.2.0-rcgit.22) and then retest.
If you want to test unstable version, you can use the "remmina-next-daily" PPA, instead of "remmina-next" PPA.

**Comment by gmalets** [comment] 2017-10-19 11:05
Thank you for advice. I'll wait for it because I don't wanna use unstable version and make more than 70 users of our company to get stress and complain

**Comment by antenore** [comment] 2017-10-20 15:21
A new version of Remmina has just been released. 
Can you please test?

**Comment by scojopa** [comment] 2017-10-20 19:02
Just tested w/ 1.2.0-rcgit-22

Still experiencing the same problem. Everything was fine until 2/3 days ago. Resolution -> Custom (800x600) -> You can change settings via Custom resolution or Use Client Resolution Save, Save as Default.... Nothing Saves.

**Comment by ZamElek** [comment] 2017-10-20 20:41
If I select "Use Client Resolution" it does not save. When I open the profile it always shows Custom...
version 1.2.0-rcgit-22 (git rcgit-22) on Ubuntu 16.04.

**Comment by giox069** [comment] 2017-10-20 20:47
Ok, @antenore now I think I have found it: when changing from "Client Resolution" to "Custom", the status of the radio button is not saved when pressing "Save" or "Save as default".

**Comment by itkostya** [comment] 2017-10-23 14:34
I have the same problem in Ubuntu 17.04, Remmina 1.2.0-rcgit-22 (git rcgit-22)

**Comment by Lonniebiz** [comment] 2017-10-23 16:01
Both me and another user of mine, are still experiencing this on 1.2.0-rcgit-22.

Both "Save" and "Save and Connect" are not able to remembering the "Use Client Resolution" setting.

**Comment by antenore** [comment] 2017-10-23 16:07
We're delivering a new version in a couple of days at worst case. Just to be sure, would you mind building the main branch and validate that it works?

**Comment by antenore** [comment] 2017-10-23 16:32
@Lonniebiz can you please compile Remmina and test it?

**Comment by Lonniebiz** [comment] 2017-10-23 17:01
Uhhh, I'm looking into it:
https://github.com/FreeRDP/Remmina/wiki#for-developers-packagers-and-testers

**Comment by giox069** [comment] 2017-10-23 17:12
if you think compiling it's too complex, you can:

- Use the snap version in the snap "edge" channel, this will preserve your system because snap is totally isolated from the rest (the snap will be unable to see the rest of the system, your remmina config included)
- For ubuntu: use the PPA remmina-next-daily, but remember to switch back to remmina-next PPA after the next release. remmina-next-daily is unstable and may distribute broken versions of remmina.
- please wait the next release. I hope in 10 to 48 hours we will have one (-rcgit.23). But we can't say if your problem is solved or not. This is why we would like you test it before we do an official release :)

**Comment by Lonniebiz** [comment] 2017-10-23 18:38
My user sent this video of the issue:
https://youtu.be/KPAS-oQYf2c

By the way, how can I email you guys privately if I want to discuss something that I don't want to be posted onto the internet? I don't see a feature for doing this under your profiles.

**Comment by antenore** [comment] 2017-10-23 18:42
Look in the Remmina about. You will find all the emails of those who have contributed to Remmina. Also on github in the authors file.

**Comment by antenore** [comment] 2017-10-23 18:43
https://github.com/FreeRDP/Remmina/blob/next/AUTHORS

**Comment by itkostya** [comment] 2017-10-24 06:16
Thank you. It's fixed

On Tue, Oct 24, 2017 at 12:19 AM, Giovanni Panozzo <notifications@github.com

**Comment by gmalets** [comment] 2017-10-24 07:01
It's fixed partial, but standard behavior is broken.
I'll post more info later today

**Comment by sagsm** [comment] 2017-10-24 07:47
The "use client resolution" setting is only getting saved until you connect. Afterwards it automatically resets back to the "custom resolution" setting.

Version is 1.2.0-rcgit-23 from the Ubuntu PPA.

**Comment by giox069** [comment] 2017-10-24 07:51
@sagsm: can you post detailed steps of the buttons your are pressing? Or post a video?
Do you press "Connect" or "Save and Connect" for connecting?

**Comment by sagsm** [comment] 2017-10-24 08:06
- Edit the connection in the remmina main window (right click -> edit)
- Check the "use client resolution" setting
- Press the "save" button
- Doubleclick the connection to connect

Following these steps the "use client resolution" setting is not being saved. The "save as default" and the "save and connect" show the same behaviour.

**Comment by giox069** [comment] 2017-10-24 08:34
Ok, I think the real bug that I can reproduce is

- Configure a profile with "Use client resolution".
- Save and connect, optionally you can close the connection, but it's not needed.
- Reenter the profile editor: now the resolution is no longer "Use client resolution".

**Comment by gmalets** [comment] 2017-10-24 09:01
For me all resolution settings saved fine. 
Also i noticed weird behavior. 

For example:
Scenario 1:
- Create new profile with "Use Client resolution" (expect to get fullscreen mode, right?) --> click "save" or "save and connect"
- If before clicked "save" then click "connect" --> result is: "client resolution mode, fullscreen"
- Do disconnect.

Scenario 2:
- (right click -> edit) --> in edit profile windows we got custom resolution (first in the list of custom available resolutions, in my case 800x600)
- if click "save" or "save and connect" --> we will get Custom resolution saved to profile
   else:
   if click "cancel" --> profile will be unchanged but on next (right click -> edit) we will see custom radio button active.
I have feeling that (right click -> edit) not reading settings from profile but saving right.

 Scenario 3:
- We have properly working profile with 
- We decided to change resolution to 800x600
- (right click -> edit) --> change to custom 800x600 --> "save" or "save and connect" 
- Connect --> Getting (800x600 resolution and fullscreen mode). (Getting previous windows size used with this profile) 
   Why we have got fullscreen mode and 800x600 resolution with huge black borders?
If we chose a custom screen resolution, it is logically clear that we want a windowed mode, rather than a full-screen.
If "Resize the window to fit in remote resolution" (Control_R + 1) key combination we'll get what we want.

Scenario 4 opposite to scenario 3:
- Before we had 800x600 windowed mode.
- We decided to change resolution to full-screen client resolution.
- (right click -> edit) --> change to "Use client resolution" --> "save" or "save and connect" 
- Connect --> Getting (client resolution mode with 800x600 window size and horizontal and vertical scroll bars, since before windows size were 800x600 windowed mode). 
If we chose a client resolution, it is logically clear that we want a full-screen, rather than a windowed mode.
If "Toggle fullscreen mode" (Control_R + F) key combination we'll get what we want.

**Comment by Lonniebiz** [comment] 2017-10-24 11:26
In 23, I can confirm sagsm's comment:
The "use client resolution" setting is only getting saved until you connect. 

To elaborate, if I set it to "use client resolution" and then click the "save" button. It does save it, but the very next time you connect, that saved setting gets overwritten with a custom resolution setting instead (upon clicking the "connect" button).

**Comment by antenore** [comment] 2017-10-24 14:43
I'm testing https://github.com/FreeRDP/Remmina/compare/issue1323_res_settings and it seems to work

**Comment by giox069** [comment] 2017-10-25 20:37
Just released 1.2.0-rcgit.24
Please test it, thank you.

**Comment by Lonniebiz** [comment] 2017-10-25 22:43
Resolution is saving fine for me in 1.2.0-rcgit.24. Thanks!

**Comment by sagsm** [comment] 2017-10-26 06:39
Can confirm that it works in 24. Thx!

**Comment by gmalets** [comment] 2017-10-26 08:17
Does anybody has read [my comment](https://github.com/FreeRDP/Remmina/issues/1323#issuecomment-338923429)?

Nothing changed!!! I still can reproduce scenario 3 and scenario 4

**Comment by giox069** [comment] 2017-10-26 09:16
@gmalets 
About scenario 3: "Why we got fullscreen mode and 800x600 resolution with huge black borders?"
This is how remmina worked for years.
Remote desktop resolution is independent from window size and maximization, because a window may contain more than one connection/remote destkop. If you want to rescale the remote desktop according the window size, there are other methods (scaler button, dynamic resolution update button, or issue #6 which requires to set remote resolution to window size during the connection, but is almost impossible to solve).
About 3 and 4:
"If we chose a custom screen resolution, it is logically clear that we want a windowed mode, rather than a full-screen."
"If we chose a client resolution, it is logically clear that we want a full-screen, rather than a windowed mode."
I can understand. But please note that it's off topic in this issue (settings not saved). You can request these as new feature enhancements by opening a new issue. Unfortunately I don't think we will able to implement it: it conflicts both with saved window settings and the fact that a single window can contain more different profiles. How do we handle it?
I think the problem in the subject as described on the 1st post seems to be fixed because now settings are saved. Can you close this issue and reopen a different new issue if needed?
Thank you

**Comment by gmalets** [comment] 2017-10-26 09:20
You're right, sir. 
Thanks for your work. 
I'm appreciate it.
Have a nice day.

**Closed** 2017-10-26 09:21 UTC
Labels: bug, confirmclose
