### ISSUE TITLE
version 1.2 RDP/VNC "viewport fullscreen mode" causes problems when scaling is enabled

### ISSUE THREAD

**Issue by swamp-fish** [FreeRDP/Remmina#357] opened 2014-10-15 10:59 UTC
When in fullscreen you set it to "viewport fullscreen mode" and scaling is set to  "Fit window size" or close to 100% then you can't handle some upper regions and thus can't close/minimize/move/resize windows or use their menu.

If you scale down to some point(i guess it depends on screen ratio though) then everything starts working.

The bug is actually there since the old version(before 1.1) but in 1.2 the region is bigger and it crashes alot.
##

**Comment by holooloo** [comment] 2015-08-10 13:13
And? Problem has gone?

**Comment by ic3d** [comment] 2016-11-05 17:01
Hi @swamp-fish , do you still get this issue with the latest version of Remmina? Indeed, we only support Remmina 1.2.* branch. Thanks!

**Comment by swamp-fish** [comment] 2016-11-07 06:57
No, it appears that new remmina is ok with this. Though scaling doesn't work in windowed mode, so i am always switching to fullscreen mode after i connect.

**Comment by ic3d** [comment] 2016-11-08 08:19
_"scaling doesn't work in windowed mode"_ 
@giox069 is it an already open issue?

**Comment by giox069** [comment] 2016-11-08 18:40
_"scaling doesn't work in windowed mode"_
I'm unable to reproduce the problem. Scaling is working with VNC and FreeRDP both in windowed and fullscreen mode. I'm using remmina 1.2.0-rcgit.15 under ubuntu 16.04, connected to a linux with vncserver.

**Comment by swamp-fish** [comment] 2016-11-15 07:07
Ok, i checked a bit more.
Scaling doesn't work if toolbar is disabled, it works only if toolbar is enabled.

**Comment by giox069** [comment] 2017-10-05 19:08
@swamp-fish I'm closing this thread because it's too old and refers to the old scaling code which no longer exists in current remmina. If you are still having problem with scaling in the latest released version of remmina (currently 1.2.0-rcgit.20), please open another issue.

**Closed by giox069** 2017-10-05 19:08 UTC
Labels: unconfirmed
