### ISSUE TITLE
Printing PDF via Remmina and share local Printers on Linux Mint dont work

### ISSUE THREAD

**Issue by FFS1** [FreeRDP/Remmina#1158] opened 2017-04-12 10:17 UTC
Hello,

i am using Remmina 1.2 on newest Mint.
We connect via VPN to a Terminalserver 2008 R2 via RDP.
We are able to share the local Printer HP LaserJet Pro M402dn connected to Mint Laptop and are able to successful print via Word, Excel, Outlook.
It is not possible to print PDF documents, the documents wont be printed, the size of the PDF document is increasing in the Terminalserver Printer Queue to an abnormal amount.
We are using Acrobat PDf to open PDF files on the Terminalserver.
If there is a way to give you more Information about this procedure i am happy to help with more Information.

Thanks

**Comment by antenore** [comment] 2017-04-12 10:26
It's probably better to ask support to our friends of FreeRDP.
Try first to reproduce it with xfreerdp.

**Comment by FFS1** [comment] 2017-04-12 10:32
I will try out and made my comment.
Thank you

**Comment by FFS1** [comment] 2017-04-12 11:10
Hello, same problem with FreeRDP

I am using this syntax to connect xfreerdp /f /v:IPADRESS /printer:HP-LaserJet-M402dn

Printer is able to use in the RDP session, but only word, excel, and no PDF printouts

**Comment by giox069** [comment] 2017-04-12 11:19
Please also report to them what freerdp version you are using.
Use
```xfreerdp --version```
Dod you compiled freerdp by yourself or are you using our PPA ?

**Comment by FFS1** [comment] 2017-04-12 11:22
I commented these informations in the new thread.

**Comment by ic3d** [comment] 2017-09-23 17:18
I'm closing this issue because it's a closed FreeRDP one. Feel free to open it again if needed.

**Closed by ic3d** 2017-09-23 17:18 UTC
