### ISSUE TITLE
"Segmentation fault" during start at Xubuntu 17.10

### ISSUE THREAD

**Issue by xgorex** [FreeRDP/Remmina#1419] opened 2017-12-28 10:21 UTC
System details:
* Client (OS name and version): Xubuntu 17.10 
* Remmina version (remmina --version): Remmina - 1.2.0-rcgit-25 (git rcgit-25)
* Desktop environment (GNOME, Unity, KDE, ..): XFCE 4.12
* Connecting to (OS and version):  n/d
* Connecting via (RDP, VNC, ...): n/d
* RDP issues only, freerdp version (xfreerdp --version): n/d 

Problem description / screenlog:
1. just updated remmina from:
`deb http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu artful main`
2. run it:
`>remmina`
3. crash, screenlog:
```
>remmina 
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:10794): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Segmentation fault (core dumped)
```

**Comment by antenore** [comment] 2017-12-28 10:39
Can you remove and purge all the remmina packages and reinstall it?

If it doesn't work can you provide a gdb backtrace?

**Comment by antenore** [comment] 2017-12-28 13:56
I've just submitted a new version. It should appear very soon.

Can you install it?

**Comment by antenore** [comment] 2017-12-28 15:53
Looks like this is a bug I've to fix 
#1418 

You can workaround it with

```sh
ssh-keygen -b 4096
```

I'll submit a new version as soon as I'll fix it, sorry

**Comment by antenore** [comment] 2017-12-28 16:21
closed via 30df7840a167620319ac43ca1eba62aaecfd0c46

**Closed** 2017-12-28 16:21 UTC

**Comment by antenore** [comment] 2017-12-28 21:42
duplicate of #1418

**Comment by xgorex** [comment] 2017-12-29 08:10
Works. Thank you.

**Comment by antenore** [comment] 2017-12-29 08:15
cool, did you upgrade from the last rcgit.26 or did you create the file?
