### ISSUE TITLE
SSH-Tunneled VNC connection randomly hangs

### ISSUE THREAD

**Issue by dktrkranz** [FreeRDP/Remmina#480] opened 2015-02-16 19:41 UTC
[ forwarded from https://bugs.debian.org/698890 ]

While connecting to a remote desktop through a tunneled VNC session, the
session will at some point stop responding to input and/or refuse to disconnect
or close.  Attempting to disconnect results in both the child VNC window
hanging and the parent Remmina session window hanging as well.  Attempting to
close the window via the window manager exhibits the same behavior.

To reproduce:
Create a VNC connection that tunnels via SSH
Connect to a remote desktop that has a 24 or 32 bit color depth
Use the session for a few minutes, then let it idle.  While it does not matter
if the VNC window is minimized or not, generally you can leave it displayed.
Wait for a period of time, say 5 minutes
Attempt to disconnect, or close the window.  At this point, both the child and
parent windows will "hang" and stop responding to input.  Your only effective
option is to kill the parent task.

Expected results:
The window should continue to respond to input, barring interruptions in the IP
connection to the remote session.
If this is a function of the SSH tunnel losing the connection, it should auto-
connect, or use some form of keep-alive while the window is displayed.
##

**Comment by ic3d** [comment] 2016-12-19 10:40
This bug affects an old version of Remmina, and - as [reported in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=698890) - seems to be a duplicate of #77, already closed. Closing it.

**Closed** 2016-12-19 10:40 UTC
