### ISSUE TITLE
remmina: gtk_drag_source_info_destroy(): remmina killed by SIGABRT

### ISSUE THREAD

**Issue by Hubbitus** [FreeRDP/Remmina#529] opened 2015-03-24 20:55 UTC
Please look at one of Fedora user crash: https://bugzilla.redhat.com/show_bug.cgi?id=1190093
It reproducible.

**Comment by giox069** [comment] 2015-03-24 21:48
Seems to be a duplicate of #478.

**Comment by giox069** [comment] 2015-03-25 08:53
Ok, I did some testing and backtrace analyzing. It seems that the problem has been introduced with the latest version of GTK in Fedora:
```
[giovanni@localhost ~]$ rpm -q gtk3-3.1\*
gtk3-3.14.9-1.fc21.x86_64
```
Downgrading it to the previous version 3.14.5-1 and rebooting, seems to make the problem disappear.
```
sudo yum downgrade gtk3 gtk3-devel
```
Can anyone test the downgrade and confirm ?

**Comment by giox069** [comment] 2015-03-25 23:09
I have just pushed a fix for Remmina 1.2. The fix is the branch "nbdnd". Can anyone test it ? After successful testing, I will try to port to Remmina 1.1.X master branch.

**Comment by Hubbitus** [comment] 2015-03-26 17:16
Which version or freerdp it requires?
I have next error compiling it:
```
-- checking for module 'freerdp>=1.2'
--   found freerdp, version 1.2.0-beta1
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find FREERDP (missing: FREERDP_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFREERDP.cmake:38 (find_package_handle_standard_args)
  cmake/FindOptionalPackage.cmake:37 (find_package)
  remmina-plugins/CMakeLists.txt:60 (find_suggested_package)
```

**Comment by giox069** [comment] 2015-03-26 18:09
Remmina 1.2 (the "next" branch and the "nbdnd" branch) requires FreeRDP 1.2, I had some problems when compiling with the "stock" version in fedora 21, so I recompiled FreeRDP from sources following the instructions on the [remmina Wiki](https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20). I'm doing some tests now with the freerdp version provided in fedora 21 and I will let you know later.

**Comment by Hubbitus** [comment] 2015-03-26 18:16
Unfortunately last changes incorporate so-name changes and break API ( ML: http://www.spinics.net/lists/fedora-devel/msg208699.html ). So, untill most of dependencies will be ported it will not be updated. Do you plan port such change?

And before that you had speak downgrading of gtk3 helps. Is it really fedora bug or gtk itself?

**Comment by Hubbitus** [comment] 2015-03-26 18:17
Off course I plan compile it locally and test you fix also.

**Comment by giox069** [comment] 2015-03-26 19:03
Ok, that's true. At the beginning of Freerdp1.2, they changed all ".so" names to simplify up things. So I adapded remmina to use the newer .so libraries. So now I can understand why I can't compile with the stock fc21 freerdp-libs-1.2.0-0.6.beta.1.fc2.
Yes, try to compile FreeRDP locally following my guide on the wiki or whatever you like and let me know.

**Comment by giox069** [comment] 2015-03-26 19:10
About "is a GTK bug" ? No, I don't think so. It's a remmina bug: Remmina used the ["create-window" signal of GtkNotebook](https://developer.gnome.org/gtk3/stable/GtkNotebook.html#GtkNotebook-create-window) in a way totally against its semantics. For some lucky reason it worked for some time. Now a minor change in GTK caused Remmina to stop working. My fix simply makes Remmina behave correctly accordingly the GTK docs specifications.

**Comment by Hubbitus** [comment] 2015-03-27 10:37
Thank you very much Giovanni.
I've cherry-pick your commit and made build with rebased patch: https://admin.fedoraproject.org/updates/remmina-1.1.2-2.fc21
Wait answer from users.

**Comment by giox069** [comment] 2015-03-27 10:40
:+1:

**Closed** 2015-05-08 19:02 UTC
