### ISSUE TITLE
vim doesn't look well in fullscreen mode

### ISSUE THREAD

**Issue by amitbha** [FreeRDP/Remmina#856] opened 2016-05-07 13:24 UTC
![loading full-screen.jpeg...](http://i4.buimg.com/8067da9cda9df5fe.jpg)

Please give us some details about the systems you are using:
* Client: ubuntu-gnome 16.04
* Remmina version: 1.2.0-rcgit.11 
* Desktop environment: gnome-shell 3.18.4
* Connecting to: centos 6.7
* Connecting via: ssh

**Comment by antenore** [comment] 2016-05-10 21:01
before to open vim can you please execute

```sh
echo $TERM
```

![remmina_freebsd-ssh_term](https://cloud.githubusercontent.com/assets/5975/15162418/12077c54-1703-11e6-8fc6-c6b03097f5f2.png)

**Comment by amitbha** [comment] 2016-05-13 12:14
![term](http://i2.buimg.com/c542da24f692b9c2.png)

**Comment by antenore** [comment] 2016-05-13 12:26
Your remote terminal detected only 79 columns

Try this:

```sh
eval $(which resize )
```
If it doesn't work set manually a greater number of columns (ie **stty cols 180** ) and than try again with the resize (if you have it). 

This is not a remmina neither a vte issue, but as I'm trying to improve the ssh support I'll see if there is a way to force rows and columns.

I'll close this issue as it's not a bug.

**Closed** 2016-05-13 12:27 UTC
Labels: notabug, SSH

**Comment by amitbha** [comment] 2016-05-13 16:08
[root@dns1 ~]# which resize
/usr/bin/which: no resize in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)

There was no 'resize' in remote centos and 'stty cols 180' made things worse.
I purge the Remmina 1.2.0 and back to 1.1.2 in ubuntu repository, no problem in the same circumstance. The stty cols detected correctly(140 in fullscreen).
