### ISSUE TITLE
copy / paste and charset

### ISSUE THREAD

**Issue by ComputingFroggy** [FreeRDP/Remmina#1300] opened 2017-10-03 15:47 UTC
* Client (OS name and version): Xubuntu 16.04
* Remmina version (remmina --version): 1.2.0-rcgit-20 
* Desktop environment (GNOME, Unity, KDE, ..): XFCE
* Connecting to (OS and version): Windows
* Connecting via (RDP, VNC, ...): RDP (& VNC as well)
* RDP issues only, freerdp version (xfreerdp --version): xfreerdp is not installed

Whe I copy/paste from my Linux program to my RDP (Windows 2012) session, the accentuated characters are not copyed OK.
Even copying from a Windows RDP session to a Windows VNC session, the accentuated characters are not copyed OK.

I had opened about [another issue](https://github.com/FreeRDP/Remmina/issues/685) that, when asked I thought it was solved ... but it's not so I create a new Issue

**Comment by giox069** [comment] 2017-10-05 19:16
The problems seems to be only on the VNC plugin: I can confirm that non ascii character are not correctly handled in copy & paste operation from the client to the VNC server. I'm using TightVNC server under Windows 10.

**Comment by giox069** [comment] 2017-10-06 06:57
I have just merged a fix. It will be available in the next release of remmina (1.2.0-rcgit.21). If you want to test the fix before the release, you can use our remmina-next-daily PPA (warning: the remmina-next-daily PPA is unstable and may break :)).
Please also note that the VNC clipboard only allows latin-1 (ISO-8859-1 western european) charset characters.

**Closed by giox069** 2017-10-06 06:57 UTC

**Comment by ComputingFroggy** [comment] 2017-10-06 22:05
Thanks, I will wait for the next version, to be released.
