### ISSUE TITLE
Windows 10 BSOD on file copy

### ISSUE THREAD

**Issue by galdwulf** [FreeRDP/Remmina#1019] opened 2016-10-21 14:54 UTC
Hi,

When connecting via RDP from my Ubuntu 16.04 client to Windows 10 via RDP with the "Share Folder" option enabled Windows produces a blue screen of death message (BSOD) and restarts immediately - the issue can be reproduced by doing the following steps:
1. Connect to Win10 with "Share folder" option enabled
2. Choose a file on Win10 that already exists in the mapped folder on Ubuntu client.
3. Copy the file using Windows Explorer
4. Windows crashes and reboots with RDR_FILE_SYSTEM error BSOD

Looking at the Windows crash dump it seems windows invoked BSOD and the stack trace contains a reference to rdbss.sys driver which is a Microsoft digitally signed driver:

c:\windows\system32\drivers\rdbss.sys:
        Verified:       Signed
        Signing date:   18:14 15/09/2016
        Publisher:      Microsoft Windows
        Company:        Microsoft Corporation
        Description:    Redirected Drive Buffering SubSystem Driver
        Product:        Microsoft« Windows« Operating System
        Prod version:   10.0.14393.206
        File version:   10.0.14393.206 (rs1_release.160915-0644)
        MachineType:    64-bit

Further details:
- Client (OS name and version): Ubuntu 16.04.1 LTS
- Remmina version (remmina --version): 1.2.0-rcgit-15 (git n/a)
- Desktop environment (GNOME, Unity, KDE, ..): XFCE
- Connecting to (OS and version): Windows 10 fully patched: Microsoft Windows [Version 10.0.14393]
- Connecting via (RDP, VNC, ...): RDP
- RDP issues only, freerdp version (xfreerdp --version): xfreerdp is not installed

If you have any other questions or need more information please let me know

GW
##

**Comment by ptempier** [comment] 2016-11-08 09:47
confirmed, i get windows 2016  tp crash everytime i want using shared folder

**Comment by Zjemm** [comment] 2016-11-11 08:50
I have the same problem on arch with freerdp and windows10

**Comment by giox069** [comment] 2016-11-11 15:50
@Zjemm do you mean with xfreerdp commandline ?
I'm adding also issue #934 here as related to this problem. They seem both originating from libfreerdp. We should re-test both this issue and #934 after we will switch to a newer freerdp version (we currently are using a pre october 6 update freerdp).

**Comment by Zjemm** [comment] 2016-11-12 08:37
Well im using myrdp witch uses freerdp from the cli

But this issue is the same so it must be in freerdp

**Comment by Zjemm** [comment] 2016-11-12 08:38
Let me know if i can help You collect debug info

**Comment by ptempier** [comment] 2016-11-12 13:29
@galdwulf 
Hello

I am re-reading your description.
"Choose a file on Win10 that **already** exists in the mapped folder on Ubuntu client."

The file can exists anywhere in the mapped folder, or is it more specific that this?
I did not pinpoint the issue very well, as for me, just browsing to some folder makes the server crashes.
I ll try to check if having a folder with the same name on both sides is what triggers the crash.

**Comment by giox069** [comment] 2016-11-12 13:35
I'm unable to reproduce :( when testing, Also please check if you have non ascii characters in path names. Include your windows 10 language and linux language setting too.

**Comment by Zjemm** [comment] 2016-11-13 18:30
no the path is just /dataonhost
language is English on host and vm

it is really clear when using the mapping, the VM will crash.
when no drive is mapped the VM is stable, but then there is nothing to share :)

**Comment by galdwulf** [comment] 2016-11-17 15:39
@ptempier: To give you an example with steps to reproduce:

1. RDP from linux with the following folder structure:
    Remmina is configured to have /home/user/Remminasharedfolder shared
   create a file /home/user/Remminasharedfolder/file.txt (or copy, makes no difference)

Steps: 
1. RDP to Win10
2. Confirm Remmina maps the shared folder under Windows Explorer
3. Create a file on Win10 called "file.txt" using notepad and save it somewhere (eg. your Desktop)
4. Open Windows explorer and copy "file.txt" from your previously saved location to the remmina shared folder (which has the same file already in it)
5. When choosing "paste" Win10 BSODs immediately

Please let me know if you need more info

@ giox069: no non-ASCII chars in the path
Windows language settings: 0409 --> English (United Kingdom)

Language on linux:

LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

Actually I just checked again and the issue seems to be resolved! Now when I'm trying to get to the BSOD stage Windows asks to replace the file...weird! I still have the same Windows build version, the same SubSystem Driver version and the same remmina version installed! Ever since this issue raised however there was a Win10 CU deployed... 

In addition I've got the following freerdp version installed as of now:

ii  libfreerdp1:amd64                                           2.0.0~dev201609090916+dfsg-1ubuntu0~git1855e36~xenial amd64        RDP client for Windows Terminal Services (library)
ii  libfreerdp-plugins-standard:amd64                           2.0.0~dev201609090916+dfsg-1ubuntu0~git1855e36~xenial amd64        RDP client for Windows Terminal Services (plugins)

Unfortunately I can't confirm which version was installed when I raised this issue but I think it's high probability my freerdp version has not changed ever since judging from the filename (and I regularly do apt-get update/upgrade)

...unless I'm losing the plot here has anybody came across this issue in the first place?

**Comment by mabico** [comment] 2016-12-29 08:30
The BSOD problem is reproduceable with the microsoft rdp client. When i connect to my Lenovo Y700 notebook from my home pc (both have Windows 10.0.14393 x64) with enabled automatic network mapping, the BSOD occurs on trying to copy any file. I found only useless solutions around the web. The bugcheck parameters i get are also not listed at microsoft :-/

**Comment by giox069** [comment] 2017-04-11 19:38
Shared RDP folder has been recently rewritten by the libfreerdp team. We have also updated our remmnia-next PPA with the latest FreeRDP.
Please test with the latest FreeRDP and Remmina and let us known.

**Comment by ptempier** [comment] 2017-04-12 18:53
I need to test well; but i didn't noticed a recent crash.
As i remember the issue was supposed to be fixed in the february or mars cumulative update (the one which was delayed/skipped). I don't remember the digging i did to attain this conclusion.

**Comment by ptempier** [comment] 2017-05-22 15:07
no crash so far , so it seems issue is resolved by microsoft update

**Comment by ic3d** [comment] 2017-09-23 16:24
Hi @galdwulf @ptempier @mabico this issue should be fixed, can you confirm? Thanks!

**Comment by ptempier** [comment] 2017-12-10 22:51
confirmed , please close

**Closed** 2018-05-08 13:39 UTC
