### ISSUE TITLE
Keyboard Mapping 

### ISSUE THREAD

**Issue by lestevam** [FreeRDP/Remmina#261] opened 2014-03-27 13:59 UTC
Mapping the "/" key on the numeric keypad is incorrect. Instead of mapping "/" is mapped to ";". 

I'm using RDP and keyboard layout "00000416 - Portuguese (Brazilian ABNT) Version: 0.9.99.1 in Fedora 20.. 

I've tried checking "Use keyboard mapping client", but the same problem occurred. 

Another problem is that when the desktop goes into standby, so when we return to the desktop, the keyboard does not understand that was already active numlock, making a mess on the keyboard handling in both local and remote station.

Tks.
##

**Comment by thecrazy** [comment] 2015-11-10 17:20
Keyboard mapping is also wrong for me, never worked right on any server I connect to.
I suppose this works fine for people using an english layout but I am trying to use Canadian French and its a total mess. Tried to fix the issue from both sides of the connection but nothing works.

**Comment by lestevam** [comment] 2015-11-10 17:27
which version are you using?
If you are using 0.99 you will probably continue to have these problems.
Once I compiled a new version of the git (branch "next") then this issue has been resolved, but others had not so problematic.

**Comment by thecrazy** [comment] 2015-11-10 17:32
I use version 1.2 from their PPA.

The problem is that the information on microsoft's website is misleading.
This website properly describes the issue and what the proper codes are:
http://sashkastechnical.blogspot.ca/2014/07/input-localisation-for-different-systems.html

The logic behind this should be valid for other languages too.

**Comment by thecrazy** [comment] 2015-11-10 18:44
Well.. ok now I feel silly, I just realised the windows servers I am connecting to are accessed using VNC. So it has nothing to do with rdp. Sorry.

**Comment by ic3d** [comment] 2016-11-05 16:52
Hi @lestevam , so can I close this issue? Thanks!

**Comment by lestevam** [comment] 2016-11-05 18:14
Yes!! Thanks!!

**Closed** 2016-11-06 09:17 UTC
Labels: confirmclose
