### ISSUE TITLE
not printing with remiina client 1.2

### ISSUE THREAD

**Issue by anilkumartvm** [FreeRDP/Remmina#707] opened 2015-12-21 19:00 UTC
Iam using windows server 2008 r2-64 bit server - Microsoft Terminal server-RDP - server pc
and client ubuntu 14.04 64bit

while trying to print from ubutu client - not printed. my printer is lbp2900 - with no issues in local printing.
the job is transferd to the client print que. 
iam attached the jobque details for ref.

![screenshot](https://cloud.githubusercontent.com/assets/16389376/11938732/db55eb66-a842-11e5-867b-4c09170c86a1.png)
![screenshot](https://cloud.githubusercontent.com/assets/16389376/11938745/f7855b64-a842-11e5-8b58-cf4b35f9fc1b.png)

i humbly request, please give a solution to print the data.
##

**Comment by giox069** [comment] 2015-12-21 19:10
Which version of remmina are you using ?

**Comment by anilkumartvm** [comment] 2015-12-22 02:22
Remmina 1.1.2
![screenshot2](https://cloud.githubusercontent.com/assets/16389376/11946446/ddcd9a72-a880-11e5-8ece-c79a5fb49546.png)

**Comment by anilkumartvm** [comment] 2015-12-24 16:59
Sir,
Please give a solution

**Comment by giox069** [comment] 2015-12-26 20:21
Have you tried to upgrade remmina to the latest version using the Ubuntu PPA ? Follow the instructions in the remmina wiki  to install the remmina-next PPA for Ubuntu: https://github.com/FreeRDP/Remmina/wiki

**Comment by akallabeth** [comment] 2016-01-17 23:05
This issue could be fixed with #728, remmina was not initializing static freerdp channels correctly.

**Comment by ic3d** [comment] 2017-09-02 16:59
@giox069 @akallabeth do you think we can close this old issue?

**Comment by giox069** [comment] 2017-09-03 10:36
I'm closing this issue. If the the problem is still here, please reopen another issue.

**Closed by giox069** 2017-09-03 10:36 UTC
Labels: unconfirmed
