### ISSUE TITLE
Closing Main Window Kills all Others

### ISSUE THREAD

**Issue by kevingarman** [FreeRDP/Remmina#943] opened 2016-08-03 13:41 UTC
Hi,

First this app is awesome...THANKS!

I'm not sure if this is a bug or not but I find it annoying.  I have the tray icon starting at gnome startup.  The problem is if I open the remmina main window to manage connections and then close the main window, the entire app is kill.  Meaning...the tray icon goes away and if I had open connections they are closed.  Ideally, it seems like opening/closing the main window shouldn't have any affect on the tray icon or open connections.

Thanks,
Kevin

System Info
Arch Linux (Antergos)
remmina - Version 1.2.0-rcgit.14 (git n/a)
Gnome
##

**Comment by antenore** [comment] 2016-08-03 20:11
Thanks for the report. We already have other issues opened about this issue.

We'll discuss it between us and don't be afraid to bump this from time to time.

**Comment by kevingarman** [comment] 2016-09-12 14:45
Looks like you guys may have addressed this in version 1.2.0-rcgit-15?

Now when I have sessions open as well as the main window, and I close the main window, it asks me if I'd like to close my existing sessions.  If I say no, the main window closes and my sessions stay open!

Thanks for the fix guys!

**Comment by antenore** [comment] 2016-09-12 14:55
Probably even before but we didn't release it I guess :-P this is a good news anyway :-)

**Comment by kevingarman** [comment] 2016-09-13 14:59
Well, I guess we're not quite there.  It works as I described if you have more than one session open in a tabbed window.  However, if you only have one session open or if you have more than one session but they are in seperate windows, closing the 'main window' (configuration window) still closes everything without prompting.

**Comment by antenore** [comment] 2016-09-13 15:12
Yes, true, I confirm, sorry for this.
I hope I'll have time to fix this asap.

**Comment by kevingarman** [comment] 2016-09-13 15:27
No problem, I appreciate the work you guys put in on this...it's a very useful app!  I dread getting stuck on windows with their remote desktop client!

**Comment by tfiskgul** [comment] 2017-01-21 11:35
I use Remmina 1.2.0_rc16-r1, and it's a really great remote desktop client =)

I also suffer from this issue, but I usually move the main window to another workspace and leave it open as a workaround.

**Comment by weberhofer** [comment] 2017-01-24 13:59
Duplicate of #785

**Comment by amitbha** [comment] 2017-04-11 08:51
Same problem as one year ago...

**Comment by lundgrenolof** [comment] 2017-04-28 10:23
This also happens to me. The suggested trick by @amitbha did not work for me.
```
remmina - Version 1.2.0-rcgit-18 (git rcgit-18)
Ubuntu 17.04
Gnome 3.24
```

**Comment by giox069** [comment] 2017-04-28 10:41
I think this happens by design.
In older gnome version the tray icon was invisible under the bottom of the screen, so it was impossible to manage remmina after you close the main window. To avoid this, we decided to completely close all windows when the main window is closed.
In newer gnome version, there is a small stripe at the bottom of the screen which shows you the remmina tray icon, so we could rethink the main window closing process now. Do you see the remmina icon at the bottom of the screen?
As an alternative, waiting for a possible modification of the exit code, install this gnome extension: https://extensions.gnome.org/extension/615/appindicator-support/ remmina will then use appindicators, you will have your remmina icon at the top right and remmina will not try to close the main window.

**Comment by giox069** [comment] 2017-09-23 17:52
Duplicate of issue #785, already fixed. Closing.

**Closed by giox069** 2017-09-23 17:52 UTC
Labels: bug, duplicate
