### ISSUE TITLE
Debian 8 copy past problem

### ISSUE THREAD

**Issue by Rob49** [FreeRDP/Remmina#775] opened 2016-02-25 16:35 UTC
Hello,

Sorry for my english.
I used debian 7 since months and Remmina was working fine.
Today i installed Debian 8 and Remmina works good but without the possibility to copy/past between host and sessions.
My Remmina version is 1.1.0 so i tried to update to latest version using the ubuntu guide (https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10)
 but i can't install the "libgnutls-dev" package.

Is there an other easy way to install latest version of Remmina on Debian Jessie ? I'm not an expert but I really need Remmina.

Thank you.
##

**Comment by giox069** [comment] 2016-02-25 21:15
Debian unfortunately does not support a build system similar to the ubuntu PPA. This means that it is currently impossible for us, due to lack of time and expertise, to create .deb packages.

Maybe @dktrkranz can tell us if a Debian maintainer is available to have a fresh/updated remmina version in a way similar to the ubuntu PPA ?

**Comment by Papina** [comment] 2016-02-26 04:12
I just compiled remmina 1.2.0-rcgit.8 and freerdp2 with Debian Jessie, and the copy/paste problem still exists, but it's possible there is a cmake/make flag in freerdp2 or remmina i didnt set? what flags would be needed for copy/paste?

**Comment by giox069** [comment] 2016-02-26 08:02
If you can add more details (destination OS version?) and the exact steps to reproduce the problem, I can try to reproduce here and debut. Please be very detailed, I need to know which application you are using at the server side, because each application generates a different clipboard content type.
Also try to execute remmina in a terminal and see the output when your copy/paste does not work.

**Comment by Thomaskru** [comment] 2016-02-26 14:17
Hello! I have the same Problem. RDP is dying on copy/paste.

Dmesg: 
[87487.731078] remmina[18832]: segfault at 768 ip 00007f94907bb11d sp 00007ffde8788910 error 4 in remmina-plugin-rdp.so[7f94907ad000+12000]

Source: Mint 17.3 fully patched
Remmina 1.2.0 RC git 8
Dest: Windows 7 Prof. 64 bit fully patched

After segfault and initiating an new rdp session the problem was not reproduce able.

**Comment by Papina** [comment] 2016-02-26 20:55
Ok, I've got a working copy/paste system now, so I'll have to try these steps below on my failing system when I get the chance, however I've created a vmware virtual machine from scratch with Debian Jessie with all the commands below used and so far so good, so if anything this will be a baseline reference.

So it's a basic Jessie install from a netinstall ISO, with Cinnamon as the desktop, which happens to be my failing systems configuration.

the target RDP server is 2012 R2

I'll replicate these steps on my other system and see what's different

```

Sudo apt install git build-essential git-core cmake xsltproc libssl-dev libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxdamage-dev libxv-dev libxkbfile-dev libasound2-dev libcups2-dev libxml2 libxml2-dev libxrandr-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libxi-dev libgstreamer-plugins-base1.0-dev libavutil-dev libavcodec-dev

git clone git://github.com/FreeRDP/FreeRDP.git
git clone git://github.com/FreeRDP/Remmina.git --branch next

cd FreeRDP
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_SSE2=ON .
Make
sudo make install

cd ../Remmina
sudo apt-get install libgnutls28-dev libavahi-common-dev libavahi-client-dev libavahi-ui-gtk3-dev libvte-2.90-dev libappindicator3-dev libvncserver-dev libxkbfile-dev libtelepathy-glib-dev libgcrypt20-dev libssh-dev libsecret-1-dev libwebkit2gtk-4.0-dev

cmake -DCMAKE_BUILD_TYPE=Release -DWITH_SSE2=ON .
Make
sudo make install

```

**Comment by Papina** [comment] 2016-02-26 21:10
Brilliant, after rerunning the steps above on my non-working build, it's now working, so I suspect i was missing an installed library that was required.

**Comment by giox069** [comment] 2016-02-26 21:12
:+1:

**Comment by Rob49** [comment] 2016-02-27 09:27
Thank you for your answers, especially Papina! I'll try this monday!

**Comment by Rob49** [comment] 2016-02-29 09:08
Hello,

I did the steps from your post papina and i had a working copy past system too until i restart my pc. I can't connect to my rdp servers now. I don't have any other error message than "impossible to connect to rdp".

Any idea?
Thanks for your help!

**Comment by giox069** [comment] 2016-02-29 09:34
@Rob49: exit from remmina and relaunch it from the command line (inside a terminal window). When you connect, you will see some text messages. Copy and paste the messages here. Thank you.

**Comment by weberhofer** [comment] 2016-03-04 15:47
Sometime when I press Ctrl-C in a windows-text field, I see the following message (always two):
(remmina:19607): Gtk-CRITICAL **: gtk_clipboard_set_text: assertion 'text != NULL' failed
(remmina:19607): Gtk-CRITICAL **: gtk_clipboard_set_text: assertion 'text != NULL' failed

**Comment by giox069** [comment] 2016-03-06 17:49
I have just published a small fix. For ubuntu PPA users: wait until tomorrow before testing. Let me know.

**Comment by weberhofer** [comment] 2016-03-08 14:57
Thank you, @giox069! Your update fixed my problem with the clipboard.

**Comment by Chealer** [comment] 2016-03-09 02:28
Could someone clarify what this ticket is about? I am also unable to copy/paste using Debian 8's Remmina 1.1.0. Is this a Remmina 1.1.0 issue which was solved? Or a Debian packaging bug?

**Comment by mtangoo** [comment] 2016-05-12 09:42
Same Problem here with 1.12 in Ubuntu.
I would like to avoid ppa if there is other work around!

**Comment by randygrolemund-tv** [comment] 2017-06-22 18:48
I'm using Ubuntu desktop 16.04, and using RDP to Windows 2012R2. I have paste issues all through the day. The other thing is, the save password feature does not work. I have to type my password in every time. I use a password manager with long complex passwords..... both of these issues are annoying.

**Comment by antenore** [comment] 2017-06-22 18:58
@mtangoo 1.12 is not supported anymore, sorry.
It's too old. The new versions don't have these issues.

**Comment by antenore** [comment] 2017-06-22 18:58
@randygrolemund-tv which version of Remmina do you have?

**Comment by randygrolemund-tv** [comment] 2017-06-23 17:05
remmina - Version 1.2.0-rcgit-18 (git rcgit-18)

This is the latest version, I can install. I've followed the instructions here:

https://github.com/FreeRDP/Remmina/wiki

Even the edge switch tells me that I am running the latest version. I reinstall just now and the save password feature doesn't work. Paste is still buggy. On the Remmina website, the official download is 1.2..... so how can it not be supported? I'm DevOps, so I am in and out of servers all day.... having to constantly put in a password is slowing me down.... same with having to workout the pasting issue. Thanks for your help BTW. :)

**Comment by antenore** [comment] 2017-06-23 20:00
We still didn't release the last patches, sol the only way to test the new functionalities is to compile it yourself.

In the next days, hopefully, maybe a couple of week, we will release the 1.2.0-rcgit-19 and it'll include all the changes. 
In the meanwhile, regarding the copy&paste issue, can you try to use the "grab all keys" mode and let me know if it works better?

**Comment by ic3d** [comment] 2017-09-13 19:59
Hi @Rob49 @randygrolemund-tv @mtangoo we're reviewing old open issues. Now, we only support Remmina 1.2.* branch. Do you still get this one? Thanks!

**Comment by randygrolemund-tv** [comment] 2017-09-13 20:03
Appreciate the response. I switched to a mac laptop and am using Microsofts client.

**Comment by ic3d** [comment] 2017-09-25 19:43
Thanks @randygrolemund-tv. I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.

**Closed** 2017-09-30 15:53 UTC
Labels: unconfirmed, wontfix
