### ISSUE TITLE
SSH Freeze

### ISSUE THREAD

**Issue by marlonsc** [FreeRDP/Remmina#84] opened 2012-07-15 11:58 UTC
Sometimes when one of my SSH sessions stuck connection, Remmina freezes globally.

**Comment by jtmoree-kahalamgmt-com** [comment] 2015-04-08 18:17
+1111   It seems that remmina is not multi threaded in that one hung window/dialog hangs all of them.  It's very annoying and disruptive to working.  I can't find a bug/change asking for a multi threaded feature or related to dialogs.  Half the freezes are due to a remmina dialog that has popped under other windows.  The dialog does not show in the OS window list so I can't get to it unless I systematically close all other windows on my desktop to find it.  In the meantime no other remmina sessions work.  Can't make new ones.  Screen updates in all current sessions stop working.   In summary, to reduce global freezes:
* need multi threaded remmina
* fix dialogs to NOT be modal (at least not for the whole app)

**Comment by giox069** [comment] 2015-04-08 18:36
Please check to be running remmina 1.2.X , see the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) to upgrade.
In the current version of remmina which runs only on GTK3, I have never seen a remmina dialog popping under other windows. Which window manager are you using ? Can I reproduce ?
Remmina *is* multithreaded: every remote connection is maintained in a separate thread. The main GUI thread is a single thread, as per GTK3 requirement. But I can understand what you mean: it's something like in web browsers, see [here](https://www.chromium.org/developers/design-documents/multi-process-architecture) ? Unfortunately this is would be a very big challenge, which now we cannot afford due to limited development time.

**Comment by jtmoree-kahalamgmt-com** [comment] 2015-04-08 19:45
In fact, any time I use the icon tray to open a remmina dialog (About, Preferences, etc).  they all pop under other windows.  Kubuntu 14.04.1 (KDE) with custom compiled remmina 1.2.0-rcgit.2

$ dpkg -l gtk*
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  gtk2-engines-murrine:amd64  0.98.2-0ubuntu2    amd64              cairo-based gtk+-2.0 theme engine
ii  gtk2-engines-oxygen:amd64   1.4.5-0ubuntu1     amd64              Oxygen widget theme for GTK+-based applications
ii  gtk3-engines-oxygen:amd64   1.3.5-0ubuntu1     amd64              Oxygen widget theme for GTK3-based applications
ii  gtk3-engines-unico:amd64    1.0.3+14.04.201401 amd64              Unico Gtk+ 3 theme engine

**Comment by jtmoree-kahalamgmt-com** [comment] 2015-04-08 20:06
related?  If I use the task tray to open both the preferences and about dialogs then I cannot close the about dialog until the preferences is first closed.

**Comment by giox069** [comment] 2015-04-08 20:38
I added two new issues: #542 and #543 both related to the sytem tray menu. Please add further comments on system tray menus there.

**Comment by giox069** [comment] 2015-04-08 20:42
I'm also closing this issue: remmina has changed both its threading model, ssh library version and its usage a lot in the last 10 months, so if the **SSH freezing problems** is still in remmina, please open a new issue.

**Closed by giox069** 2015-04-08 20:42 UTC

**Comment by jtmoree-kahalamgmt-com** [comment] 2015-05-11 15:48
BTW.  on our network the firewalls drop connections between me and servers after a few minutes of inactivity.  This makes it look like ssh sessions have frozen.   Might be what's happening to you.
