### ISSUE TITLE
No more keyboard when switching out of remmina

### ISSUE THREAD

**Issue by ComputingFroggy** [FreeRDP/Remmina#754] opened 2016-02-01 13:01 UTC
Hi,

Following the advice to get a latest version of remmina because of [another problem](https://github.com/FreeRDP/Remmina/issues/685), I switched to v. 1.2.0-rcgit.8.

My problem is that now when I switch from remmina to any another local program, when I switch back to remmina, the keys (from the keyboard) are not read anymore.
As a workaround, I've found out, that if I launch the chat tool, the keyboard is on again.

I am running Bodhi 3.1 (Ubuntu 14.04 derivatives) and using remmina to connect to remote Windows PCs (via VNC).

Any help about that would be welcome.

Cheer,
L@u
##

**Comment by scottscreations** [comment] 2016-02-01 15:50
This is happening to me as well, latest version.

**Comment by antenore** [comment] 2016-02-01 16:35
@scottscreations VNC as well?

**Comment by scottscreations** [comment] 2016-02-01 17:45
I've been using it today and it appears to be only on 2012 servers...i don't have a VNC server to test with.

**Comment by ComputingFroggy** [comment] 2016-02-01 19:58
For me, it's on all Windows I've come across Windows 7, 8, 10 !

**Comment by antenore** [comment] 2016-02-01 20:37
I cannot reproduce it. I work all the day long with different windows versions, with both RDP and VNC.

Can you pastethe output of each of the following commands (or equivalent of)?

```
ldd `which remmina`
dpkg-query -l 'remmina*'
dpkg-query -l '*freerdp*'
dpkg-query -l '*libvnc*'
```

**Comment by scottscreations** [comment] 2016-02-01 21:10
http://pastebin.com/DjmCie8C  hopefully this helps.

**Comment by antenore** [comment] 2016-02-01 21:32
I suspect you still have an old version of remmina (and its related libraries) laying around.

Can you both execute:

``` 
sudo apt-get --purge remove freerdp-x11 \
 remmina remmina-common remmina-plugin-rdp remmina-plugin-vnc remmina-plugin-gnome \
 remmina-plugin-nx remmina-plugin-telepathy remmina-plugin-xdmcp
```
and than install again remmina and the plugins you need from the PPA.

I really hope that it helps

**Comment by scottscreations** [comment] 2016-02-01 21:41
@antenore it appears to be working, i'll keep testing. I appreciate the support. Love remmina.

**Comment by antenore** [comment] 2016-02-01 21:56
cool! Let me know in some days. Thx!

**Comment by ComputingFroggy** [comment] 2016-02-03 08:01
Even, after removing and reinstalling, I still have the same problem.

I have pasted the results of the commands asked on [pastebin](http://pastebin.com/dSRF0bE8).

Cheers,
L@u

**Comment by antenore** [comment] 2016-02-03 08:10
Did you execute the purge? That's really important.

@giox069 I'm not a Debian/Ubuntu expert, can you advice @ComputingFroggy ? I think he has still something old installed.

**Comment by ComputingFroggy** [comment] 2016-02-03 09:58
Yep, I did run the purge command.

**Comment by ComputingFroggy** [comment] 2016-02-22 12:27
I still have this bug.
A fairly easy workaround is to click on the keyboard icon twice (in the toolbar) ... it's not ideal, but it works !

**Comment by ComputingFroggy** [comment] 2016-08-06 17:03
The bug is related to Bodhi. On a fresh Ubuntu Gnome 16.04, I do not have this bug any more.
Thanks for your help anyway.

**Comment by ic3d** [comment] 2017-09-10 19:53
I'm closing this issue because it's a Bodhi problem.

**Closed** 2017-09-10 19:54 UTC
Labels: invalid
