### ISSUE TITLE
credentials folder issue?

### ISSUE THREAD

**Issue by Killertjuh** [FreeRDP/Remmina#770] opened 2016-02-22 07:32 UTC
Hi Therem

I`m working with remmina for a few years and i`ll love it. But i miss this feature. When i look into the history i found these feature request #82 #229. But i dont know how i can use this. 

I`m using Remmina 1.1.2-3 (debian stretch)

Yes i can create groups and everything but i cannot find any feature to story the credentials within the folder/group.

**Comment by antenore** [comment] 2016-08-24 23:57
Duplicate of #82

**Closed by antenore** 2016-08-24 23:57 UTC
Labels: duplicate
