### ISSUE TITLE
Connection window disappears when minimized 

### ISSUE THREAD

**Issue by JaggedJax** [FreeRDP/Remmina#155] opened 2013-02-25 22:10 UTC
Using Cinnamon window manager (on Linux Mint), if the setting "Minimize windows to tray" is enabled and a connection window is minimized, the window disappears with no way to bring it back.

Starting a new session, loads the new connection, but the main window still stays hidden.

**Comment by Hubbitus** [comment] 2015-03-16 23:17
Possibly duplicate of https://github.com/FreeRDP/Remmina/issues/148.

**Comment by ic3d** [comment] 2016-10-07 12:06
@JaggedJax What versions of freerdp and remmina are you use? Is it actual now?

**Comment by ic3d** [comment] 2016-10-23 16:18
I close this issue because it was opened a long ago and probably it's a duplicate of a already-closed bug.

**Closed by ic3d** 2016-10-23 16:18 UTC
