### ISSUE TITLE
font smoothing - some fonts are not smoothed

### ISSUE THREAD

**Issue by aleqx** [FreeRDP/Remmina#382] opened 2014-11-21 05:11 UTC
I used the testing package from here which was built against freerdp 20141002 at the time of this writing:

https://launchpad.net/~remmina/+archive/ubuntu/testing

Im connecting to a Win8.1 x64 Pro. Works fine except that some fonts are smoothed, whereas others are not ... first time I see this. The remmina conf has rdp_quality_9=80 which is supposed to smooth fonts. I tried using 16bpp, 24bpp, 32bpp and also remotefx 32bpp. None of the conf combinations helped.

**EDIT**: In fact, it does smooth all fonts briefly when connected, for a fraction of a second, and then some fonts get un-smoothed while others remain smoothed.

The supplied freerdp with Ubuntu Trusty, which is freerdp-1.0.2-2ubuntu1, does not have this problem (all fonts are smoothed permanently) but it has the screen positioning bug #69, which I was trying to workaround.

`rdesktop` does not have this problem either (all fonts are smoothed when using `-x 0x80`)

Any clues?
##

**Comment by gnumdk** [comment] 2015-09-08 10:44
Same here, seems to be broken...

**Comment by giox069** [comment] 2015-09-08 19:12
From the main remmina window, edit your connection profile. On the "Advanced tab" choose Quality: Best. This should enable font smoothing.
You can use the Quality Profile editor from the main window to enable font smoothing also for other quality profiles: Edit->Preferences, RDP, select a Quality Level to edit and enable font smoothing for that quality profile.

Does it work ?

**Comment by gnumdk** [comment] 2015-09-09 04:45
No, it does not work.
Using xfreerdp +fonts from cmdline works.

Archlinux

**Comment by giox069** [comment] 2015-09-09 06:57
Are you trying with the latest 1.2.0-rcgit3 version of remmina and freerdp 1.2 ?

**Comment by gnumdk** [comment] 2015-09-14 07:13
Remmina 1.2
freerdp 1:1.2.0_beta1+android9-1

**Comment by giox069** [comment] 2015-09-14 07:20
I need the full version of remmina. Go on help menu and choose about. And check that it's the latest one (1.2.0-rcgit3).
According your package naming, it seems that you are running the old version of remmina included in Arch Linux (I may be wrong here). If you are running the stock version of remmina included by Arch, please consider the fact that we cannot patch it: because distribution specific packages are out of our control.

**Comment by dannysuls** [comment] 2016-08-24 12:26
I'm having the exact same issue as the OP described: even though font smoothing is on (checked in quality settings), some fonts are smoothed and some aren't.

With rdesktop, all fonts are properly smoothed (using -x 0x80).

Remmina version: 1.2.0-rcgit-15
Ubuntu 14.04 LTS amd64

**Comment by antenore** [comment] 2016-08-24 13:07
By me the font smoothing is correctly implemented in Remmina. So it's more a GTK issue, in fact on my main PC everything works correctly, but I've put in place some different hacks to have some good fonts anti aliasing.

Unlucky I don't remember exactly what I have done. 

With xfreerdp works out of the box, because you have anti aliasing correctly set in X, and  because the anti aliasing in X works :-)

In GTK the font anti aliasing implementation, it's quite poor, also, as far as I understood, for performance issues (aliasing is bad for performance). 

So I don't know yet how we can help you guys :-\  , but we will keep searching.

Can you kindly research a bit around the gtk and font configurations (hacks, tips, workaround) to have a perfect anti aliasing and see if it helps (GTK3 and GTK2)?

To be confirmed, but by me this is not a remmina bug and to work around the GTK implementation we would risk to make Remmina unstable, so it will probably be a "won't fix this". Please help us

**Comment by ic3d** [comment] 2016-11-05 17:11
Hi @aleqx @gnumdk do you still get this issue with the latest version of Remmina? Thanks!

**Comment by gnumdk** [comment] 2016-11-05 20:04
Fixed for me

**Comment by ic3d** [comment] 2016-11-15 07:34
Hi @gnumdk thanks for your answer. I'll wait some more day, just to wait for some other feedback, and then I'll close this issue.

**Closed** 2016-11-17 17:00 UTC
Labels: unconfirmed
