### ISSUE TITLE
SFTP identity File

### ISSUE THREAD

**Issue by ColbyC** [FreeRDP/Remmina#1301] opened 2017-10-03 16:30 UTC
Please give us some details about the systems you are using:
* Client (OS name and version):  Ubuntu 17.04 64-bit

* Remmina version (remmina --version): 

StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
Remmina - Version 1.2.0-rcgit-20 (git rcgit-20)

* Desktop environment (GNOME, Unity, KDE, ..): GNOME

* Connecting to (OS and version):  Debian Wheezy

* Connecting via (RDP, VNC, ...): SFTP

While connecting to a server using an Identity file for authentication, Remmina Crashes. This only happens when using SFTP.

**Comment by antenore** [comment] 2017-10-03 18:33
As a temporary workaround, does it crash with auto?

**Comment by ColbyC** [comment] 2017-10-03 19:16
Auto meaning? It does not crash and works with password authentication.

**Comment by antenore** [comment] 2017-10-03 19:31
Publick key (auto)

![image](https://user-images.githubusercontent.com/5975/31144829-226bdc2c-a882-11e7-8d1c-7fd992ec706a.png)

**Comment by antenore** [comment] 2017-10-03 19:47
I cannot reproduce it, but I'm testing the branch "next", that will be released in few weeks. It could be that the problem has been already fixed.
It'd be great if you could test as well the branch 'next', so that we can eventually fix this problem if it still persists. 
In our wiki there is everything is needed to compile it.

**Comment by ColbyC** [comment] 2017-10-03 20:11
It does not work, It Crashes

**Comment by giox069** [comment] 2017-10-06 17:48
@ColbyC if you are using the "remmina-next" PPA, you can try to switch to the "remmina-next-daily" PPA to get updated remmin (but in "testing" quality).

**Comment by antenore** [comment] 2017-12-01 22:41
This was broken, sorry. I've just fixed this and I'm merging into next. It'll be available ASAP in the next release

**Closed** 2017-12-01 22:54 UTC
Labels: backlog
