### ISSUE TITLE
Pasting something that was copied in another VM that has since been closed causes crash

### ISSUE THREAD

**Issue by zimmertr** [FreeRDP/Remmina#1484] opened 2018-02-19 23:12 UTC
* Client (OS name and version): Arch Linux, fully updated
* Remmina version (remmina --version): 1.2.0-rcgit-26
* Desktop environment (GNOME, Unity, KDE, ..): i3wm
* Connecting to (OS and version): Windows Server 2012 R2
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 2.0.0-rc1 (n/a)

When you copy a string in an RDP session, close RDP session, and paste string in another VM, Remmina crashes. Should instead fail (or succeed) to copy and not crash.

**Comment by antenore** [comment] 2018-02-19 23:23
Are you able to reproduce it with xfreerdp?

Would you mind providing a backtrace (with gdb for example, run bt after the crash) of when this happens please?

**Comment by zimmertr** [comment] 2018-02-20 18:33
I spawned two xfreerdp sessions from my terminal, copied text from one to the other successfully, closed the source VM, and attempted to copy again. Rather than crashing xfreerdp just failed to paste anything and acted like the clipboard was null. 

I replicated the issue posted above in Remmina and generated a stacktrace for you using `coredumpctl`. Let me know if this isn't sufficient and I will do my best to help with troubleshooting.

https://gist.githubusercontent.com/zimmertr/68a1693b035f323ccd756db7ed627d88/raw/ddb90e6ed38a1e608f4350cbbddb2e4bb4125fbd/gistfile1.txt

**Comment by giox069** [comment] 2018-02-20 19:34
Confirmed. I'm able to reproduce it. Thank you for the backtrace.

**Comment by giox069** [comment] 2018-02-20 21:43
Fix committed in branch "issue1484". If anyone can test it, he/she is welcome :)
Tomorrow I will merge on next.

**Comment by giox069** [comment] 2018-02-21 09:18
Fix merged in "next". Will be available with next release 1.2.0-rcgit28. I'm closing this issue.

**Closed by giox069** 2018-02-21 09:18 UTC
Labels: bug

**Comment by zimmertr** [comment] 2018-02-21 16:01
Sorry @giox069 I meant to give this a test when I got home from work. Slipped my mind though. :(

That was a really fast turnaround! I really appreciate your work. Remmina is an amazing piece of software that I have recommended to many.

**Comment by giox069** [comment] 2018-02-21 16:42
No problems @zimmertr. I was in a hurry because Debian/Ubuntu maintainer is preparing official distro packages for Ubuntu 18.04, and this fix is quite important for remmina stability. So I merged it.
