### ISSUE TITLE
please add support multi-hop ssh tunnels / read .ssh/config

### ISSUE THREAD

**Issue by cloph** [FreeRDP/Remmina#302] opened 2014-08-25 12:13 UTC
To tunnel to a host that has no external IP, I need to use multi-hop ssh-tunnel.
Currently there is no way to do that with remmina alone, so I have to manually create appropriate tunnel on the commandline.

I cannot use ssh's proxy-commands as a shortcut either, since .ssh/config isn't evaluated.

So please allow to enter manual ssh tunnel commands like for example

ssh -L 3389:192.168.1.152:3389 user@exposed.host

to tunnel traffic through the expost host to the actual target machine in the exposed host's internal network.

**Comment by Hubbitus** [comment] 2015-03-16 22:39
I think it is duplicate of https://github.com/FreeRDP/Remmina/issues/235 and https://github.com/FreeRDP/Remmina/issues/223

**Comment by cloph** [comment] 2015-03-23 18:13
it is similar to the "doesn't respect ssh-config", more specially this one is a subset of what you could configure in a ssh config (so if remmina supports all options from .ssh/config, then this one is solved), but it is not the same as "not able to use multiple ssh-tunneled rdp connections". This one is about using a series of intermediate hosts to the target:
local → host A → hostB

while the other one is
local → host A
local → host B
where remmina fails because it stores the certificate fingerpint with the local endpoint as key, not with the target (so when you want to connect to host B after having used host A, you need to remove the entry from ~/.freerdp/known_hosts)

**Comment by giox069** [comment] 2015-03-23 18:19
Currently multihop tunnel is not supported by remmina. Only one hop tunnel is suppoted.
Maybe the feature request in issue #520 (add the ability to run external command) will help in the future.

**Comment by giox069** [comment] 2015-03-23 19:11
Maybe my previous answer is not correct. If you mean
local -> hostA(ssh) -> hostB(rdpserver)
then remmina may work, and has been recently fixed to support the correct certificates. Please use Remmina 1.2. See the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) for info on getting Remmina 1.2.

**Comment by antenore** [comment] 2015-06-21 01:07
look at #235 , I'm not sure it'll work because libssh does not support all the ssh options.

Duplicated of #235

**Comment by antenore** [comment] 2015-10-14 06:17
Closed by #235 and by #562

**Closed by antenore** 2015-10-14 06:17 UTC
Labels: newfeature, SSH
