### ISSUE TITLE
Bug: unable to connect through gateway since 1.2.0-rcgit.8

### ISSUE THREAD

**Issue by montechristos** [FreeRDP/Remmina#722] opened 2016-01-12 12:58 UTC
I have been using Remmina for some time now on Mint.
Yesterday I updated to the latest version 1.2.0-rcgit.8
Since, I am unable to connect through the gateway. The application seems to ignore it.

Thanks in advance
##

**Comment by cmayoros** [comment] 2016-01-13 00:54
I've got the same issue. My company has the option to work remotely, I did so all day today. After work, I installed updates on my system, which included 1.2.0-rcgit.8 as well, and now when trying to connect, it fails every time. It just gives me and error that says "Unable to connect to RDP server ..." Just glad I didn't install updates until after work. BTW, I checked in a Windows VM, and was able to connect, so it's not my company having issues.

**Comment by giox069** [comment] 2016-01-13 06:12
We don not currently have a RDP gateway to test, we will try to find one as soon as possible. Could someone please test the connection using the commandline xfreerdp ? (I think the commandline option for xfreerdp is "/g:...").

**Comment by karmacoma92** [comment] 2016-01-13 06:22
Hi there

something similar happening to me. As far as I can see in the logs it was working properly with 

remmina-plugin-rdp:amd64 1.1.2-ppa1+809+next+201512191532~ubuntu14.04.1

but stopped working with 

remmina-plugin-rdp:amd64 1.1.2-ppa1+809+next+201512191532~ubuntu14.04.1

when I run the command you mentioned I get 

reeopp@elxc5q9q12-za:~$ xfreerdp /g:
xfreerdp: error while loading shared libraries: libxfreerdp-client.so.2.0: cannot open shared object file: No such file or directory

not sure if hat helps......

Many thanks

**Comment by giox069** [comment] 2016-01-13 06:39
@karmacoma92: your xfreerdp is unable to load an important library and maybe remmina is having the same problem. You should see the same error by executing remmina from the commandline. Please do the following:
1. Update your system in the usual way
`sudo apt-get update && sudo apt-get dist-upgrade`
We had some problem with the PPA yesterday, and you can be one of the people that downloaded a wrong package during a specific time window. Updating your syste again will fix it.
2. retry to execute `xfreerdp /g:name_of_uour_server ...` and post the output here. If the error changes or disappear, retry also with remmina.
3. post the output of `dpkg --list "freerdp*" here, and pos also the output of `dpkg --list "remmina*"`
Thank you.

**Comment by karmacoma92** [comment] 2016-01-13 06:50
Hi giox069

1.- No new package updated/upgraded after running the common updating commands :-(
2.- Exactly same error when executing the xfreerdp command
3.- This is the output of the command
dpkg --list "freerdp*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-==============================================================================================
un  freerdp                                      <none>                      <none>                      (no description available)
ii  freerdp-sipe                                 1.1.0~git20150628.1.084b365 amd64                       RDP client for Windows Terminal Services (X11 client)
ii  freerdp-x11                                  1.2.0~git20151218+dfsg-0tru amd64                       RDP client for Windows Terminal Services

dpkg --list "remmina*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-==============================================================================================
ii  remmina                                      1.1.2-ppa1+819+next+2016011 amd64                       remote desktop client for GNOME desktop environment
ii  remmina-common                               1.1.2-ppa1+819+next+2016011 all                         common files for remmina remote desktop client
ii  remmina-dbg                                  1.1.2-ppa1+819+next+2016011 amd64                       remote desktop client - debug pakcage
un  remmina-gnome                                <none>                      <none>                      (no description available)
un  remmina-plugin-data                          <none>                      <none>                      (no description available)
ii  remmina-plugin-gnome                         1.1.2-ppa1+819+next+2016011 amd64                       GNOME plugin for remmina remote desktop client
ii  remmina-plugin-nx                            1.1.2-ppa1+819+next+2016011 amd64                       NX plugin for remmina remote desktop client
ii  remmina-plugin-rdp                           1.1.2-ppa1+819+next+2016011 amd64                       RDP plugin for remmina remote desktop client
ii  remmina-plugin-telepathy                     1.1.2-ppa1+819+next+2016011 amd64                       Telepathy plugin for remmina remote desktop client
ii  remmina-plugin-vnc                           1.1.2-ppa1+819+next+2016011 amd64                       VNC plugin for remmina remote desktop client
ii  remmina-plugin-xdmcp                         1.1.2-ppa1+819+next+2016011 amd64                       XDMCP plugin for remmina remote desktop client
un  remmina-xfce                                 <none>                      <none>                      (no description available)


Just in case it helps I noticed freerdp was also updated at the same time from a February version to a new one from December:

2016-01-12 06:39:50 upgrade libfreerdp-plugins-standard:amd64 1.2.0~git20150207+dfsg-0trusty2 1.2.0~git20151218+dfsg-0trusty1

Not sure if you can read this very well, I can send you a log or mail if needed

thanks a lot!

**Comment by giox069** [comment] 2016-01-13 07:15
Yes, correct. We recently upgraded freerdp from the February version (1.2) to a December version (2.0) in the PPA.
Can you also post the output of `dpkg --list "*freerdp*"` ? I forgot an asterisk.
Do you really need the freerdp-sipe package ? If you can remove it, then remove it.
After you get the full "*freerdp*" list of packages, you should try to remove and reinstall it with something similar:
```
sudo apt-get --purge remove libfreerdp1 libfreerdp-plugins-standard remmina-plugin-rdpsudo
sudo apt-get install libfreerdp1 libfreerdp-plugins-standard remmina-plugin-rdp
```

**Comment by karmacoma92** [comment] 2016-01-13 07:31
Hi Giovanni
Here you have the output:
```
dpkg --list "*freerdp*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                         Version                     Architecture                Description
+++-============================================-===========================-===========================-==============================================================================================
un  freerdp                                      <none>                      <none>                      (no description available)
ii  freerdp-sipe                                 1.1.0~git20150628.1.084b365 amd64                       RDP client for Windows Terminal Services (X11 client)
ii  freerdp-x11                                  1.2.0~git20151218+dfsg-0tru amd64                       RDP client for Windows Terminal Services
un  libfreerdp-cache1.1                          <none>                      <none>                      (no description available)
ii  libfreerdp-client1.1:amd64                   1.1.0~git20150628.1.084b365 amd64                       Free Remote Desktop Protocol library (client library)
un  libfreerdp-codec1.1                          <none>                      <none>                      (no description available)
un  libfreerdp-common1.1.0                       <none>                      <none>                      (no description available)
un  libfreerdp-core1.1                           <none>                      <none>                      (no description available)
un  libfreerdp-crypto1.1                         <none>                      <none>                      (no description available)
un  libfreerdp-gdi1.1                            <none>                      <none>                      (no description available)
un  libfreerdp-locale1.1                         <none>                      <none>                      (no description available)
ii  libfreerdp-plugins-standard:amd64            1.2.0~git20151218+dfsg-0tru amd64                       RDP client for Windows Terminal Services (plugins)
un  libfreerdp-primitives1.1                     <none>                      <none>                      (no description available)
un  libfreerdp-rail1.1                           <none>                      <none>                      (no description available)
un  libfreerdp-utils1.1                          <none>                      <none>                      (no description available)
ii  libfreerdp1                                  2.0                         all                         Dummy package to accomodate libfreerdp1.1
ii  libfreerdp1.1:amd64                          1.1.0~git20150628.1.084b365 amd64                       Free Remote Desktop Protocol library (core library)
ii  libxfreerdp-client1.1:amd64                  1.1.0~git20150628.1.084b365 amd64                       Free Remote Desktop Protocol library (xfreerdp-client library)
un  lightdm-remote-session-freerdp               <none>                      <none>                      (no description available)
```
I'm using freerdp-sipe for pidgin sip so unfortunately I cannot uninstall it...

it is in fact leading to problems since there seems to be a conflict when trying to re-install the libfreerdp

```
Preparing to unpack .../libfreerdp1_1.2.0~git20151218+dfsg-0trusty1_amd64.deb ...
Unpacking libfreerdp1:amd64 (1.2.0~git20151218+dfsg-0trusty1) ...
dpkg: error processing archive /var/cache/apt/archives/libfreerdp1_1.2.0~git20151218+dfsg-0trusty1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libwinpr.so.1.1.0', which is also in package libwinpr0.1:amd64 1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu14.04.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/libfreerdp1_1.2.0~git20151218+dfsg-0trusty1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Not so sure what to do, maybe uninstall sipe, reinstall libfreerdp and then  reinstall sipe?

**Comment by giox069** [comment] 2016-01-13 07:37
Try to understand if sipe can live without the freerdp plugin: try to uninstall all listed *freeerdp* packages and see if sipe complains or not.
Then yes, try to install in the reverse order as you suggested.

**Comment by karmacoma92** [comment] 2016-01-13 07:58
Ok, I finally made it working, I had to 

1.- Uninstall libfreerdp and lifreerdp plugins as you mentioned before

```sudo apt-get --purge remove libfreerdp1 libfreerdp-plugins-standard remmina-plugin-rdp```

2.- Uninstall freerdp sipe

```sudo apt-get --purge remove freerdp-sipe```

3.-  Uninstall libwinpr0

```sudo apt-get --purge remove libwinpr0.1```

4.- Install libfreerdp and plugins

```sudo apt-get install libfreerdp1 libfreerdp-plugins-standard remmina-plugin-rdp```

5.- Install freerdp sipe

```sudo apt-get install freerdp-sipe```

6.- Install pidgin-sip (looks like it was uninstalled previously 

```sudo apt-get install pidgin-sipe```

Note I didn't need to install libwinpr0.1 since it was already included in libfreerdp1 package. 

I hope this may help the rest....

Thanks a lot for your support!

**Comment by giox069** [comment] 2016-01-13 08:03
@karmacoma92 You're welcome.
I'm leaving this issue open waiting for comments from @montechristos and @cmayoros. Maybe they have different issues.

**Comment by karmacoma92** [comment] 2016-01-13 08:27
Fully agree :-D

//Oscar

**Comment by montechristos** [comment] 2016-01-13 16:52
It didn't work for me:

followed the instructions of @karmacoma92 
Still the same problem

Please instruct me how to send the logs, as I am not a very advanced linux user...

**Comment by cmayoros** [comment] 2016-01-14 00:45
I've followed the steps above without success. I was able to use xfreerdp to connect running it as follows:
xfreerdp /g:<gateway.server> /v:<my.company.pc>

It then prompted me for my username, domain & password and I was then logged into my work pc.

The output from dpkg is as follows:
dpkg --list "freerdp*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
un  freerdp             <none>         <none>         (no description available)
ii  freerdp-x11         1.2.0~git20151 amd64          RDP client for Windows Terminal Services


dpkg --list "remmina*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  remmina             1.1.2-ppa1+819 amd64          remote desktop client for GNOME desktop env
ii  remmina-common      1.1.2-ppa1+819 all            common files for remmina remote desktop cli
un  remmina-gnome       <none>         <none>         (no description available)
un  remmina-plugin-data <none>         <none>         (no description available)
ii  remmina-plugin-rdp  1.1.2-ppa1+819 amd64          RDP plugin for remmina remote desktop clien
ii  remmina-plugin-vnc  1.1.2-ppa1+819 amd64          VNC plugin for remmina remote desktop clien
un  remmina-xfce        <none>         <none>         (no description available)

**Comment by montechristos** [comment] 2016-01-18 11:24
Any update? Something I can do to help?

PS: got the latest updates but still the same problem...

**Comment by cmayoros** [comment] 2016-01-23 00:08
Updated today, version 1.1.2-ppa1+824. Still not working. Any further debugging I can help with?

**Comment by giox069** [comment] 2016-01-23 12:43
anyone could give me a test account reachable via a public IP address ?

**Comment by cmayoros** [comment] 2016-01-23 17:07
Unfortunately I cannot. The connection I'm using is to my computer at work. I don't have any options to create new logins for you to test with. Is there a way I can log more information for you to figure out what's going on?

**Comment by montechristos** [comment] 2016-01-25 22:32
Same here. It still doesn't work and I cannot share the account at work

Can't you install M$ remote gateway on a VM? Sorry, don't know how to do it

**Comment by der-eismann** [comment] 2016-02-29 02:13
Still nothing new? 
Also not working for me on Arch with Remmina 1:1.2.0rcgit.8-1.

**Comment by cmayoros** [comment] 2016-03-03 00:55
I am now getting the error message "Unable to find the address of RDP server ...."

Been testing it each time I see an update available, nothing working yet.

1.2.0-rcgit.8 was the first version not working. Are you not able to look at code changes between it and the previous version to see what was updated? Maybe get something from that. Also, if you want to build a custom version with additional logging that I could run, maybe I would be able to get you more debugging information that way.

I'm happy to help, but can't get you access to an RDP gateway to test against.

**Comment by karmacoma92** [comment] 2016-03-03 06:00
Hi

sorry for not answering before but same happens to me I cannot provide an RDP to test against.

//Oscar

**Comment by akallabeth** [comment] 2016-03-03 07:33
just been informed of a possible source of the issue in freerdp/freerdp#3185

**Comment by giox069** [comment] 2016-03-03 07:46
@akallabeth thank you for reporting and helping. I will follow https://github.com/FreeRDP/FreeRDP/issues/3185 and push an update of FreeRDP to our ubuntu PPA when fixed.

**Comment by jackdozier** [comment] 2016-03-04 01:10
Found this issue while trying to get Remmina working with gateway. It isn't the same one I reported to FreeRDP. 

I'm using Remmina 1.2.0-rcgit.9 (git 0e935eb). The issue seems to be related to a DNS address lookup for the server name that happens from the client machine. The server that I'm connecting to is not published in DNS since it's a desktop on a private network. 

When I specify the server name in my /etc/hosts file, it connects properly through the gateway. It works even if I associate a fake IP address with the server name in /etc/hosts.

Haven't had a chance to look at the code yet. If I find anything, I'll post an update.

**Comment by jackdozier** [comment] 2016-03-04 01:36
The issue appears to be in the init function of remmina-plugins/rdp/rdp_plugin.c. There is already an exclusion in the code for connections through SSH tunnels. I added an exclusion for gateway configs as well. It tested out against gateway and non-gateway configs.

Here are my changes.

[0001-Fixed-address-resolution-when-connecting-through-gat.txt](https://github.com/FreeRDP/Remmina/files/157964/0001-Fixed-address-resolution-when-connecting-through-gat.txt)

**Comment by giox069** [comment] 2016-03-04 09:19
Very good @jackdozier: there is no point in resolving the final server hostname during a gateway session. We could try to resolve the gateway server hostname, but the code is a bit more complex because we must remove the port name. So in the meanwhile, I'm going to emit a commit with your patch.

**Comment by jackdozier** [comment] 2016-03-04 14:38
Newest pull (Remmina 1.2.0-rcgit.9 (git 0ed3e11)) works for me.Thanks for incorporating it!

**Comment by cmayoros** [comment] 2016-03-24 22:59
Even after multiple updates since last time I posted, I'm getting the old errors still "Unable to connect to RDP server ..."

**Comment by jackdozier** [comment] 2016-03-25 02:42
I'm still able to connect via gateway on latest pull (1.2.0-rcgit.11 (git a3d6f23)) in my environment. I get that error if I put bad data (nonexistent host) in Server or RD Gateway Server fields. Can you confirm those fields are filled out correctly and list your Remina version from the about page?

**Comment by cmayoros** [comment] 2016-03-25 14:35
The connection information saved in Remmina was the same I had successfully used before this started. To be safe, I deleted the profile and set it up again. The information I used comes from the Microsoft remote desktop connection script provided by our helpdesk. Using this same information on xfreerdp is connecting successfully.

Remmina shows that it is version 1.2.0-rcgit.11 (git n/a)

**Comment by montechristos** [comment] 2016-03-27 08:52
Same here

**Comment by jackdozier** [comment] 2016-03-28 03:05
I spent some time setting up a test windows 2008r2 gateway server. I'm able to connect to it. Can you please try to connect to it through your version of Remmina to see if you have the same issue you currently have?

Server: 127.0.0.1
Username: test
Password: asdQWE123
RD Gateway Server: gateway.jackdozier.com

It's a virtual machine running on an underpowered host, so don't be concerned if connecting is slow.

**Comment by cmayoros** [comment] 2016-03-29 00:52
I was able to connect to your server successfully.

**Comment by jackdozier** [comment] 2016-03-29 00:59
Interesting. Do you have any way to know the version of Windows that is running on the gateway server or the destination server? That could help us narrow down on the issue.

Can you try putting the server name in your /etc/hosts file? For example, if the computer I was attempting to connect to was called "mydesktop", I would add a line to /etc/hosts like below. The IP address you use shouldn't matter.

192.168.1.100     mydesktop

**Comment by cmayoros** [comment] 2016-03-29 01:14
The destination I'm connecting to is my desktop workstation, it's running Windows 7 Enterprise. I do not know what Windows version is on the gateway server. I've added the line:
10.8.10.60 CLE-4NH2P22
to my hosts file, no luck there either. I tried it with the rest of the domain name as well, same thing.

**Comment by jackdozier** [comment] 2016-03-29 02:14
If you run remina from a command line, do you get any errors when trying to connect? For example, if I put a typo in the gateway hostname, I get the following on the command line when I try to connect.

[21:11:49:552] [17008:17014] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[21:11:49:711] [17008:17014] [ERROR][com.freerdp.core] - getaddrinfo: Name or service not known
[21:11:49:852] [17008:17014] [ERROR][com.freerdp.core] - getaddrinfo: Name or service not known
[21:11:49:852] [17008:17014] [ERROR][com.freerdp.core.gateway.tsg] - rpc_connect error!
[21:11:49:852] [17008:17014] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[21:11:49:852] [17008:17014] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[21:11:49:852] [17008:17014] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by cmayoros** [comment] 2016-03-29 23:40
Finally. Solved it. Thank you. This is what I've needed, I tried running Remmina from a command line as you suggested, and saw the output. Below is a copy, with company info edited out. Once I saw this and realized it's a certificate error, I tried to remove any old certificates without any luck. Then found the option on the advanced settings screen to ignore the certificate. Turned that on, and was immediately able to connect. Thank you again for your assistance.

[19:35:43:788] [9744:9759] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - @           WARNING: CERTIFICATE NAME MISMATCH!           @
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - The hostname used for this connection (***.***.com:443) 
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - does not match any of the names given in the certificate:
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - Common Name (CN):
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - 	gateway.***.com
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - Alternative names:
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - 	 gateway.***.com
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - A valid certificate for the wrong name should NOT be trusted!
[19:35:43:979] [9744:9759] [ERROR][com.freerdp.crypto] - certificate not trusted, aborting.
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - @           WARNING: CERTIFICATE NAME MISMATCH!           @
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - The hostname used for this connection (***.***.com:443) 
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - does not match any of the names given in the certificate:
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - Common Name (CN):
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - 	gateway.***.com
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - Alternative names:
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - 	 gateway.***.com
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - A valid certificate for the wrong name should NOT be trusted!
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.crypto] - certificate not trusted, aborting.
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_CANCELLED [0x2000B]
[19:35:43:171] [9744:9759] [ERROR][com.freerdp.core.gateway.tsg] - rpc_connect error!
[19:35:43:172] [9744:9759] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[19:35:43:172] [9744:9759] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

**Comment by der-eismann** [comment] 2016-03-30 10:23
I can confirm this, I also get the certificate error. For me it looks like it compares the certificate of the gateway with the hostname of the RDP server which results in an error.

[12:15:59:300] [2308:2313] [ERROR][com.freerdp.crypto] - The hostname used for this connection (<IP address>:443) 
[12:15:59:300] [2308:2313] [ERROR][com.freerdp.crypto] - does not match any of the names given in the certificate:
[12:15:59:300] [2308:2313] [ERROR][com.freerdp.crypto] - Common Name (CN):
[12:15:59:300] [2308:2313] [ERROR][com.freerdp.crypto] - 	gateway.public.domain.com

**Comment by ic3d** [comment] 2017-09-13 19:21
Hi @cmayoros @der-eismann, we are reviewing open issues. Reading the comments above I can assume this one is fixed, isn't it? Thanks!

**Comment by ic3d** [comment] 2017-10-05 16:37
I'm closing this issue, assuming it's fixed. Feel free to open it again if needed.

**Closed by ic3d** 2017-10-05 16:37 UTC
Labels: confirmclose
