### ISSUE TITLE
SSH windows closes without message

### ISSUE THREAD

**Issue by mreichardt95** [FreeRDP/Remmina#975] opened 2016-08-22 14:18 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
- Client (OS name and version): Arch Linux x64
- Remmina version (remmina --version): 1.2-rcgit-15
- Desktop environment (GNOME, Unity, KDE, ..): GNOME
- Connecting to (OS and version): Windows 2012R2 (cygwin)
- Connecting via (RDP, VNC, ...): SSH
- RDP issues only, freerdp version (xfreerdp --version): -

Hey, im trying to connect to a  Windows Server via SSH. 
Over the Gnome-terminal it works all fine, but if I use the Remmina-SSH plugin, the Terminal Window randomly closes. There appear absolutly no Messages about this in  the Debug window. So it is relativly hard to track it. On the Server side the log just says 
`Disconnected from 172.19.254.10 port 1664`
or
`Received disconnect from 172.19.254.10 port 1664:11: disconnected by user`
I tried installing different Versions of Remmina (normal repo and git checkout) but the same issue.

Best Regards
##

**Comment by antenore** [comment] 2016-08-22 20:41
Did you execute Remmina from the command line (before be sure that remmina is not already running)? Can you eventually try and check the output to see what happens?

From Gnome terminal I guess you are using openssh, while remmina uses libssh (both uses VTE).
If it's that the case I'd ask help, also, to the libssh team to see if they are aware of a similar issue and they know a work around (or if they can point us in the right direction).

Can you please do these for us? Thanks in advance.

**Comment by mreichardt95** [comment] 2016-08-23 07:56
Hey, 
I Started remmina over the Terminal this is the Output: 
```
mreichardt@LPT-031:~$  remmina

(remmina:1557): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(remmina:1557): Gtk-WARNING **: Theme parsing error: <data>:16:28: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:1557): Gtk-WARNING **: Theme parsing error: <data>:17:31: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:1557): Gtk-WARNING **: Theme parsing error: <data>:22:28: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:1557): Gtk-WARNING **: Theme parsing error: <data>:23:31: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version

(remmina:1557): Gtk-WARNING **: Allocating size to GtkScrollbar 0x1d41980 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(remmina:1557): Gtk-WARNING **: Allocating size to GtkScrollbar 0x1ed9bb0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(remmina:1557): Gtk-WARNING **: Allocating size to GtkScrollbar 0x1ec7da0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

Also the Output of the Debug Window (it doesnt even say something about the disconnect):
```
[SSH] ssh_config_parse_file: Reading configuration data from /home/mreichardt/.ssh/config
[SSH] ssh_config_parse_line: Unsupported option: ServerAliveInterval, line: 2

[SSH] ssh_config_parse_line: Unsupported option: ServerAliveCountMax, line: 3

[SSH] ssh_config_parse_file: Reading configuration data from /etc/ssh/ssh_config
[SSH] ssh_config_parse_line: Unsupported option: ServerAliveInterval, line: 33

[SSH] ssh_connect: libssh 0.7.3 (c) 2003-2014 Aris Adamantiadis, Andreas Schneider, and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[SSH] getai: host 172.19.205.146 matches an IP address
[SSH] ssh_socket_connect: Nonblocking connection socket: 11
[SSH] ssh_connect: Socket connecting, now waiting for the callbacks to work
[SSH] ssh_connect: Actual timeout : 50000
[SSH] ssh_socket_pollcallback: Received POLLOUT in connecting state
[SSH] socket_callback_connected: Socket connection callback: 1 (0)
[SSH] callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.2
[SSH] ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.2
[SSH] ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.2
[SSH] ssh_analyze_banner: We are talking to an OpenSSH client version: 7.2 (70200)
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] ssh_packet_socket_callback: packet: read type 20 [len=972,padding=10,comp=961,payload=961]
[SSH] ssh_packet_process: Dispatching handler for packet type 20
[SSH] ssh_list_kex: kex algos: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
[SSH] ssh_list_kex: server host key algo: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
[SSH] ssh_list_kex: encryption client->server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[SSH] ssh_list_kex: encryption server->client: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
[SSH] ssh_list_kex: mac algo client->server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[SSH] ssh_list_kex: mac algo server->client: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[SSH] ssh_list_kex: compression algo client->server: none,zlib@openssh.com
[SSH] ssh_list_kex: compression algo server->client: none,zlib@openssh.com
[SSH] ssh_list_kex: languages client->server: 
[SSH] ssh_list_kex: languages server->client: 
[SSH] ssh_knownhosts_algorithms: server 172.19.205.146:22 has ecdsa-sha2-nistp256 in known_hosts
[SSH] ssh_client_select_hostkeys: Changing host key method to "ecdsa-sha2-nistp256"
[SSH] ssh_list_kex: kex algos: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
[SSH] ssh_list_kex: server host key algo: ecdsa-sha2-nistp256
[SSH] ssh_list_kex: encryption client->server: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc
[SSH] ssh_list_kex: encryption server->client: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc
[SSH] ssh_list_kex: mac algo client->server: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[SSH] ssh_list_kex: mac algo server->client: hmac-sha2-256,hmac-sha2-512,hmac-sha1
[SSH] ssh_list_kex: compression algo client->server: none
[SSH] ssh_list_kex: compression algo server->client: none
[SSH] ssh_list_kex: languages client->server: 
[SSH] ssh_list_kex: languages server->client: 
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=444,padding=4,comp=439,payload=439]
[SSH] packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] ssh_packet_socket_callback: packet: read type 31 [len=260,padding=10,comp=249,payload=249]
[SSH] ssh_packet_process: Dispatching handler for packet type 31
[SSH] ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
[SSH] ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
[SSH] ssh_packet_socket_callback: Processing 16 bytes left in socket buffer
[SSH] ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
[SSH] ssh_packet_process: Dispatching handler for packet type 21
[SSH] ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
[SSH] crypt_set_algorithms2: Set output algorithm to aes256-ctr
[SSH] crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
[SSH] crypt_set_algorithms2: Set input algorithm to aes256-ctr
[SSH] crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
[SSH] ssh_pki_signature_verify_blob: Going to verify a ecdsa-sha2-nistp256 type signature
[SSH] ssh_packet_newkeys: Signature verified and valid
[SSH] ssh_connect: current state : 7
[SSH] packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
[SSH] ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
[SSH] ssh_packet_process: Dispatching handler for packet type 6
[SSH] ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=60,padding=18,comp=41,payload=41]
[SSH] ssh_packet_socket_callback: packet: read type 51 [len=44,padding=8,comp=35,payload=35]
[SSH] ssh_packet_process: Dispatching handler for packet type 51
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: password,keyboard-interactive
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: password,keyboard-interactive
[SSH] ssh_userauth_kbdint_init: Sending keyboard-interactive init request
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=76,padding=10,comp=65,payload=65]
[SSH] ssh_packet_socket_callback: packet: read type 51 [len=44,padding=8,comp=35,payload=35]
[SSH] ssh_packet_process: Dispatching handler for packet type 51
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: password,keyboard-interactive
[SSH] ssh_packet_userauth_failure: Access denied. Authentication that can continue: password,keyboard-interactive
[SSH] ssh_socket_unbuffered_write: Enabling POLLOUT for socket
[SSH] packet_send2: packet: wrote [len=76,padding=16,comp=59,payload=59]
[SSH] ssh_packet_socket_callback: packet: read type 52 [len=12,padding=10,comp=1,payload=1]
[SSH] ssh_packet_process: Dispatching handler for packet type 52
[SSH] ssh_packet_userauth_success: Authentication successful
[SSH] ssh_packet_userauth_success: Received SSH_USERAUTH_SUCCESS
[glibsecret] password deleted for file /home/mreichardt/.local/share/remmina/1471531928864.remmina
[glibsecret] password deleted for file /home/mreichardt/.local/share/remmina/1471531928864.remmina
[glibsecret] password deleted for file /home/mreichardt/.local/share/remmina/1471531817680.remmina
```

Yes I'll get in contact with them and link this Issue here. 

Regards

**Comment by e-alfred** [comment] 2016-08-31 10:57
This is probably related to https://github.com/FreeRDP/Remmina/issues/985. The tabs close without a message after some time.

**Comment by nhdnet** [comment] 2017-03-19 12:42
I just update libssh ticket. I put same information here. Maybe usefull:
Same here. Tested with last version of Remmina.
I suspect that it close TCP socket when a packet loss occurs. Very often on wireless networks.
Ubuntu's ssh command its very much robust and reestablish session transparently.
I tested unplugging wire ethernet from my wireless access point and plugging again (no wireless link lost on laptop). SSH command reenable session even if I type some words during AP wire disconnection or show all remaining 'top refresh' together when I reconnect wire to AP. LibSSH (Remmina) close window as soon I unplug AP's ethernet wire.
It can explain why libssh connection over openssh tunnel doesnt close. Openssh recover any packet lost with very low delay.
I wish this info could be usefull.
Regards

**Comment by antenore** [comment] 2017-03-19 20:02
@nhdnet thank you. Very useful. I'll take a look in about one week.

**Comment by e-alfred** [comment] 2017-03-20 11:32
Yes, I also would say it happens if packet loss occurs. My local SSH connections work well and stay open all the time, but external connections are troublesome and get closed after some time. I can also confirm that the same connections stay open all the time if I use the ssh on CLI or Putty on Windows, so these tools are more robust than Remmina/libssh.

**Comment by TamiasSibiricus** [comment] 2017-07-22 08:42
Could confirm this bug too. After a while of time some connections closing unexpectedly. In my work i need to keep connections alive for long time and this small bug is little annoying. :)

**Comment by lorenzov83** [comment] 2017-08-01 08:24
I have the same problem, it's pretty dangerous because ssh sessions are accidentally closed and often stop shelled processes.
If I use other ssh clients, the problem does not occur
Please fix it

**Comment by lorenzov83** [comment] 2017-08-01 08:29
I have the same problem, it's pretty dangerous because ssh sessions are accidentally closed and often stop shelled processes.
If I use other ssh clients, the problem does not occur
Please fix it

**Comment by erhanvarlik** [comment] 2017-10-23 12:37
Same problem here, it's very annoying and like @lorenzov83 said, it's preetty dangerous.

**Comment by antenore** [comment] 2017-10-23 13:48
We rely on libssh, so we cannot really do anything, or at least this is my opionion, if I'm wrong please help me to fix this.

Can you keep pinging the libssh guys?

https://red.libssh.org/issues/239

@giox069 do you think we can implement the reconnect here? Will it help (I doubt honestly)

**Comment by lorenzov83** [comment] 2017-10-23 14:44
I'm sorry @antenore but because the problem does not come with other ssh clients on the same pc ?
bash and remmina do not use the same ssh libraries?
I'm probably wrong, but I think the problem is due to a lack of management of the ssh library's exceptions by remmina

**Comment by antenore** [comment] 2017-10-23 14:52
@lorenzov83 With the other terminals you use a command that is ssh, that comes from OpenSSH. Remmina uses libssh that is a library and not a command.

We cannot use OpenSSH here because we should fork ssh commands and it could make things even worst. The Gnome team, for instance, are willing to migrate to libssh as well for their client Vinagre for the same reason.

https://wiki.gnome.org/Apps/Vinagre/RoadMap

**Comment by lorenzov83** [comment] 2017-10-23 15:18
@antenore many thanks for the answer.
It's a shame because this problem makes ssh connections unmanageable with remmina.
For ssh connections I'm are forced to use PAC Manager that using OpenSSH library, it's not as good as Remmina but at least the ssh connections are stable.
Do you just exclude the possibility of using OpenSSH libraries?

**Comment by antenore** [comment] 2017-10-23 15:48
At the moment yes, but I don't give up in fixing this issue. Well I need your support (all) to fix it.

@lorenzov83

**Comment by e-alfred** [comment] 2017-10-23 18:22
I see this issue mostly on unstable connections over WIFI and high latency. Would it be possible to make connections more stable by having something similar to the Keealive setting in OpenSSH?

**Comment by antenore** [comment] 2017-10-23 18:34
@e-alfred Yes supporting the libssh team providing them traces, use cases and so forth. From our side I'll continue to investigate as well.

**Comment by Hubbitus** [comment] 2018-01-11 20:38
Please look at comment of Fedora bugreport https://bugzilla.redhat.com/show_bug.cgi?id=1488405#c16 it has details about reproduce of issue. It looks like say about similar issue.

**Comment by antenore** [comment] 2018-01-11 22:32
I'm testing right now on Arch Linux, with Remmina compiled from the last git commit.
I'll wait till the connection close and see why. I'll keep you updated.

**Comment by erhanvarlik** [comment] 2018-02-05 11:29
I updated fedora and also remmina. It happened again.

**Comment by antenore** [comment] 2018-02-21 11:15
@erhanvarlik Always as usual or is it a bit better at least?

**Comment by antenore** [comment] 2018-03-08 15:07
If you have an SSH server that doesn not support compression through zlib, see issue #1505

**Comment by antenore** [comment] 2018-04-08 22:56
Resolved via #1553

**Closed by antenore** 2018-04-08 22:56 UTC
Labels: SSH, bug

**Comment by nhdnet** [comment] 2018-04-08 23:54
Awesome antenore! !!
I will back to Remmina and give you some feedback. Can this kinds of timeout send a log anywhere or windows popup to trace?

Thank you very much!

Regards

**Comment by antenore** [comment] 2018-04-09 05:15
Not really, I'll see for a future release. 
Be sure to have rcgit-29.

**Comment by TamiasSibiricus** [comment] 2018-04-09 17:31
Thanks for patch.
