### ISSUE TITLE
SSH connections terminate after some time if there is no activitiy in them

### ISSUE THREAD

**Issue by e-alfred** [FreeRDP/Remmina#1176] opened 2017-05-14 08:15 UTC
Hello,

my SSH connections terminate after some time in Remmina if they are idle. This can be hours (mostly), but if some process runs on the terminal inside Remmina, the connection stays up. This problem does not occur with the CLI ssh client or Putty, for example. is there a possibility to enable/implement/respect the `ServerAliveInterval` like in ssh_config? I already tried to set it in ssh/config in my home folder, but it has no effect.

System details:
* Client (OS name and version): Kubuntu 14.04.5
* Remmina version (remmina --version): 1.2.0-rcgit-18 (git rcgit-18)
* Desktop environment (GNOME, Unity, KDE, ..):  KDE
* Connecting to (OS and version):  Ubuntu 14.04 Server, Debian Wheezy and Jessie, Synology DSM, Centos 7, Fedora 25, Raspbian
* Connecting via (RDP, VNC, ...):  SSH

**Comment by bperel** [comment] 2017-06-11 17:41
Maybe related to #975

**Comment by antenore** [comment] 2018-02-21 11:11
Duplicate of #975

**Comment by antenore** [comment] 2018-04-08 23:00
Resolved via #1553 
Let me know otheriwise

**Closed by antenore** 2018-04-08 23:00 UTC
Labels: SSH, duplicate
