### ISSUE TITLE
Remmina doesn't respect the `SSH Tunnel` `SSH authentication` `User name` setting

### ISSUE THREAD

**Issue by Andrew-Poloni** [FreeRDP/Remmina#1278] opened 2017-09-14 22:41 UTC
Remmina version 1.2.0-rcgit-20 (git rcgit-20) running on Ubuntu 16.04.3 LTS

I've noticed (with some irritation) that Remmina always wants to replace the `User name` in the SSH Authentication section of the SSH Tunnel tab with the linux username, even when an existing connection is being edited and the value had been previously changed.  This requires that you go in and re-enter the user name for the SSH tunnel every time you make a change to the connection settings (just an annoyance, really).

**Comment by antenore** [comment] 2017-09-15 05:58
I'm sorry for this. It should be fixed in the 'next' branch and we'll merge it ASAP.

I'd really appreciate if you could test it. Do you mind?

**Comment by Andrew-Poloni** [comment] 2017-09-18 18:19
No worries at all, it's a *very* minor thing.  Be delighted to give the
fix a whirl.

|==============================>
| Andrew M. Poloni
| 36538 Snickersville Tpke.
| Purcellville, VA.  20132-4258
| (610) 212.7452 (cell)
|==============================>
| andrew.m.poloni@gmail.com
|==============================>

**Comment by giox069** [comment] 2017-10-06 20:37
This is a duplicate of issue #1255, already fixed in commit https://github.com/FreeRDP/Remmina/commit/435f8269aa88a6f4c274f1f43d9e8471d91a88c7
Please wait the release ot remmina 1.2.0-rcgit.21 into the remmina-next PPA, or test it using the remmina-next-daily (only for testing) PPA.

**Closed** 2017-10-15 09:08 UTC
Labels: backlog
