### ISSUE TITLE
Cursor box

### ISSUE THREAD

**Issue by nathangoing** [FreeRDP/Remmina#566] opened 2015-05-07 10:56 UTC
I get a box around my cursor during RDP sessions. Appears to be mostly the I-beam pointer. Please see the video: http://1drv.ms/1F0cTQa sorry to use my phone, but screenshot software appears to force an invalidation to the layer showing the cursor. 

Remmina 1.2.0-rcgit.3
Ubuntu 14.04.1

Thanks
##

**Comment by giox069** [comment] 2015-05-07 11:08
Which version of remmina and which operating system are you using ?
(please, **never** open an issue without providing such data, thank you).

**Comment by nathangoing** [comment] 2015-05-07 11:12
Sorry about that! somebody interrupted me while I was typing and completly forgot...

Date: Thu, 7 May 2015 04:08:15 -0700

**Comment by giox069** [comment] 2015-05-07 11:48
it seems to be something related to the video driver. Which graphic card are you using ?
Can you provide the output of
```
sudo lshw -C video
```
Thank you.

**Comment by nathangoing** [comment] 2015-05-07 11:56
```
  *-display               
       description: VGA compatible controller
       product: RV730 PRO [Radeon HD 4650]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:48 memory:d0000000-dfffffff memory:f0200000-f020ffff ioport:2100(size=256) memory:f0220000-f023ffff
  *-display
       description: VGA compatible controller
       product: RV730 PRO [Radeon HD 4650]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:20:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:50 memory:e0000000-efffffff memory:f0100000-f010ffff ioport:1100(size=256) memory:f0120000-f013ffff
```

**Comment by giox069** [comment] 2015-05-07 17:46
Unfortunately I cannot reproduce it. As explained before, it seems to be a video driver problem. The video driver here is "radeon", the opensource driver included with the linux kernel.
You can try yo update the kernel to 3.19 as explained here: [how-can-i-use-kernel-3-19-in-14-04-now](http://askubuntu.com/questions/598483/how-can-i-use-kernel-3-19-in-14-04-now), it should bring you a newer radeon driver.
You can also try to connect to the same RDP server with xfreerdp command on the command line and see if it works.

**Comment by nathangoing** [comment] 2015-05-07 19:21
Thank you, I'll look into that tonight.

**Comment by ic3d** [comment] 2016-12-28 16:25
Hi @nathangoing :-) Do you still get this issue?

**Comment by ic3d** [comment] 2017-01-19 15:22
I'm closing this issue because it seems to affect an old version of Remmina.

**Closed** 2017-01-25 19:36 UTC
Labels: unconfirmed, wontfix
