### ISSUE TITLE
Slow work through VPN tunnels

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [FreeRDP/Remmina#850] opened 2016-04-29 10:22 UTC
Hello.

We use the latest version of the RDP client on Ubuntu / Kubuntu 16.04 LTS with the packages:

remmina:amd64/xenial 1.2.0~rcgit-11+894+next+201604262127~ubuntu16.04.1
remmina-plugin-rdp:amd64/xenial 1.2.0~rcgit-11+894+next+201604262127~ubuntu16.04.1
freerdp-x11:amd64/xenial 2.0.0~dev~git20160331+dfsg-0xenial2

We are connecting remotely to computers Windows Server 2012 R2 and Windows 10. 
RDP session, which runs through the VPN tunnel (I tested different protocols such as PPTP / SSTP / OpenVPN), works very slowly. 
Through this same tunnel VPN RDP client from Microsoft is working properly.
Is there any way to solve this problem?
##

**Comment by antenore** [comment] 2016-04-29 15:43
@giox069 any chance you can test this specific scenario?

**Comment by giox069** [comment] 2016-04-29 18:16
Just tested on Ubuntu 16.04 x64, last remmina-next PPA update, with a Cisco IPSec VPN tunnel opened from my laptop to a Cisco router. Destination RDP server is a Windows 10 PC.
All is working fine, and my daily job is using also OpenVPN, PPTP and IKEv2 vpns...
So the correct answer here is... I can't reproduce.
@Aleksey-Maksimov: other tests you can do:
- Try to connect without VPN (ie: by temporary opening some port with NAT/PAT on the destination router
- Try to change some settings in remmina profile: lower quality settings, disable audio, reduce the number of bpp to 15 or 16.
- Also please try with the commandline
 `xfreerdp /v:hostname /u:username /d:domain`

**Comment by sashasaturn** [comment] 2017-03-03 09:12
Hi all,
Well, I'm having the same issue reported by @Aleksey-Maksimov .
I'm using Ubuntu 14.04 LTS with openconnect as a client to connect to  Cisco VPN.
Versions
 openconnect    5.02-1       amd64
 remmina  1.2.0-rcgit-18-1.0ubuntu1~trus amd64

I'd tried to change settings in profile as suggested by @giox069 - doesn't help.
Connection without VPN works much better.

**Comment by antenore** [comment] 2017-03-03 10:36
Isn't it at a TCP level the issue?
If ICMP is allowed, can you ping the host with and without the VPN to see if the bottleneck is the VPN itself?

I now use openconnect at home, plus socks5 tunnels and it's not that bad

**Comment by ic3d** [comment] 2017-09-25 19:57
Hi @vext01 @Aleksey-Maksimov @sashasaturn we're reviewing old issues, do yuo still get this one? We only support Remmina 1.2.* Thanks!

**Comment by ic3d** [comment] 2017-10-05 16:43
I'm closing this issue because it probably affects an old version of Remmina. Feel free to open it again if needed.

**Closed** 2017-10-15 11:21 UTC
Labels: unconfirmed, wontfix
