### ISSUE TITLE
The image of the commented text from an SQL editor is mallformed

### ISSUE THREAD

**Issue by liviudelureanu** [FreeRDP/Remmina#736] opened 2016-01-22 20:28 UTC
Hi!
I use Remmina 1.2.0-rcgit.8 on Linux Mint 17.1 Rebecca.

My problem is that the image of the commented text from an SQL editor is mallformed in Remmina.  
For example,I'm using TOAD for Oracle SQL/PL-SQL editor on the remote Windows 7 PC.
In SQL/PL-SQL language, you may make comments in code in two ways:
1. with -- for single line comment
2. with /* ... */
 / *
  _for more lines
  comments_
*/

(Note: The multiline comments are realized with  "slash" "back slash" and "*" without spaces between, but "github" editor do not show * only if I let a space between / and *   ) 

The problem is that Remmina reveal as "hidden" this type of commented lines. 
Please see the images attached to compare hou reveal those lines Remmina versus another remote tool:
1. the correct mode :
![screenshot from 2016-01-22 22 07 28](https://cloud.githubusercontent.com/assets/16843534/12522084/3b7e8bd8-c157-11e5-822b-522c60f6347e.png)
1. the wrong(Remmina) mode :
   ![screenshot from 2016-01-22 22 00 48](https://cloud.githubusercontent.com/assets/16843534/12522090/40f4eeae-c157-11e5-819d-41cc5df3ad23.png)
##

**Comment by giox069** [comment] 2016-01-22 21:10
Hi @liviudelureanu, thank you for reporting.
The drawing code for remmina is undergoing to a huge change, and I think it will be totally redone in a couple of week. In the meanwhile can you test it using xfreerdp from che command line
```
xfreerdp /v:hostname /u:username /d:domain
```
and 
```
xfreerdp /v:hostname /u:username /d:domain /gdi:sw
```
It will help us in discovering if the problem is in libfreerdp or remmina.

**Comment by liviudelureanu** [comment] 2016-01-24 08:24
Hi!
Thans for your fast reply!
I've tried also with 
   xfreerdp /v:hostname /u:username /d:domain
and
   xfreerdp /v:hostname /u:username /d:domain /gdi:sw
but the result is the same: the image is not correctly reproduced.

**Comment by giox069** [comment] 2016-01-24 14:14
It seems to be a FreeRDP problem. Can you post the output of
```
xfreerdp --version
```
?
Thank you.

**Comment by liviudelureanu** [comment] 2016-01-25 15:52
The version of FreeRDP is : 
"This is FreeRDP version 2.0.0-dev (git n/a)"

**Comment by liviudelureanu** [comment] 2016-12-03 09:19
Hi!
I think I've found a little more about the cause of problem: if I set that the comments in TOAD SQL Editor to not be formatted as _Italic_ , than the comments are displayed correctly . 
Hope it is helpful.

**Comment by ic3d** [comment] 2017-09-13 19:28
I'm closing this issue because it probably affects an old version of FreeRDP. Feel free to open it again if needed.

**Closed** 2017-09-17 09:15 UTC
Labels: outofscope, wontfix
