### ISSUE TITLE
Systray icon closes when closing 'Main Window' or RDP connection

### ISSUE THREAD

**Issue by Bruadar** [FreeRDP/Remmina#1229] opened 2017-07-27 19:52 UTC
Please give us some details about the systems you are using:
* Client (OS name and version): Debian Testing
* Remmina version (remmina --version): 1.2.0-rcgit-19 (git v1.2.0-rcgit.19)
* Desktop environment (GNOME, Unity, KDE, ..):  GNOME
* Connecting to (OS and version): Windows 7 Pro
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): This is FreeRDP version 2.0.0-dev (git 7891a0f91)

The systray icon disappears when the 'Main Window' or RDP connection is closed.

**Comment by antenore** [comment] 2017-07-27 23:58
This is not a bug but a feature :-)

The icon disappear because closing the main window you are closing the Remmina process.

We had some bug and feature requests asking to close Remmina if there were not opened connections. So, if you have 2 or more connections opened and you close the main window, Remmina won't exit.

If you want to just minimize Remmina you can use your window manager controls to do it.

I'm closing this, but if you don't agree feel free to reopen it and we can discuss this further.

**Comment by giox069** [comment] 2017-07-28 06:22
@antenore in almost all desktop I tested remmina, when the systray/appindicator icon is available and visible, remmina should not close. @Bruadar: can you post a screenshot of your systray icon (maybe is not a systray icon), and execute remmina in a terminal and then copy & paste the first lines of output about systray/appindicator here? Are you using Gnome or GnomeShell?

**Comment by Bruadar** [comment] 2017-07-28 08:39
I'm using GnomeShell. I like, with Remmina 1.1x that my users can open a RDP connection from the systray. My users use various other DE's too which I have not yet tested.

Here is what I get in the terminal:

`StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed`

And the screenshot:

![screenshot from 2017-07-28 10-28-43](https://user-images.githubusercontent.com/29062284/28709488-cddaa12e-7380-11e7-8eb4-8d062eaaae89.png)

**Comment by giox069** [comment] 2017-07-28 09:08
Ok, now I'm starting to understand what's happening:
in older Gnome Shell, the systray icon was not visible. You were forced to press ALT M (or a similer key) to see the systray bar. So I decided to exit remmina immediately if Gnome Shell is detected, because the user had no visual feedback of remmina running.
Recently gnome shell has changed, they introduced the ribbon on the bottom left of the screen, which can host GtkStatusIcons (the Remmina systray icon). Or maybe this is a common extension.
I'm investigating on that ribbon and the exact version of gnome it was introduced, and then I will try to patch it.
In the meanwhile, if you are compiling remmina, you can add "-DWITH_APPINDICATOR=on" to cmake commandline (and install the appropiate libappindicator-dev package). With libappindicator compiled in, remmina should not exit.

**Comment by Bruadar** [comment] 2017-07-28 10:41
@giox069 I recompiled Remmina according to your instructions but it didn't help. The systray icon still closes. I'm thankful for your Remmina and your dedication.

**Comment by giox069** [comment] 2017-07-28 11:41
@Bruadar I realized too late that you need also an extra Gnome Shell extension called "KStatusNotifier/Appindicator", and then I edited the previous message.
But... you can forget -DWITH_APPINDICATOR=on.
I'm trying to fix it, you can find a new branch called "issue_1229". The new code should detect Gnome Shell >= 3.16, where the Status Icon drawer is visible, and avoid to close remmina when there are no windows.
Can you test this new branch?

**Comment by Bruadar** [comment] 2017-07-28 12:33
Great! I've tested the branch and it works. The master branch works with the "KStatusNotifier/Appindicator" extension too but not with the 'Status Icon drawer'. With branch 'issue_1229' it does.

Now, when "KStatusNotifier/Appindicator" is not enabled terminal reports:

`StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed`

With "KStatusNotifier/Appindicator" enabled terminal reports:

`StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!`

**Comment by giox069** [comment] 2017-07-29 07:27
Merged. The fix is in the "next" branch now.

**Closed** 2017-07-29 07:27 UTC
Labels: notabug

**Comment by giox069** [comment] 2017-08-23 13:17
the so called "legacy tray" (drawer), [will be removed in Gnome Shell 3.26](https://bugzilla.gnome.org/show_bug.cgi?id=785956). In Gnome Shell 3.26 there will be NO WAY to have a systray menu for remmina, unless you install some specific extension like [KStatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/).
I think we should change again the exit strategy of remmina after the legacy tray will disappear again.
