### ISSUE TITLE
Connection to all servers stopped working with last update of remmina-next PPA

### ISSUE THREAD

**Issue by tomas-korec** [FreeRDP/Remmina#506] opened 2015-03-01 11:29 UTC
Hi, I used Remmina yesterday and everthing was ok. Today I installed update (now I have 1.2.0-rcgit.2). From synaptic history:

<pre>
Upgraded the following packages:
remmina (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-common (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-plugin-gnome (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-plugin-nx (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-plugin-rdp (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-plugin-telepathy (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-plugin-vnc (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
remmina-plugin-xdmcp (1.1.1-1+710+next+201502271631~ubuntu14.04.1) to 1.1.1-1+714+next+201502281631~ubuntu14.04.1
</pre>

and I cannot connect to any server from my list of six servers. They are running.

**Comment by muflone** [comment] 2015-03-01 11:39
What connection type are you using?
What errore are you receiving?

Please provide useful information.
This issue reporting so made is pretty useless.

**Comment by tomas-korec** [comment] 2015-03-01 11:47
Sorry. I use RDP and the error message is the same: "Unable to connect to RDP server XX.XX.XX.XX"

**Comment by giox069** [comment] 2015-03-01 12:17
Same problem here. Here is the console outpur of FreeRDP:
```
[13:13:42:862] [3415:-872417536] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[13:13:42:862] [3415:-872417536] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[13:13:42:863] [3415:-872417536] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[13:13:42:863] [3415:-872417536] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[13:13:42:863] [3415:-872417536] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x2000C
[13:13:42:863] [3415:-872417536] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

```

I can only assume 2 possible causes:
1. The PPA was updated yesterday when the Remmina-next branch was in an "unstable" state ?
2. Newest Remmina is using some new feature of FreeRDP which is not included in the current freerdp's PPA (it's dated back FEB 07).

For 2. I kindly ask @dktrkranz to update FreeRDP on remmina-next PPA. @dktrkranz can you update FreeRDP in remmina-next PPA (and refresh Remmina) as soon as possible, so tomorrow, monday, when people will get back to work will not risk to find an updated non-working version of remmina next ?
Thank you.

**Comment by muflone** [comment] 2015-03-01 12:55
I think the issue is fixed from the commit 47137a38b6f64a116ae085905fba4124e9396939

On the next PPA update your issue should be solved.

**Comment by giox069** [comment] 2015-03-01 13:06
Ok, I will retest the PPA after its automatic refresh (16:31 GMT). Thank you @muflone.

**Comment by tomas-korec** [comment] 2015-03-01 13:12
Wow, that was quick! Thank you guys. :)

**Comment by giox069** [comment] 2015-03-01 18:19
Testing done. The latest version (1.1.1-1+719+next+201503011631~ubuntu14.04.1) works.

@dktrkranz: please **DO NOT** update FreeRDP as requested before. I have found they messed up something in return codes when authentication fails. And the older FreeRDP on the PPA works better.

@tomas-korec: please close this issue if Remmina also works for you.
Giovanni

**Comment by tomas-korec** [comment] 2015-03-01 22:12
It works! Thank you :)

**Closed** 2015-03-01 22:12 UTC
