### ISSUE TITLE
Window 0x555b79d3d650 has not been made visible in GdkSeatGrabPrepareFunc

### ISSUE THREAD

**Issue by alirezaimi** [FreeRDP/Remmina#1359] opened 2017-11-03 06:04 UTC
Failed to load plugin: /usr/lib/remmina/plugins/remmina-plugin-spice.so.
Error: libspice-client-gtk-3.0.so.5: cannot open shared object file: No such file or directory
Failed to load plugin: /usr/lib/remmina/plugins/remmina-plugin-vnc.so.
Error: libvncclient.so.1: cannot open shared object file: No such file or directory
Failed to load plugin: /usr/lib/remmina/plugins/remmina-plugin-telepathy.so.
Error: /usr/lib/remmina/plugins/remmina-plugin-telepathy.so: undefined symbol: remmina_tp_handler_new
StatusNotifier/Appindicator support: not supported by desktop. Remmina will try to fallback to GtkStatusIcon/xembed
Running under Gnome Shell version 3.26.1

(remmina:12728): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[09:32:03:354] [12728:12737] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[09:32:03:354] [12728:12737] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[09:32:04:549] [12728:12737] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRA32
[09:32:04:549] [12728:12737] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[09:32:04:554] [12728:12737] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp

(remmina:12728): Gdk-CRITICAL **: Window 0x555b79d3d650 has not been made visible in GdkSeatGrabPrepareFunc

**Comment by antenore** [comment] 2017-11-03 06:39
How did you install Remmina? 

OS version ? Remmina version?

**Comment by alirezaimi** [comment] 2017-11-03 07:39
@antenore 

[root@alireza-pc alireza]# pacman -Qi remmina
Name            : remmina
Version         : 1:1.2.0rcgit.22-1
Description     : remote desktop client written in GTK+
Architecture    : x86_64
URL             : http://www.remmina.org/
Licenses        : GPL
Groups          : None
Provides        : remmina-plugins
Depends On      : gtk3  zlib  libjpeg  libssh  avahi  vte3  libgcrypt  libxdmcp  libsecret
                  webkit2gtk
Optional Deps   : libxkbfile [installed]
                  freerdp [installed]
                  telepathy-glib [installed]
                  gnome-keyring [installed]
                  nxproxy
                  spice-gtk3
                  xorg-server-xephyr: XDMCP support
                  libvncserver: VNC client/server support
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : remmina-plugins
Installed Size  : 2.27 MiB
Packager        : Sergej Pupykin <pupykin.s+arch@gmail.com>
Build Date      : Mon 23 Oct 2017 06:54:18 PM +0330
Install Date    : Sat 28 Oct 2017 08:56:13 PM +0330
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by antenore** [comment] 2017-11-03 07:46
Weird, would you mind trying the aur version? By eworm. Should be remmina-next

**Comment by alirezaimi** [comment] 2017-11-03 19:27
`[alireza@alireza-pc ~]$ remmina
StatusNotifier/Appindicator support: not supported by desktop. Remmina will try to fallback to GtkStatusIcon/xembed
Running under Gnome Shell version 3.26.1

(remmina:24932): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[22:55:11:692] [24932:24938] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[22:55:11:692] [24932:24938] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[22:55:13:886] [24932:24938] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRA32
[22:55:13:886] [24932:24938] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[22:55:13:889] [24932:24938] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp

(remmina:24932): Gdk-CRITICAL **: Window 0x56512aab8660 has not been made visible in GdkSeatGrabPrepareFunc
^C
[alireza@alireza-pc ~]$ remmina -V
StatusNotifier/Appindicator support: not supported by desktop. Remmina will try to fallback to GtkStatusIcon/xembed
Running under Gnome Shell version 3.26.1

Remmina - Version 1.2.0-rcgit-24 (git 0a094a1d6)

NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
NX                  Protocol        NX - NX Technology                                              1.2.0-rcgit-24
RDP                 Protocol        RDP - Remote Desktop Protocol                                   RDP Plugin: 1.2.0-rcgit-24 (git 0a094a1d6), FreeRDP lib: 2.0.0-dev (git 5416c2724)
RDPF                File            RDP - RDP File Handler                                          RDP Plugin: 1.2.0-rcgit-24 (git 0a094a1d6), FreeRDP lib: 2.0.0-dev (git 5416c2724)
RDPS                Preference      RDP - Preferences                                               RDP Plugin: 1.2.0-rcgit-24 (git 0a094a1d6), FreeRDP lib: 2.0.0-dev (git 5416c2724)
SFTP                Protocol        SFTP - Secure File Transfer                                     1.2.0-rcgit-24
SSH                 Protocol        SSH - Secure Shell                                              1.2.0-rcgit-24
VNC                 Protocol        VNC - Virtual Network Computing                                 1.2.0-rcgit-24
VNCI                Protocol        VNC - Incoming Connection                                       1.2.0-rcgit-24
XDMCP               Protocol        XDMCP - X Remote Session                                        1.2.0-rcgit-24
glibsecret          Secret          GNOME libsecret                                                 1.2.0-rcgit-24
telepathy           Entry           Telepathy - Desktop Sharing                                     1.2.0-rcgit-24
`

**Comment by antenore** [comment] 2017-11-03 19:34
Thank you

**Comment by giox069** [comment] 2017-11-03 19:43
We should try to reproduce the problem, but we are still unable to reproduce it... and we need more data from you :(
Are you using the standard Gnome Shell or some derived desktop (Budgie or others) ?
How many monitors? Resolution for each monitor?
Are you using a profile created with an older version of remmina? Have you tryed to create a new profile?
Thank you.

**Comment by antenore** [comment] 2017-11-15 23:08
Remmina has been upgraded to rcgit-24 in the main Arch linux community packages

community/remmina 1:1.2.0rcgit.24-1

So I'm closing this.

**Closed by antenore** 2017-11-15 23:08 UTC
Labels: outofscope
