### ISSUE TITLE
Problem connecting to Windows machine since this last patch Tuesday

### ISSUE THREAD

**Issue by stonerough** [FreeRDP/Remmina#1515] opened 2018-03-15 08:34 UTC
Please give us some details about the systems you are using:
* Client (OS name and version):  Ubuntu 16.04
* Remmina version (remmina --version): 1.2.0-rcgit-27 (git rcgit-27)
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Windows 10 / 2012 / 2016
* Connecting via (RDP, VNC, ...): RDP

Since this week "patch Tuesday" updates I have not been able to use Remmina to connect to any updated Windows system - always get "Unable to establish a connection to RDP server .... This has occured from two different Ubuntu 16.04 machine (work and home)

Yes this is likely to be something on the Windows boxes but even downgrading the security at the Windows end is not helping... I am seeking ideas - wondering if others have encountered the same issue!

Peter

**Comment by Razerwire** [comment] 2018-03-15 08:40
Duplicate of #1513

**Comment by giox069** [comment] 2018-03-15 10:38
@stonerough if you are using our PPA, just update your system. Follow the discussion on issue #1513. I'm closing this issue now.

**Closed by giox069** 2018-03-15 10:38 UTC

**Comment by stonerough** [comment] 2018-03-15 18:50
@giox069 thanks for the pointer to the solution - I had tried changing settings but obviously not that one!
