### ISSUE TITLE
Remmina isn't saving connections

### ISSUE THREAD

**Issue by coventry** [FreeRDP/Remmina#1438] opened 2018-01-14 19:44 UTC
When I hit the "Create a new connection profile" button, enter the details, and try to save it, first of all, the "save" button is grayed out. "save as default" and "save and connect" are clickable, but don't seem to have any impact.

```
$ remmina --version
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!
Remmina - 1.2.0-rcgit-26 (git rcgit-26)
```
```
$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
```
```
$ find ~ -name \*remmina\*
/home/alx/.config/autostart/remmina-applet.desktop
/home/alx/.config/remmina
/home/alx/.config/remmina/remmina.pref
/home/alx/.local/share/remmina
/home/alx/.cache/remmina
```
```
for p in `find ~ -name \*remmina\* -type f ` ; do 
  echo $p; echo '*********************************'; 
  cat $p ; 
done > /tmp/remmina-file-contents.txt # (Output is a attached)
```

[remmina-file-contents.txt](https://github.com/FreeRDP/Remmina/files/1629727/remmina-file-contents.txt)

**Comment by antenore** [comment] 2018-01-14 20:25
Don't you have an old Remmina version still installed?
Can you also execute Remmina from the command line and cut and paste here all the messages you'll have in the terminal?

**Comment by giox069** [comment] 2018-01-14 21:09
@coventry have you changed the 1st field value? The field "Name" seems to have a default value of "Quick connect". You need to change it to make the save button work.

**Comment by coventry** [comment] 2018-01-14 21:53
Thanks for the responses.

> Don't you have an old Remmina version still installed?

I've installed using the PPA. Here are the matches to `remmina` from `dpkg`:

```
# dpkg -l | grep remmina
ii  libfreerdp-plugins-standard:amd64          2.0.0~git201712281853-0+remmina201712282040.r4e42179.d9be5820~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp1:amd64                          2.0.0~git201712281853-0+remmina201712282040.r4e42179.d9be5820~ubuntu16.04.1 amd64        RDP client for Windows Terminal Services (library)
ii  remmina                                    1.2.0-rcgit-26-0~remmina201712282243.r3100877.d1bd53da~ubuntu16.04.1        amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                             1.2.0-rcgit-26-0~remmina201712282243.r3100877.d1bd53da~ubuntu16.04.1        all          common files for remmina remote desktop client
ii  remmina-plugin-rdp                         1.2.0-rcgit-26-0~remmina201712282243.r3100877.d1bd53da~ubuntu16.04.1        amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc                         1.2.0-rcgit-26-0~remmina201712282243.r3100877.d1bd53da~ubuntu16.04.1        amd64        VNC plugin for remmina remote desktop client
```

> Can you also execute Remmina from the command line and cut and paste here all the messages you'll have in the terminal?

This is the full output after creating a connection and clicking "Save and Connect":
```
$ remmina 
StatusNotifier/Appindicator support: your desktop does support it and libappindicator is compiled in remmina. Good!

(remmina:2374): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

> have you changed the 1st field value? The field "Name" seems to have a default value of "Quick connect". You need to change it to make the save button work.

That's in the `.desktop` file, which is part of the ubuntu desktop config. I don't think it should impact `remmina`'s behavior.

**Comment by antenore** [comment] 2018-01-14 22:03
Giovanni is right, I didn't read carefully the log you have shared.
When you edit the remmina profile you are going to connect to, if you don't replace Quick Connect with a name, the Remmina profile cannot be saved.

![image](https://user-images.githubusercontent.com/5975/34921190-13547f2a-f97f-11e7-86cf-bae0ab7161f2.png)

**Comment by coventry** [comment] 2018-01-14 23:37
Oh, `name=` in `remmina.pref`? I get it now. Thanks for the explanation. Where is this behavior documented?

**Comment by antenore** [comment] 2018-01-15 00:19
At the moment we have just this page https://github.com/FreeRDP/Remmina/wiki/Remmina-User's-guide but it's quite old and misses a lot of information.

If you are up to it you can contribute.

I'm closing this because it's not a bug.

**Closed by antenore** 2018-01-15 00:19 UTC
Labels: notabug, question
