### ISSUE TITLE
RDP remote files are listed with huge wrong size under 32bit client platforms

### ISSUE THREAD

**Issue by AngelNone** [FreeRDP/Remmina#1166] opened 2017-05-03 08:59 UTC
Good day. There was a problem. When you connect to RDP from Linux Mint, the files on the attached drive from the local computer increase the size from 2 bytes to 8 gigabytes. What is the problem with this problem? We use the latest version. When connecting with xreerdp the same problem, I attach a screenshot it may be easier to understand what is happening.
![2017-05-03 11-22-09](https://cloud.githubusercontent.com/assets/28342808/25653978/fcaa947c-2ff7-11e7-82f1-d330cc330acc.png)

**Comment by giox069** [comment] 2017-05-03 09:05
Are you using our Ubuntu PPA or did you compiled remmina by yourself?
Can you paste here the output of

```dpkg -l '*libfreerdp*'```

Thank you

**Comment by AngelNone** [comment] 2017-05-03 09:19
The installation package was downloaded from the official site and then updated via the update center.
![2017-05-03 12-18-49](https://cloud.githubusercontent.com/assets/28342808/25654696/bdc1a1b2-2ffa-11e7-8d38-5757aaa2cf35.png)

**Comment by giox069** [comment] 2017-05-03 11:55
Unfortunately I can't see the full version of libfreerdp1 in your screenshot.
Can you execute `dpkg -s libfreerdp1` and paste here the entire line which starts with "Version:" ?

The latest we published has version on our **remmina-next PPA**  is `2.0.0~dev201703030839+dfsg201704111144-0ubuntu0~git59a8418+e33fbeb~ubuntu16.04.1`

I also tried to reproduce the problem, but I'm unable to reproduce it.

Are you running on an Intel or ARM CPU?

What happens when you have more than one file on the same folder? And if the file is bigger than 2 bytes ?

Thank you

**Comment by AngelNone** [comment] 2017-05-03 12:10
Computers based on Intel. The problem manifested itself only on the 32-bit system. And after the last updates. That is, a couple of days ago everything worked. If the file is larger than 2 bytes, the same thing happens, according to my assumptions, 1 byte of the source file equals 4 gigabytes in the final form.
![2017-05-03 15-03-29](https://cloud.githubusercontent.com/assets/28342808/25659901/95ffbf20-3012-11e7-91db-20fa5f70e5f7.png)
![2017-05-03 15-06-24](https://cloud.githubusercontent.com/assets/28342808/25659923/a5bb10a4-3012-11e7-8051-137ae931b6d8.png)

**Comment by antenore** [comment] 2017-05-03 13:30
@AngelNone Open an issue to the FreeRDP developers:
https://github.com/FreeRDP/FreeRDP/issues/new

And reference this one as well. Thanks

**Comment by giox069** [comment] 2017-05-03 14:25
Got it! I compiled xfreerdp under a 32bit arch machine, and the problem appeared to me too.

**Comment by ic3d** [comment] 2017-09-23 18:44
I'm closing this issue because it's a (closed) FreeRDP one.

**Closed** 2017-09-23 18:44 UTC
