### ISSUE TITLE
SSH not passing locale info

### ISSUE THREAD

**Issue by thecrazy** [FreeRDP/Remmina#331] opened 2014-09-15 14:28 UTC
When I connect to a SSH server via Remmina the locale variables doesn't seem to be passed on.

In the options all there is is a setting to select the character set (but no language?). No matter what I set in Remmina the remote locale was allway set to "POSIX"

When I connect from the command line using ssh directly the proper locale is passed on to the server.

Anyone else getting that?

**Comment by antenore** [comment] 2015-06-20 23:24
In your ssh_config file, you should have an option like:

```
SendEnv LANG LC_*
```
So this is a duplicate of #235
I'll take a look on this

**Closed** 2015-09-23 05:14 UTC
Labels: bug, SSH
