### ISSUE TITLE
No RDP connection after latest update Ubuntu

### ISSUE THREAD

**Issue by kmg454** [FreeRDP/Remmina#657] opened 2015-10-21 10:46 UTC
Since 20-10-2015 after a update of Ubuntu we can't  make an RDP connection anymore

**Comment by antenore** [comment] 2015-10-21 19:26
Hi @kmg454 
can you be more specific please? What version of remmina and ubuntu do you have?
Did you install it from the PPA?

**Comment by kmg454** [comment] 2015-10-22 06:59
Hi.

I'm using the latest release of Ubuntu 14.04 LTS and Remmina 0.9.99.1

My RDP connection was working for 2 years without a problem but after 
the latest system update of Ubuntu 20-10-2015 it will not connect anymore.

When I use an other RDP client it works for 100%.




Met vriendelijke groet,
Johan Velthuizen
Velthuizen Webdesign & Media
Christineweg 17
2961 AB Kinderdijk
Tel. 078 6990167
www.velthuizen.nl

Op 21-10-15 om 21:27 schreef Antenore Gatta:

**Comment by antenore** [comment] 2015-10-22 07:16
This version is not supported anymore by us as it's too old, you should open a bug to Ubuntu (please do, it's important).

In the meanwhile you can use our ppa

```sh
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard
```

You will have also several new features and much less bugs

**Comment by faune** [comment] 2015-10-26 12:26
I've used remmina with remmina-plugin-rdp previously on Ubuntu 14.04.03LTS, but I beleive recent updates in this project have introduced a regression:

```
$ sudo apt-get install remmina-plugin-rdp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libfreerdp-plugins-standard libfreerdp1
The following NEW packages will be installed:
  libfreerdp1 remmina-plugin-rdp
The following packages will be upgraded:
  libfreerdp-plugins-standard
1 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/881 kB of archives.
After this operation, 2 963 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Selecting previously unselected package libfreerdp1:amd64.
(Reading database ... 289918 files and directories currently installed.)
Preparing to unpack .../libfreerdp1_1.2.0~git20150207+dfsg-0trusty2_amd64.deb ...
Unpacking libfreerdp1:amd64 (1.2.0~git20150207+dfsg-0trusty2) ...
dpkg: error processing archive /var/cache/apt/archives/libfreerdp1_1.2.0~git20150207+dfsg-0trusty2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/librdtk.so.1.1.0', which is also in package libfreerdp1.1:amd64 1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu14.04.1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../libfreerdp-plugins-standard_1.2.0~git20150207+dfsg-0trusty2_amd64.deb ...
Unpacking libfreerdp-plugins-standard:amd64 (1.2.0~git20150207+dfsg-0trusty2) over (1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu14.04.1) ...
Selecting previously unselected package remmina-plugin-rdp.
Preparing to unpack .../remmina-plugin-rdp_1.1.2-ppa1+789+next+201510182216~ubuntu14.04.1_amd64.deb ...
Unpacking remmina-plugin-rdp (1.1.2-ppa1+789+next+201510182216~ubuntu14.04.1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libfreerdp1_1.2.0~git20150207+dfsg-0trusty2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I believe the conflict is due to me using the pidgin-sipe PPA, which also has its own version of libfreerdp but the package names do not match and they are attempting to overwrite each others files.

I understand that supporting all variants of unofficial PPAs can be tricky to handle by you, but can you please advice on what can be done to solve this? I'm depending on both Remmina supporting RDP and the latest improvements to Pidgin SIPE.

**Comment by kmg454** [comment] 2015-10-26 12:33
I just installed the package by the ppa and everything works as 
aspected, but when installing it removed my VLC package WHY?

Met vriendelijke groet,
Johan Velthuizen
Velthuizen Webdesign & Media
Christineweg 17
2961 AB Kinderdijk
Tel. 078 6990167
www.velthuizen.nl

Op 26-10-15 om 13:26 schreef faune:

**Comment by antenore** [comment] 2015-10-26 14:01
@giox069 @dktrkranz Can you please advise on these issues? Thanks!

**Comment by maMykola** [comment] 2016-01-13 11:30
After last update of remmina and ubuntu (14.04.3 LTS) rdp protocol disappeared from the list.

after executing the following commands:
> apt-get remove --purge remina remina-plugin-*
> apt-get install remina remina-plugin-rdp libfreerdp-plugins-standard

no rdp protocol in the list

```
ii  freerdp-x11                                           1.2.0~git20151218+dfsg-0trusty1 amd64                           RDP client for Windows Terminal Services
ii  remmina                                               1.1.2-ppa1+819+next+20160112183 amd64                           remote desktop client for GNOME desktop environment
ii  remmina-plugin-rdp                                    1.1.2-ppa1+819+next+20160112183 amd64                           RDP plugin for remmina remote desktop client
```

**Comment by maMykola** [comment] 2016-01-13 12:21
After several tries, I remove remmina and plugins. I found folder /opt/remmina_devel that has also removed. Then I install remmina and rdp appeared in the list!!!

**Comment by giox069** [comment] 2016-01-13 12:27
Ok, thank you @maMykola. I'm closing this issue now. It's old enough to be forgotten :)

**Closed by giox069** 2016-01-13 12:27 UTC
Labels: unconfirmed
