### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by alqu1m1sta** [FreeRDP/Remmina#831] opened 2016-04-11 20:49 UTC
Hello to everybody
I have in mind implement a program capable of controlling a few number of computers in order to display their information in another one known for me as the master computer. 
Every computer is in the same LAN. 
I would like to use remmina in a command line. I am going to create a script and send it to the master computer (after logged in a ssh service) that will display the remote desktop of the computer I want to show.
So I need to know how to setup, create a connection and disconnect it in a terminal using the command line. 
I do not know if this is a bad question but I would like to know how to do it or if there is another tool that make it possible. 
At the end of the project I will deliver a GUI application in a computer (Ubuntu running a ssh connection to the master) to the end user in order to select any computer to display its desktop in the master computer. 

 The features of my system are:
Every computer will use Ubuntu desktop 14.04 LTS
Remmina 1.2
The master is Ubuntu 
The connection is VNC

I really appreciate your help or your guideline because I am new in ubuntu and making this project will be my first one so I am very excited about using this amazing Operating system

**Comment by antenore** [comment] 2016-04-13 07:43
Hi ,

Github should be used only for development issues, why don't you follow us on G+ (link in the Remmina help menu)? We can continue the discussion over there.

I'm not sure I've completely understood what you want to accomplish, in the meanwhile I give you some info you will probably need (anyway). 

Let me know what do you think (on G+ if it's ok for you). I've to close this because this is not a bug.

With Remmina is possible to setup a (local) command or a script that is execute before and one that is executed after a connection.
Additionally you can send custom keystrokes in the remote computer.

![selection_130](https://cloud.githubusercontent.com/assets/5975/14485963/bf9365a4-015a-11e6-86e1-c81a24d87a38.png)

![selection_132](https://cloud.githubusercontent.com/assets/5975/14486024/170d6de8-015b-11e6-8c12-689cda8ed4d4.png)

Finally you can execute remmina from the command line

```
remmina -c ~/.local/share/remmina/1403789259120.remmina
```

@giox069

**Closed by antenore** 2016-04-13 07:43 UTC

**Comment by giox069** [comment] 2016-04-13 07:51
> So I need to know how to setup, create a connection and disconnect it in a terminal using the command line. 

Remmina currently cannot disconnect a session via commandline. There some commandline vnc clients for linux around which are more commandline friendly than remmina. For example xtightvncviewer.
You can start vncviewer from the commandline and then kill it to close the connection.
Please use our Google+ community for non remmina development related discussions.
