### ISSUE TITLE
Clipboard doesn't work

### ISSUE THREAD

**Issue by morfeus929** [FreeRDP/Remmina#730] opened 2016-01-18 14:20 UTC
Clipboard doesn't work when I use RDP from Ubuntu - to Windows.

**Comment by morfeus929** [comment] 2016-01-18 14:31
Even if it sometimes work just for text, it doesn't work with files at all.

**Comment by antenore** [comment] 2016-01-18 21:05
Can you please provide the remmina and freerdp version?

**Comment by morfeus929** [comment] 2016-01-19 20:08
No remmina -v not remmina --version can't show the version. It should be the last available from your ..next repo.

**Comment by antenore** [comment] 2016-01-19 20:25
So you have an old version of remmina, because these options has been added by the commit 3e92940d 

Follow the wiki to update it https://github.com/FreeRDP/Remmina/wiki and let me know how it goes (remove all the packages you have of remmina and freerdp before to install the new one)

**Comment by giox069** [comment] 2016-01-19 20:34
I have just noticed that `remmina --version` works only when remmina is not running (whe should fix that). So kill remmina before running `remmina --version`, with `killall remmina`.
Or use the help->about dialog inside the remmina application.

**Comment by antenore** [comment] 2016-01-19 21:15
It works indeed, but you will see it in the Remmina stdout.
Start remmina from the command line and then, from another shell execute

```remmina -v```

and you will get the version.
We should see if we can redirect the output to the current STDOUT.

Let 's open a new issue about this if it makes sense to fix it (for example opening a gtkdialog or teh about dialog).

Good catch btw, thanks Gio.

**Comment by morfeus929** [comment] 2016-01-22 13:00
my version:
Version 1.2.0-rcgit.8
It's the last version as I can see.
Text clipboard works last few days.
Tell me please if it's possible to use clipboard for file transfer? RDP on Windows can do it.

**Comment by antenore** [comment] 2016-01-22 13:09
This is (file clipboard transfer)something I've often issue with as well, and it depends on FreeRDP and not Remmina.

There is a lot of discussion regarding the clipboard in the last days.

Please be patient. 

@giox069

**Comment by morfeus929** [comment] 2016-01-25 10:13
Yes.
I installed xreerdp uthing guide https://github.com/FreeRDP/FreeRDP/wiki/Compilation
and launched with command
xfreerdp +clipboard /size:1800x1000 /u:Sombra /p:TkHht4fFnNvv /v:52.10.202.173
Text clipboard works in both directions.
It would great to have file clipboard, as on Windows's native RDP implementation.

**Comment by antenore** [comment] 2016-01-25 10:30
Can you kindly comment on https://github.com/FreeRDP/FreeRDP/issues/2424 and https://github.com/FreeRDP/FreeRDP/pull/1732 it looks like it has been implemented, but not working anymore

**Comment by antenore** [comment] 2016-01-25 10:43
Also PR https://github.com/FreeRDP/FreeRDP/pull/2851 could improve things. @giox069 Do you think we can test that PR to validate that it works with Remmina?

**Comment by MartinHaimberger** [comment] 2016-01-25 10:54
@morfeus929 u posted ur WORKING password. Change password asap and dont post information like this ever again ...

**Comment by giox069** [comment] 2016-01-25 11:02
@morfeus929 @MartinHaimberger: I have edited the post to hide it. But many people has already received your password and public IP via e-mail, so yes, change it immediately. :) :)

**Comment by giox069** [comment] 2016-01-25 11:06
@antenore: https://github.com/FreeRDP/FreeRDP/pull/2851 seems to be limited to the xfreerdp client (we do not use it). So it's not useful to test it. It will be useful to recheck clipboard format support in remmina RDP plugin against that PR, but only to add new formats support.

**Comment by morfeus929** [comment] 2016-01-25 13:21
MartinHaimberger, sorry for that and thank you!!

**Comment by morfeus929** [comment] 2016-01-28 10:43
Ok, so when can I expect working file clipboard on Remmina?

**Comment by hellboy81** [comment] 2016-02-26 09:52
Is there another solution without clipboard problems?

**Comment by giox069** [comment] 2016-03-06 17:50
I have just published a small fix. For ubuntu PPA users: wait until tomorrow before testing. Let me know.

**Comment by antenore** [comment] 2016-03-06 21:37
:+1:

**Comment by StevenLOL** [comment] 2016-03-08 03:32
client:
ubuntu 15.10
remmina 1.2.0-rcgit.9(git n/a)

not work when login to ubuntu 15.10 via xfce4

**Comment by hellboy81** [comment] 2016-03-08 06:42
we are still waiting for release with fixed bug...

**Comment by antenore** [comment] 2016-03-08 08:54
@StevenLOL Do you have the same issue connecting to a Windows Server
@hellboy81 File copy/èaste deos not work for me on xfreerdp either. If it does not work with freerdp, it cannot work with Remmina.

Does copy/paste of text works for you between windows and linux?

**Comment by giox069** [comment] 2016-03-08 09:51
This issue should be closed: it's a collection of different problems on different versions of remmina, different protocol plugins, different RDP servers and clients, different clipboard contents.

So, @antenore, if you agree we can close it.

Since in our tests we do not see any problem with the clipboard, you are kindly requested to help us to reproduce your problem. So we ask you to open one or more new issues by indicating clearly:

1. The version of remmina you are using `remmina --version`
2. The version of xfreerdp you are using `xfreerdp --version`
3. The OS name and version on which remmina is running
4. The desktop environment under which remmina is running (Unity, GnomeShell, Xfce,...)
5. How did you installed remmina (from your distribution packages, from our ubuntu PPA, from our source code compiling as explained in the wiki...)
6. The remmina protocol/plugin you are using for the connection in which you have the clipboard problems: RDP, VNC, SSH, SFTP...
7. The destination operating system you are connecting to, please include both the OS name and its version.
8. If you are connecting to a linux/bsd/'nix OS, please also add which server software you are using to allow remote desktop connections.
9. Which kind of content are you trying to copy and the source application: a string fo text from google chrome ? an image from internet explorer ? A file from windows explorer ?

Please note that copying and pasting files is currently NOT supported in remmina RDP plugin, because it seems to be not currently supported by FreeRDP. So before opening an issue requesting to copy & paste a file, test if it works with xfreerdp. If it works with xfreerdp, then you can proceed with opening an issue on remmina.

I hope this will help us to understand what's really happening.
Thank you.

**Comment by antenore** [comment] 2016-03-08 10:02
:+1:  I agree Gio (while I'm answering I close it)

**Closed by antenore** 2016-03-08 10:02 UTC

**Comment by hellboy81** [comment] 2016-03-15 07:20
> remmina --version

empty output

In Ubuntu software centre:

remmina 1.1.2-2ubuntu3

> xfreerdp --version

This is FreeRDP **version 1.1.0-beta1 (git n/a)**

> 4.

Unity on Ubuntu 15.10

> 6.

RDP

>7. 

Windows Server 2012

>9 

Text from any text field in Linux to any text box in Windows VM and vice versa

**Comment by giox069** [comment] 2016-03-15 07:25
@hellboy81 install remmina from the "remmina-next" PPA, instructions are on the [wiki](https://github.com/FreeRDP/Remmina/wiki).
Please don't reuse cloded issues. Thank you.

**Comment by hellboy81** [comment] 2016-03-15 09:11
>Please don't reuse cloded issues. Thank you.

Where can I get support in this case?

Problem still exists with update version

```
1.2.0-rcgit.10 (git n/a)
```

**Comment by zandao** [comment] 2016-11-30 17:38
What @giox069 said is exactly what @hellboy81 did (and me too). The URL does not exist. Not any more.

**Comment by giox069** [comment] 2016-11-30 20:29
The PPA is still there, and has never been removed.

I just tested the first part of the Remmina's wiki instructions, on a Ubuntu 16.04,
```sudo apt-add-repository ppa:remmina-ppa-team/remmina-next```
and the answer was:
```
giovanni@uno:~$ sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
 PPA for development (next branch) Remmina packages
 More info: https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next
Press [ENTER] to continue or ctrl-c to cancel adding it
```
You can see the PPA here [https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next](https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next)
Currently the PPA supports Ubuntu 14.04, 15.10, 16.04 and 16.10.
Which ubuntu version are you using?
Are you accessing the internet via a firewall which blocks the access to launchpad.net ?

**Comment by louisrubet** [comment] 2017-06-06 15:00
@zandao @hellboy81 did you run `sudo apt-add-repository ppa:remmina-ppa-team/remmina-next` behind a proxy ? It seems it does not work, even with `http_proxy` and `https_proxy` set and **even with apt.conf correctly configured with your proxy**.
