### ISSUE TITLE
error: ‘rdpGdi {aka struct rdp_gdi}’ has no member named ‘bytesPerPixel’

### ISSUE THREAD

**Issue by svanschalkwyk** [FreeRDP/Remmina#1028] opened 2016-10-27 18:58 UTC
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
- Client (OS name and version): Linux Mint 18 Sarah
- Remmina version (remmina --version): 1.2 (next)
- Desktop environment (GNOME, Unity, KDE, ..): mate
- Connecting to (OS and version): Ubuntu 15.10
- Connecting via (RDP, VNC, ...): RDP
- RDP issues only, freerdp version (xfreerdp --version): freerdp, remmina make

/opt/remmina_devel/freerdp/include/freerdp2/freerdp/addin.h:59:17: note: expected ‘FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN {aka _Bool (\* (_)(const char *, char *, char *, unsigned int))(struct tagCHANNEL_ENTRY_POINTS *)}’ but argument is of type ‘void \* (_)(const CHAR _, CHAR *, CHAR *, DWORD) {aka void \* (_)(const char *, char *, char *, unsigned int)}’
 FREERDP_API int freerdp_register_addin_provider(
                 ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c: In function ‘remmina_rdp_close_connection’:
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1163:5: warning: implicit declaration of function ‘freerdp_channels_close’ [-Wimplicit-function-declaration]
     freerdp_channels_close(instance->context->channels, instance);
     ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1186:3: warning: implicit declaration of function ‘freerdp_clrconv_free’ [-Wimplicit-function-declaration]
   freerdp_clrconv_free(rfi->clrconv);
   ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1187:16: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
   rfi->clrconv = NULL;
                ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1189:4: warning: implicit declaration of function ‘freerdp_channels_free’ [-Wimplicit-function-declaration]
    freerdp_channels_free(instance->context->channels);
    ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c: In function ‘remmina_rdp_get_screenshot’:
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1275:41: error: ‘rdpGdi {aka struct rdp_gdi}’ has no member named ‘bytesPerPixel’
   szmem = gdi->width \* gdi->height \* gdi->bytesPerPixel;
                                         ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1286:32: error: ‘GDI_DC {aka struct _GDI_DC}’ has no member named ‘bitsPerPixel’
   rpsd->bitsPerPixel = rfi->hdc->bitsPerPixel;
                                ^
/home/steph/Projects/FreeRDP/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:1287:28: error: ‘rdpGdi {aka struct rdp_gdi}’ has no member named ‘bytesPerPixel’
   rpsd->bytesPerPixel = gdi->bytesPerPixel;
                            ^
remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/build.make:62: recipe for target 'remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o' failed
##

**Comment by giox069** [comment] 2016-10-27 20:02
Check if you have the same prolem as already reported in issue #1012 #1015 #1021:
the current "next" branch only compiles with FreeRDP before october 6 2016.
You can use commit https://github.com/FreeRDP/FreeRDP/commit/1d06087b601a4cc723592e9a6efbf9bee0dc2d12.
In the meanwhile we are working to adapt remmina to the newer FreeRDP changes, but we need the current FreeRDP HEAD code to stabilize a bit more: there are at least three open regression bugs on FreeRDP issues page after October 6 commit.

**Comment by giox069** [comment] 2016-11-03 19:27
@svanschalkwyk can I close this issue ?

**Comment by joakim-tjernlund** [comment] 2016-11-07 13:48
I really need a working remmina with current freerdp(for pidgin-sipe with screen sharing).
Any ETA when remmina next will build with latest freerdp?

**Comment by giox069** [comment] 2016-11-07 17:19
@joakim-tjernlund, I have just updated the branch _libfreerdp_updates_ with the latest remmina "next" branch. _libfreerdp_updates_ has all the patches needed to compile Remmina against FreeRDP master branch. It's just a test, so please:

1. remmina maybe unstable when used from _libfreerdp_updates_
2. the _libfreerdp_updates_ branch will be repeatedly rebased to the next branch in the next days/weeks
3. current FreeRDP master branch is full of memory leaks

so please... use at your own risk and... let us know if it works :)

**Comment by joakim-tjernlund** [comment] 2016-11-07 17:37
it builds so that is a big plus :)
I do get this warning though:
```
/var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.c: In function ‘remmina_rdp_init’:
/var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.c:1129:34: warning: passing argument 1 of ‘freerdp_register_addin_provider’ from incompatible pointer type
  freerdp_register_addin_provider(freerdp_channels_load_static_addin_entry, 0);
                                  ^
In file included from /usr/include/freerdp2/freerdp/dvc.h:57:0,
                 from /usr/include/freerdp2/freerdp/channels/rdpgfx.h:24,
                 from /usr/include/freerdp2/freerdp/codec/h264.h:25,
                 from /usr/include/freerdp2/freerdp/codecs.h:29,
                 from /usr/include/freerdp2/freerdp/freerdp.h:46,
                 from /var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.h:40,
                 from /var/tmp/portage/net-misc/remmina-9999/work/remmina-9999/remmina-plugins/rdp/rdp_plugin.c:36:
/usr/include/freerdp2/freerdp/addin.h:59:17: note: expected ‘FREERDP_LOAD_CHANNEL_ADDIN_ENTRY_FN’ but argument is of type ‘void * (*)(const CHAR *, CHAR *, CHAR *, DWORD)’
 FREERDP_API int freerdp_register_addin_provider(
                 ^

**Comment by giox069** [comment] 2016-11-07 17:42
Yes, I saw it.
But you get the same warning compiling FreeRDP itself on their ./client/common/client.c file, so it should be a freerdp problem.
Thank you for reporting.

**Comment by joakim-tjernlund** [comment] 2016-11-07 17:42
I also noticed that one get an external_tools dir:
```
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/launcher.sh
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/functions.sh
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/remmina_filezilla_sftp.sh
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/remmina_filezilla_sftp_pki.sh
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/remmina_nslookup.sh
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/remmina_ping.sh
-- Installing: /var/tmp/portage/net-misc/remmina-9999/image/usr/share/remmina/external_tools/remmina_traceroute.sh
```
Should these be there? maybe on option defaulting to OFF?

**Comment by joakim-tjernlund** [comment] 2016-11-07 17:44
BTW, looks like the memory leaks in freerdp was plugged some weeks ago?

**Comment by giox069** [comment] 2016-11-07 17:46
external_tools: Yes, they should be there. @antenore: do you know if an option exists to disable it ?
If an option does not exists, open a new issue asking it as a new feature, but we do not have too much time to implement it :(

many memory leaks on FreeRDP have been introduced with the big FreeRDP commits of October 6, the same commits with breaks the current "next" branch of Remmina.

**Comment by joakim-tjernlund** [comment] 2016-11-07 18:11
OK, it builds and can do a RDP session against a Windows server. Lets see the next days.

**Comment by joakim-tjernlund** [comment] 2016-11-07 18:16
Could you not adapt remmina code dynamically against freerdp?
Then it will be users choice which freerdp to use and hopefully freerdp
bugs will be dealt with earlier.

**Comment by giox069** [comment] 2016-11-07 18:35
Every time they change the libfreerdp API we must manually reverse engineer it, try to understand the semantics and rewrite some code. This is what happened on october 6. They removed some functions from the APIs, they changed the callback process during a connection setup, and they added something new in color conversion.
There is no automatic way to adapt to such kind of eartquake.
And we can't stop them, because FreeRDP 2.0 is still unstable/unreleases.

**Comment by joakim-tjernlund** [comment] 2016-11-10 16:51
Yesterday I tested to join Screen Sharing session (a PPT slid presentation) and this worked well.
The only thing was that Remmina/FreeRDP was noticeable  slower to draw when the slide changed
compared to MS SfB

**Comment by giox069** [comment] 2016-12-16 22:08
@joakim-tjernlund: the libfreerdp_updates branch has been merged into "next", so it will be deleted.
Now remmina default branch (next) compiles with the latest FreeRDP (master) as expected.
I'm closing this issue.

**Closed by giox069** 2016-12-16 22:08 UTC

**Comment by joakim-tjernlund** [comment] 2016-12-17 08:23
Ok, thanks for letting me known. I will move to next branch now.
