### ISSUE TITLE
Auto-highlighted "Quick Connect" connection name within new connection dialog copies the words "Quick Connect" into PRIMARY selection

### ISSUE THREAD

**Issue by mystica555** [FreeRDP/Remmina#263] opened 2014-03-31 11:26 UTC
The title is mostly the bug.

When I attempt to create a new connection, the title input field is highlighted and the words "Quick Connect" auto-populated within this field.

The process of auto-highlighting is effectively placing the words "Quick Connect" within my PRIMARY X11 selection - displacing anything useful I had there before I attempted to create a new connection.. like the IP address.  

Do you even test your program to see that it doesnt do weird shit?

**Comment by muflone** [comment] 2015-01-03 12:22
First of all thank you for reporting this issue in the Remmina bug tracker.

However this bug is not really a bug and mainly is not related to Remmina but as far I can see it's related to the GTK+ library as it seems to be reproducible on every GTK+ application that I've used so far, actually tested on Geany, Nautilus file manager and deluge BitTorrent client but not limited to that.

The primary clipboard selection is automatically filled with any value that has been **selected** from ANY text entry from any GTK+ application.

Closing as invalid issue.

**Comment by mystica555** [comment] 2016-08-20 19:19
This is actually a bug, because I should not need to continually open a new connection window, and then be forced to go back into my clipboard manager simply because OPENING THE WINDOW causes my copied IP:port combination to disappear. 

This should be fixable by one of the following:
DISABLE THE "Quick Connect" text in the Name box
DO NOT AUTO-SELECT the "Quick Connect" text in the Name box
Instead SHOW PLACEHOLDER TEXT:

https://developer.gnome.org/gtk3/3.2/GtkEntry.html#gtk-entry-set-placeholder-text
gtk_entry_set_placeholder_text ()
void                gtk_entry_set_placeholder_text      (GtkEntry *entry,
                                                         const gchar *text);
Sets text to be displayed in entry when it is empty and unfocused. This can be used to give a visual hint of the expected contents of the GtkEntry.
Note that since the placeholder text gets removed when the entry received focus, using this feature is a bit problematic if the entry is given the initial focus in a window. Sometimes this can be worked around by delaying the initial focus setting until the first key event arrives.
entry :
a GtkEntry
text :
a string to be displayed when entry is empty an unfocused, or NULL
Since 3.2

It is _infuriating_ that simply opening the window MODIFIES MY CLIPBOARD SELECTION

I've waited for a year for you to figure out this is a problem, and fix it, but no, so I am writing here again, still angered EVERY SINGLE TIME i create a new server in my remmina server list.

PLEASE FIX THIS.

**Comment by mystica555** [comment] 2016-08-20 19:21
Oh and I just read now in the text i copied "this can be problematic if the if the entry is given initial focus"

SIMPLY STOPPING THE INITIAL FOCUS IN THIS FIELD WOULD FIX THE BUG

**Comment by antenore** [comment] 2016-08-20 20:12
Reopened. 

I had the same issue sometime, I'll take a look, but be patient some more time.

**Comment by antenore** [comment] 2016-08-22 19:56
@mystica555 I'm working on this issue, but honestly reading your posts doesn't help, if you'd be just a bit more polite it'd be more pleasant. Just to remember you that this is a volunteer project. Nobody between us earn money for this (and we don't want to), or maybe you nothing about netiquette and in the case RTFM!

BTW, I think I've found a solution and I'm testing it.  Can you please tell me which desktop environment you are using? The more you say about your particular setup the less we will have to deal with issues like:

> Do you even test your program to see that it doesnt do weird shit?

Thank you Sir.

**Closed** 2016-08-24 21:22 UTC
Labels: bug
