### ISSUE TITLE
Huge icons in toolbar in some desktop environments

### ISSUE THREAD

**Issue by giox069** [FreeRDP/Remmina#826] opened 2016-04-07 10:53 UTC
Under LXQT and KDE, some icons in the toolbar inside are too big. The same problem can be observed on the floating toolbar.

![selezione_011](https://cloud.githubusercontent.com/assets/5477803/14348756/e3db36d0-fcbe-11e5-9fbf-b35de7df328f.png)

**Comment by antenore** [comment] 2016-04-07 19:29
I can confirm the issue.

**Comment by giox069** [comment] 2016-04-11 12:57
It also happens on other remmina windows
![preferenze del desktop remoto_012](https://cloud.githubusercontent.com/assets/5477803/14427549/ab5d6bb8-fff5-11e5-8d72-f63c8c444e1b.png)

**Comment by antenore** [comment] 2016-04-11 13:17
Looks like it's theme issue... I'm investigating

**Comment by antenore** [comment] 2016-04-11 14:32
I cannot reproduce the issue on Fedore fc22 + LXQT vanilla. :-( I've pushed on wm-hints a little improvement.

Let me know.

**Comment by benkohler** [comment] 2016-04-26 15:39
I don't know if this will help or not, but a user reported this exact issue yesterday in Freenode\#gentoo on 1.2.0_rc3, I helped him build a snapshot of commit 0fb13e17749bd30ac9f6d2bbebc88bbdc65053e1 and the issue went away.

**Comment by antenore** [comment] 2016-04-26 16:00
Probably the commit 1dab13ac0532d330545c74da90b50d7ff4563565 is the one that fixed the problem.
@giox069 is it solved also for you this issue?

In that case we can tag a new version.

@benkohler thanks for your support.

**Comment by giox069** [comment] 2016-04-26 16:31
Nothing changed with the last code in the "next" branch. I think I have a problem in my local PC, and Qt based desktops are choosing a bad GTK style or icon set.
I'm investingating.

**Comment by giox069** [comment] 2016-04-26 16:41
Installed "lxappaerance", set new style and now all is better... I will test on KDE later.

**Comment by metalight** [comment] 2016-10-26 15:46
I can confirm the big icons appear running under KDE when Breeze Icon theme is selected, and not any of the other icon themes I could select.

**Comment by antenore** [comment] 2016-10-26 16:21
Yes, it's a theme issue. I'll close this.

**Closed** 2016-10-26 16:21 UTC

**Comment by Riamse** [comment] 2018-01-31 00:55
Does anyone know where this issue is being tracked? I'm seeing this same problem (with breeze icons only, for some reason) except for my entire desktop...
