### ISSUE TITLE
[Feature] SSH maintain session on unstable connection

### ISSUE THREAD

**Issue by Inglebard** [FreeRDP/Remmina#1487] opened 2018-02-21 09:57 UTC
Hi,

Since I use Remmina, I notice the window close if there is packets drop. I understand why, but on Remmina it's very sensitive.

This behaviour is present for example on Gnome Terminal, but the session is closed with a lot more packets drop.

Should be great if the is a way to "fix" this.

**Comment by antenore** [comment] 2018-02-21 10:57
Which remmina and libssh version do you have? I've recently improved it, so I'm curous to know if you are using a relatively old version

**Comment by antenore** [comment] 2018-02-21 11:00
I've applied a patch in the version v1.2.0-rcgit.27

**Comment by Inglebard** [comment] 2018-02-21 11:02
Hi,
libssh : 0.7.5-2
remmina : 1.2.0-rcgit-26 (git rcgit-26)

**Comment by Inglebard** [comment] 2018-02-21 11:03
Oh, ok, I should try v1.2.0-rcgit.27 so.

**Comment by antenore** [comment] 2018-02-21 11:06
yes, please I'm really really curious, this is a quite old issue that I's like to close.

**Comment by antenore** [comment] 2018-02-21 11:10
Duplicate of #975

**Comment by Inglebard** [comment] 2018-02-21 13:26
I just update to 1.2.0-rcgit.27.

To simulate a packet drop, I unplug ethernet cable few seconds, here are my observations :

1.2.0-rcgit.26 : 
-> Remmina close the window

1.2.0-rcgit.27 : 
-> Remmina keep the window open except if you input something during offline period (so not perfect)

Gnome Terminal : 
-> Seems to enter in a freeze state, even if you input something during offline period. When the cable is plug, it remembers the inputs during offline period and continue working.

**Comment by antenore** [comment] 2018-02-21 13:34
Does it recover from the the connection drop if you don't type anything?

**Comment by antenore** [comment] 2018-02-21 13:47
I've just tried myself.

I've opened an SSH connection, unplugged the cable, wrote something in the Remmina terminal (nothing happens, but the windows is still there), plugged back the cable and what I've previously typed suddenly appears.

This looks a good behaviour to me, isn't it?

```sh
$ lsb_release -idc
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Codename:       TwentySix

$ remmina --full-version 2>/dev/null
Remmina - 1.2.0-rcgit-27 (git 644cd140)
NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
EXEC                Protocol        Execute a command                                               1.0
NX                  Protocol        NX - NX Technology                                              1.2.0-rcgit-27
RDP                 Protocol        RDP - Remote Desktop Protocol                                   RDP Plugin: 1.2.0-rcgit-27 (git 644cd140), FreeRDP lib: 2.0.0-dev2 (git e1cc60196)
RDPF                File            RDP - RDP File Handler                                          RDP Plugin: 1.2.0-rcgit-27 (git 644cd140), FreeRDP lib: 2.0.0-dev2 (git e1cc60196)
RDPS                Preference      RDP - Preferences                                               RDP Plugin: 1.2.0-rcgit-27 (git 644cd140), FreeRDP lib: 2.0.0-dev2 (git e1cc60196)
SFTP                Protocol        SFTP - Secure File Transfer                                     1.2.0-rcgit-27
SPICE               Protocol        SPICE - Simple Protocol for Independent Computing Environments  1.2.0-rcgit-27
SSH                 Protocol        SSH - Secure Shell                                              1.2.0-rcgit-27
VNC                 Protocol        VNC - Virtual Network Computing                                 1.2.0-rcgit-27
VNCI                Protocol        VNC - Incoming Connection                                       1.2.0-rcgit-27
XDMCP               Protocol        XDMCP - X Remote Session                                        1.2.0-rcgit-27
glibsecret          Secret          GNOME libsecret                                                 1.2.0-rcgit-27
telepathy           Entry           Telepathy - Desktop Sharing                                     1.2.0-rcgit-27
$ cat /proc/sys/net/ipv4/tcp_keepalive_intvl /proc/sys/net/ipv4/tcp_keepalive_probes /proc/sys/net/ipv4/tcp_keepalive_time
75
9
7200
$ dnf info libssh
slack                                                                                                                                                                                                                           19 kB/s |  30 kB     00:01
Last metadata expiration check: 0:00:00 ago on Wed 21 Feb 2018 02:45:51 PM CET.
Installed Packages
Name         : libssh
Version      : 0.7.5
Release      : 1.fc26
Arch         : x86_64
Size         : 508 k
Source       : libssh-0.7.5-1.fc26.src.rpm
Repo         : @System
From repo    : anaconda
Summary      : A library implementing the SSH protocol
URL          : http://www.libssh.org
License      : LGPLv2+
Description  : The ssh library was designed to be used by programmers needing a working SSH
             : implementation by the mean of a library. The complete control of the client is
             : made by the programmer. With libssh, you can remotely execute programs, transfer
             : files, use a secure and transparent tunnel for your remote programs. With its
             : Secure FTP implementation, you can play with remote files easily, without
             : third-party programs others than libcrypto (from openssl).
```

**Comment by Inglebard** [comment] 2018-02-21 13:58
If I don't type anything it recover. But if I type it closes the window.

```bash
$ lsb_release -idc
Distributor ID:	Arch
Description:	Arch Linux
Codename:	n/a

$ remmina --full-version 2>/dev/null
Running under Gnome Shell version 3.26.2
Remmina - 1.2.0-rcgit-27 (git rcgit-27)
NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
EXEC                Protocole       Execute a command                                               1.0       
NX                  Protocole       NX — Technologie NX                                           1.2.0-rcgit-27
RDP                 Protocole       RDP — Remote Desktop Protocol                                 RDP Plugin: 1.2.0-rcgit-27 (git rcgit-27), FreeRDP lib: 2.0.0-rc1 (git n/a)
RDPF                Fichier         RDP — gestionnaire de fichiers RDP                            RDP Plugin: 1.2.0-rcgit-27 (git rcgit-27), FreeRDP lib: 2.0.0-rc1 (git n/a)
RDPS                Préférences   RDP — Préférences                                           RDP Plugin: 1.2.0-rcgit-27 (git rcgit-27), FreeRDP lib: 2.0.0-rc1 (git n/a)
SFTP                Protocole       SFTP — transfert de fichiers sécurisé                       1.2.0-rcgit-27
SPICE               Protocole       SPICE — Simple Protocol for Independent Computing Environments1.2.0-rcgit-27
SSH                 Protocole       SSH - Shell sécurisé                                          1.2.0-rcgit-27
VNC                 Protocole       VNC — Virtual Network Computing                               1.2.0-rcgit-27
VNCI                Protocole       VNC — Connexion entrante                                      1.2.0-rcgit-27
XDMCP               Protocole       XDMCP — session X distante                                    1.2.0-rcgit-27
glibsecret          Secret          GNOME libsecret                                                 1.2.0-rcgit-27
telepathy           Entrée         Telepathy — partage de bureau                                 1.2.0-rcgit-27

cat /proc/sys/net/ipv4/tcp_keepalive_intvl /proc/sys/net/ipv4/tcp_keepalive_probes /proc/sys/net/ipv4/tcp_keepalive_time
75
9
7200

$ sudo pacman -Qii libssh
Nom                      : libssh
Version                  : 0.7.5-2
Description              : Library for accessing ssh client services through C libraries
Architecture             : x86_64
URL                      : http://www.libssh.org/
Licences                 : LGPL
Groupes                  : --
Fournit                  : --
Dépend de                : libgcrypt  zlib
Dépendances opt.         : --
Requis par               : ffmpeg  ffmpeg2.8  remmina  wireshark-cli
Optionnel pour           : --
Est en conflit avec      : --
Remplace                 : --
Taille installée         : 628,00 KiB
Paqueteur                : Antonio Rojas <arojas@archlinux.org>
Compilé le               : mer. 14 juin 2017 11:06:15 CEST
Installé le              : mer. 14 juin 2017 16:12:50 CEST
Motif d’installation     : Installé comme dépendance d’un autre paquet
Script d’installation    : Non
Validé par               : Signature
Fichiers de sauvegarde   :
(aucun)
```

**Comment by antenore** [comment] 2018-02-21 14:47
This is really weird, I've developed the patch on my Arch, so I'm sure it was working there.

I'll test again at the first occasion. If it'll work, an it's what I expect, I don't even know from where to start to debug this.

**Comment by Hypocritus** [comment] 2018-03-31 17:05
Dev, thanks for all you do!!!!!!!!!!

I am also having this problem over a wifi connection with the new Remmina (.26 or .27) . Give me 30 seconds after I connect, and the majority of the time I get closed. Usually while trying to do something. With the original Xenial Remmina, my windows never closed when I was on wifi. I upgraded to prevent from having to type in my SSH password each time. But I inherited closing windows over Wifi! Over wire it's not an issue.

I have also disabled power management on my adapter to prevent that from being a factor, but it didn't help. For the time being I will have to revert to the default Xenial Remmina b/c typing in my password once per session is worth not breaking.

I'm sure you'll figure this out, and THANKS AGAIN for all you do!!!!!!!!! WE LOVE YOU!!!!!

**Comment by antenore** [comment] 2018-03-31 20:21
@Hypocritus Thanks for your support!

I really have a bad time reproducing it, lately I've even tried to unplug the cable or disconnect the wifi network and rarely I loose the connection.

I've to say that on wifi this happens more often, but still rarely.

I'll continue to investigate.

**Comment by Hypocritus** [comment] 2018-04-01 00:15
Thanks, Antenore!

More info:

-The USB Wifi module I am using is an Edimax, using the 8814au driver. I
want to say that I also have the issue with rtl8812au dongles (who thinks
of these words??? Sounds like donkeys and dingleberries)
- Kernel is 4.4.anything.
- Wifi router is an Archer C7 using DD-WRT.
- Motherboards are any of the Supermicro X10??? Series.
- CPUs are random Haswell and Broadwell

I downgraded to stock Xenial Remmina a couple of hours ago, and really
enjoying the rock-stable ... stability!

**Comment by antenore** [comment] 2018-04-06 23:45
Bingo!

... or at least  I think so

First of all, I've found a reliable way to reproduce this issue

```sh
iptables -I OUTPUT -p tcp --dpor 22 -j DROP ; sleep 5; iptables -D OUTPUT -p tcp --dpor 22 -j DROP
```
Rising up the sleep counter if needed but as is the remmina code today it's enough even 1 second of sleeping.

I've created a test branch and found the code that was causing the problem. A TCP parameter that we thought was expressed in seconds, but on alas, it was in milliseconds. Therefore Remmina was dropping the connection if there were no answer from the server after 4 ms seconds after the first keepalive sent.

I've raised this timeout to 60000 ms (60 secs).

I'm going to merge this quite soon in the next branch if there are any volunteers we can finally close this and other similar issues.

**Comment by Hypocritus** [comment] 2018-04-07 00:46
AWESOME!

Nice job, Antenore!

Here's a crazy thought. What do you think about making this a configurable
parameter anywhere (config file, etc) for those of us that might have
breaks longer than 60 seconds?

Or, I wonder if 90, 120 or 150 seconds is inappropriate.  For instance, I
live in a RF crowded space, yet am forced to use 2.4GHz for most of my
connections b/c that signal travels further. However, recently there are
nearby routers who go psycho every now and then amping their signals well
above what Is legal for sometimes minutes at a time. I have chosen the
least crowded space, but there are also routers that periodically like to
hop over to my channel until they find out that it is not very hospitable
b/c I'm using it for several connections across 3 rooms. Sometimes I return
to my remote connection between DC and Massachusetts and find the session
closed.

But 60 seconds is MUCH better than 60 ms!!

Nice work!!

**Comment by antenore** [comment] 2018-04-07 00:51
Yes sure, it's feasible. I'll have a look in the next few days.

**Comment by Inglebard** [comment] 2018-04-07 07:51
Hi,
I just test the patch.
Just perfect. Really nice job.
Thanks.

**Comment by Hypocritus** [comment] 2018-04-07 16:27
Hi,

How do I make sure I have this patch applied? Should I build from scratch?
Or for Ubuntu, was it sufficient to newly do the following from the old
(xenial) version?

sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt-get update
sudo apt-get install remmina remmina-plugin-rdp libfreerdp-plugins-standard

**Comment by antenore** [comment] 2018-04-07 16:59
The daily is updated.

Do

remmina --version

**Comment by Hypocritus** [comment] 2018-04-07 18:50
Thanks Antenore, I had already tried that, but I couldn't tell that the new
patch was installed. It said

*1.2.0-rcgit-27*

But that's the same version that had been giving me problems prior to
reverting, and my remote VNC over SSH connections were still dropping like
dehydrated gnats. So I ended up compiling from scratch with these
instructions:

https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-16.04

Now it says

*1.2.0-rcgit-28 (git fae9c94)*

And I am currently testing...

- Hypocritus

**Comment by antenore** [comment] 2018-04-10 22:26
@Hypocritus , @Inglebard 

![image](https://user-images.githubusercontent.com/5975/38586641-d69ce782-3d1e-11e8-876a-4250ced6dfd5.png)

It's coming to 'next', that means that in few days you'll be able to use it either

**Comment by antenore** [comment] 2018-04-10 22:29
EDIT: edited the previous comment as pushed "comment" before I've finished to write it.

**Closed** 2018-04-10 22:50 UTC
Labels: SSH, enhancement, review

**Comment by antenore** [comment] 2018-04-12 10:02
Now available on SNAP for those in urgent need.

**Comment by antenore** [comment] 2018-04-13 07:44
And on flatpak as well

```sh
flatpak remote-add --user flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-ls -a --user | grep remmina
flatpak install --user flathub org.remmina.Remmina
```

**Comment by Hypocritus** [comment] 2018-04-17 03:50
@Antenore,

Just wanted to report that this definitely fixed the short-term closing
issue. Very nice to have this functionality!

I can confirm the usefulness of having a user-setting for the timeout. Our
internet service (apart from wifi) was having 2 minute dropouts every 5 to
10 minutes for 2 or 3 days. But it is nice (and solid) to have Remmina keep
the connection during interruptions of less than 60 seconds.

A question: what is the secret to having that ability to open up a new
sshell terminal connection from (I believe) the Tools menu every time?
There are times when I have connected to an ssh session, but when I click
the icon, only 4 options show, two of which are copy and paste, but not
[Open a New Secure Connection] (sorry for the paraphrasing, I'm currently
on a train)

**Comment by Hypocritus** [comment] 2018-04-17 03:53
Woah! Just saw the graphic! Nice! Looking forward to the new user settings!
Nice work, Dev!

**Comment by antenore** [comment] 2018-04-17 09:37
@Hypocritus thanks :-) For general purpose questions (regarding the tools i.e.) asks on G+ or reddit please
