### ISSUE TITLE
main window won't hide in i3

### ISSUE THREAD

**Issue by karlsebal** [FreeRDP/Remmina#926] opened 2016-07-13 17:30 UTC
Thank you for Remmina. I am on an ubuntu 16.04 running Remmina 1.2.0-rcgit.14 (git n/a) installed via ppa. I have Unity installed but am using i3.

It is not possible to close the main window. In the tray I only can "show main window" but not hide it. In the Menu there is no such action as well. Since there are no window decorations there is no possibility to hide the main window.

**Comment by antenore** [comment] 2016-07-13 19:39
If you are using i3 you should close the main remmina window with your i3 shortcut, for me it's mod4+c

**Comment by karlsebal** [comment] 2016-07-13 20:38
if you are referring to the shortcut "close window" defaulting to Shift+$mod+q then remmina will close not only the main window.

**Comment by antenore** [comment] 2016-07-13 20:41
c , not q , q is used to quit i3, not?

```
bindsym Mod4+Shift+c kill
```

**Comment by antenore** [comment] 2016-07-13 20:49
Yes, I confirm

1) I start Remmina
2) I focus the Remmina file editor (the Remmina main window)
3) I hit Mod4+Shift+c
4) Remmina is still running and I can see the tray icon

Now, the issue, for me, it's that I don't have setup a shortcut to (re)open Remmina

5) I execute remmina (that is already running) and the remmina main window show up again.

**Comment by antenore** [comment] 2016-07-13 20:50
I'll keep this opened for now. Let me know.

**Comment by karlsebal** [comment] 2016-07-13 21:22
This behaviour is true for 1.1.2 where Shift+$mod+q (default) will close the main window as well as the remmina-shortcut Ctrl-X. But this is gone in 1.2 where is no menu bar but a button and it says "quit" not close and shortcut is Ctrl-Q.

**Comment by antenore** [comment] 2016-07-13 21:25
```sh
$ remmina --version
remmina - Version 1.2.0-rcgit.14 (git bc80656)
```
I think I know what I'm testing :-) don't you?

**Comment by karlsebal** [comment] 2016-07-13 21:29
What is the line in i3-config? Mine says

`bindcode $mod+Shift+24 kill`

as told in the i3-doku. Am I missing something? What is happening when you hit Ctrl-q? Are there any differences with your version and the ppa?

**Comment by antenore** [comment] 2016-07-13 21:32
Bingo! 

I think that  **bindcode $mod+Shift+24 kill** cannot work at all

Mine is https://github.com/antenore/dotfiles/blob/master/i3/.i3/config#L29 

I was answering before your reply, here after the original message

I'd like to help but I don't get where is the issue.

I'm a long time i3 and dwm user on Fedora, FreeBSD, Arch Linux and Ubuntu, but I really cannot reproduce your issue.

Are you sure you have only one version of remmina installed? Can you please try to purge all the remmina and freerdp packages you have and reinstall the PPA?

    - Update your ubuntu, if you have limited bandwidth, you can ignore this.

	apt-get update.

    - Remove all remmina and freerdp packages

	sudo apt-get --purge remove freerdp-x11 remmina remmina-common remmina-plugin-rdp remmina-plugin-vnc remmina-plugin-gnome remmina-plugin-nx remmina-plugin-telepathy remmina-plugin-xdmcp
    
    - Install the new remmina version

	sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
	# the following line is optional if you have limited bandwidth.
	sudo apt-get update
	sudo apt-get install remmina remmina-plugin-rdp

**Comment by karlsebal** [comment] 2016-07-13 21:35
`28 # kill focused window`
`29 bindsym Mod4+Shift+c kill`

**Comment by karlsebal** [comment] 2016-07-13 21:45
I did not purge but after the dist-upgrade running in background finnished I now have the expected behavior: ctrl-q will quit, shift+$mod+q will close only main window. It was a pretty large upgrade and I cannot imagine what should have fixed that but, well, ..

I have a second machine I had this issue some hours ago if you are interested I can have a closer look at that but for me the issue is closed. 

Thank you for helping, anyway!

**Comment by antenore** [comment] 2016-07-13 21:47
Cool! :-)

I close this, but, for reference, if you find anything useful just add comments here.

Thanks!

**Closed by antenore** 2016-07-13 21:47 UTC
Labels: notabug, question
