### ISSUE TITLE
Files in mounted sharefolders become terrabytes big.

### ISSUE THREAD

**Issue by Optica1** [FreeRDP/Remmina#1174] opened 2017-05-12 12:23 UTC
The files in a mounted sharefolder are suddenly very big when connecting to a windows 2012 server.
For example a 33 MB file becomes over 145 TB.

This does not happen on my other computer with remmina version 1.1.2.

Lubuntu 14.04
remmina - Version 1.2.-rcgit-18
LXDE
Connecting to windows server 2012 R2 via RDP
FreeRDP version 1.2.0-beta1

**Comment by giox069** [comment] 2017-05-12 12:28
Hi @Optica1.
Just confirm me that you are using a 32 bit lubuntu, and not a 64bit one.
Your bug can be a duplicate of issue #1166. I'm sorry, currently issue #1166 has a wron, too genenric, title "Problem Connect to RDP". I'm going to rename it now.

**Comment by Optica1** [comment] 2017-05-12 12:34
Hello @giox069,
Very fast answer! 
It seems that issue #1166 is indeed the same problem as mine. I am on a 32-bit system.
Sorry for duplicate, I didn't find this one.

**Comment by giox069** [comment] 2017-05-12 12:38
Ok, I'm going to close this issue now. If you want to receive notifications, just add a comment on issue #1166 or enable notifications on its page.
Work is in progress to solve it by the FreeRDP team, I hope :)

**Closed by giox069** 2017-05-12 12:38 UTC
