### ISSUE TITLE
WINPR_INCLUDE_DIR Set to not found

### ISSUE THREAD

**Issue by CryptoJones** [FreeRDP/Remmina#1281] opened 2017-09-15 15:00 UTC
With latest git clone on Centos 7.1, I received the following error;

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WINPR_INCLUDE_DIR
   used as include directory in directory /home/akclark/src/Remmina/remmina-plugins/rdp

**Comment by antenore** [comment] 2017-09-15 20:08
We have tested the latest FreeRDP without issues.

You must uninstall completely freerdp and remmina and also clean the build directory of FreeRDP and Remmina, only just after you can compile both and it should work.

I'm closing this because it's not a bug. If you need support reach us on G+, reddit or irc (on irc the next week).

**Closed by antenore** 2017-09-15 20:08 UTC
