### ISSUE TITLE
Enter key doesn't "Connect" when in Edit menu and password field is in focus

### ISSUE THREAD

**Issue by erichoog** [FreeRDP/Remmina#1233] opened 2017-07-31 00:04 UTC
When I'm in the Edit Menu (Ctrl + E) and I type in my password the Enter button doesn't "Connect".

If the Server field is in focus it seems to work fine.

Version 1.2.0-rcgit-19 (git rcgit-19)
Arch Linux with KDE Plasma Desktop (5.10.4-1)

**Comment by giox069** [comment] 2017-07-31 09:19
Confirmed. Enter works for me only on the Server field.

**Comment by giox069** [comment] 2017-08-03 14:53
Leaving it open: I cant make it work under ubuntu 17.04.
@antenore, isn't it a better choice to have the Connect (which does Save+Connect) by default on all the fields of the profile editor?

**Comment by erichoog** [comment] 2017-08-03 16:22
I agree! I just couldn't figure out exactly how to implement that. Still learning the source so looking forward to seeing the best solution for this.


-------- Original message --------

**Comment by antenore** [comment] 2017-08-07 19:59
Yep, it's not a bad idea.
Let me deal with some annoying bugs and then I'll try to help out as well.

BTW the default buttons are very tricky in glade, I think it's better to look at the GTK+ documentation to see if there is a function or a parameter for this.

**Comment by antenore** [comment] 2017-08-08 19:56
Well, it should be quite straightforward.

I'm writing here just as a memo, if you don't have time I'll try it in the next days.

Each GtkEntry (each server, username, password fields) can have ```gtk_entry_set_activates_default ()``` that tell Gtk to activate the default widget when pressing enter.

At the moment the default widget is the Connect button as defined [here](https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_file_editor.c#L1248-L1252) with gtk_dialog_set_default_response

```gtk_entry_set_activates_default ()``` is set for the server and the password field

https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_file_editor.c#L406 
https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_file_editor.c#L459

As in the password field does not work it means that it cannot determine the right widget hierarchy and therefore get the right default button... So

I'll try to modify directly the code and create a pull request, bu I don't have time to test it, can you?

**Comment by antenore** [comment] 2017-08-09 12:32
It works. I've merged and closed this.

**Comment by erichoog** [comment] 2017-08-09 12:39
@antenore  Awesome thanks! Sorry i didn't have a chance to test it until later today or tomorrow.

**Comment by erichoog** [comment] 2017-09-29 17:19
@antenore I'm on Version 1.2.0-rcgit-20 (git rcgit-20) and the issue doesn't seem to be resolved.

Should I reopen it?

**Comment by antenore** [comment] 2017-09-30 20:59
Really weird, I'm sure I've tested this ...

**Comment by erichoog** [comment] 2017-09-30 21:15
Is there anything I can try? I was downloading this package from the Arch AUR but I can try building the next branch and see if it is working maybe

**Comment by antenore** [comment] 2017-09-30 22:43
No, because it's really not working, also in the development branch.

I'll fix it in the next minutes hopefully, but you won't be able to test it till the next release.

As you are using Arch the AUR package should be updated, even if the version number often is not correct.

I'll keep updated, thanks for your support!

**Comment by erichoog** [comment] 2017-09-30 23:00
Awesome sounds good, I thought that about the package on the AUR [https://aur.archlinux.org/packages/remmina-git](url) it shows version remmina-git 1.2.0.rcgit.18.r51.g2c0a77e12-1 but when I clone the repo there and check the PKGBUILD it does show that it's getting the next branch of the official remmina repo.

Thanks again for looking at this, hoping to help more as well just still have alot to learn.  Thanks!

**Comment by antenore** [comment] 2017-09-30 23:09
:-)
It's easier than you think, I'm not a developer (well it's quite obvious that I'm not :-P ), and I keep trying till it works.

Maybe you can help out managing the AUR package? There is very little to do, like keeping the version updated, but I don't know what is needed to do to become a package maintainer

**Comment by antenore** [comment] 2017-09-30 23:39
I need some more time to fix it.

**Comment by antenore** [comment] 2017-09-30 23:54
Done, it's in next already.
I close this again, but don't hesitate to reopen it.

**Closed by antenore** 2017-09-30 23:54 UTC
Labels: enhancement
